### ISSUE TITLE
Investigation: Custom Dashboard Improvements

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#1007]
# Bugs
 - ~Map features (geojson) are synced with other maps (e.g. airplane detection)~ beae99d9, 16219b22
 - ~Maps that have a boundary are not easy to move sometimes have a wrong center (jump back when zoomed out)~ 44f4dc92
 - ~Maps that have not saved a center/zoom once reset their center/zoom if other maps are updated~ 263207b2
- ~Compare mode on maps does not work~ 7f53a955
- ~Custom area charts are not stored properly and do not persist between sessions~ 5aec260d
- ~Editing the title of an indicator breaks the title of the same indicator on race.esa.int (may be connected to back button and/or page reload)~ 40f95abf
- ~Click on title of indicator takes user to race.esa.int but not to the respective indicator (right panel remains blank)~ 40f95abf
- ~Sometimes, the "Add to custom dashboard button" is still overlaying the chart (e.g. Mobility Data) and thus also not visible in dark mode~ d3c50186

# Improvements
- Consider adding  a "save chart position" similar to the "save map position"; explore options in chart.js

**Comment by aapopescu** [comment]
Other bugs:
Some actions in custom-dashboard break the main race.esa.int view (in safari):
1. editing the title of an indicator breaks the title of the same indicator on race.esa.int
2. click on title of indicator takes user to race.esa.int but not to the respective indicator (right panel remains blank)
![image](https://user-images.githubusercontent.com/35488732/129004213-9a4d5bd9-1c3d-468a-9173-b58cea3b00a8.png)

**Comment by silvester-pari** [comment]
>     1. editing the title of an indicator breaks the title of the same indicator on race.esa.int
By "breaking" you mean it only displays a comma (" , ")? If so, this seems to be connected to using the back button and/or reloading the page, don't think it has to do with title editing. Added to the issue description.

**Comment by aapopescu** [comment]
> > ```
> > 1. editing the title of an indicator breaks the title of the same indicator on race.esa.int
> > ```
> 
> 
> By "breaking" you mean it only displays a comma (" , ")? If so, this seems to be connected to using the back button and/or reloading the page, don't think it has to do with title editing. Added to the issue description.

Yes exactly

**Comment by silvester-pari** [comment]
Regarding 
> Compare mode on maps does not work

can you provide details which steps you took? I tried with various indicators and they all worked
![image](https://user-images.githubusercontent.com/26576876/129177205-c4027f41-6893-4b6e-9535-1accd26daf5a.png)

![image](https://user-images.githubusercontent.com/26576876/129177248-55ca14d0-3b21-4bd0-ae30-2dcae34743bd.png)

**Comment by santilland** [comment]
Created new issue for improvement suggestion #1721
Issue of title editing seems to have been solved, so propose to close this issue for now as it contains multiple points, if issue appear again we can create a new specific issue for that.
