### ISSUE TITLE
Add EO Data view to custom-dashboard

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#1114]

**Comment by silvester-pari** [comment]
Background information: For most indicators, there is the "EO Data" button underneath the story. This is the "input" data for the indicator chart.
Consider making it possible adding this map view to the custom indicator selection.

**Comment by aapopescu** [comment]
@silvester-pari , can you confirm this can be closed with the UI simplification?

**Comment by aapopescu** [comment]
will be resolved with OL migration
