### ISSUE TITLE
Make news section temporary to save screen estate

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#1129]
Especially on mobile, it takes a lot of space, and is actually not needed permanently. Example: 

![grafik](https://user-images.githubusercontent.com/26576876/142245236-a94c72d4-5438-4df0-ad90-074f20951ca8.png)

**Comment by silvester-pari** [comment]
Handled by #1146 , keeping this open to track

**Comment by aapopescu** [comment]
News handled on Homepage for EO Dashboard and Carousel for RACE.
