### ISSUE TITLE
Add 3D globe as POI data visualization option

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#1138]
This globe also needs to be embeddable, and addable to custom dashboard. Example: 
![grafik](https://user-images.githubusercontent.com/26576876/142247605-3e13c1f7-c5a6-4605-8cf2-9dbd2de70ebc.png)

**Comment by silvester-pari** [comment]
Depends on #1229

**Comment by silvester-pari** [comment]
A good first display example could be Tropomi CO: https://github.com/eurodatacube/eodash/blob/staging/app/src/config/esa.js#L2269-L2304

In the end, the globe view should replace the current map view:
![image](https://user-images.githubusercontent.com/26576876/153163088-f6d417f1-7c04-469e-b543-a0cc102987f1.png)

**Comment by RobertOrthofer** [comment]
Concerning the data of the Tropomi CO: it seems the `CORS`-header are not correctly set. No matter the globe implementation, we would need the CORS header [to be set correctly](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin), so we can access the image data and warp it for the application needs.
Ideally these headers should be set directly by the server, alternatively a small proxy could also set these headers.
