### ISSUE TITLE
add a tutorial for how to use the dashboard

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#115]
- [ ] poi selection
- [ ] filtering
- [ ] data (graph or map) panel
- [ ] eo data incl. time selection and comparison
- [ ] graph interactions like zoom
- [ ] ...

**Comment by silvester-pari** [comment]
we could implement something like https://pulsardev.github.io/vue-tour/ to have the tutorial in a step-by-step, interactive way (as requested in #217 )

**Comment by silvester-pari** [comment]
started in the add-tour branch, but moved to a future release

**Comment by aapopescu** [comment]
@silvester-pari , FYI, Sara is preparing some video tutorials. Maybe once they are online we can link to them from the dashboard, perhaps from the welcome page?

**Comment by silvester-pari** [comment]
Sure, in the welcome text there is just the markdown to update, the rest above (carousel, number of indicators) has to be changed in the code though.

**Comment by aapopescu** [comment]
tutorials published on Medium
