### ISSUE TITLE
Document out map features currently supported

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#1173]
So that we have a list of "behavior" we intend to support in our main map component, which other issues are referring to.

**Comment by lubojr** [comment]
# indicatorMap features
## Behavior
- Show xyz/wms Baselayers
- Show/hide xyz/wms Overlays
- Show WMS/XYZ tile layers based on selected indicator
- differentiate between "data" (right) and "compare" (left) set of layers. Both are in different "map pane". Compare layer is shown only when "compare button" is toggled.
- Allow to cycle through time selections for both data/compare. Time and other optional parameters (siteMapping etc.) from configs based on selected time get passed to the wms/xyz url parameters.
- Show Legend div from url + expand it on click
- show detection "features" for both data/compare with tooltip div with filtered properties from geojson
- show detection features clustered (turned on for trucks)
- show subaoi multipolygon and inverse multipolygon (with 50% opacity)
- merge layers into layer groups and display them as Leaflet LayerGroup
- draw bbox or polygon for detection features search, fetch data and display them
- draw bbox or polygon for custom indicator data chart, initiate fetch + store data
- fetch mobility data
- delete currently drawn bbox/polygon
- select country for some indicators
- select GSA indicator from feature pois
- show/hide warning on a limit of features when configured and exceeded
- display custom label on left/right side of the screen
- Toggle fullscreen
- Show loading indicator, current mouse coordinates, attributions
- Zoom to subaoi bounds +- margin when first shown, constrain map panning to +- margin, largeSubAoi config increases the margin
​
## Configurations
- allow to disable time selection completely
- add "extra" time entries, remove time entries or completely replace time entries array for indicator
- label shown in the time selection box is configurable, time can have different formats (1 value vs array), custom format function, eoSensor is usually appended
- merge layer/detections configs coming from following sources
    - defaultLayersDisplay
    - indDefinition - indicator code specific configuration
    - display/compareDisplay - coming from js configuration for single indicator
    - configFromInputData - coming from input data value from geodb matching against our config for given time index
- above mentioned allows to set different layer configuration for data/compare side
    - either via currently selected time index configuration from inputData
    - or via compareDisplay configuration
# map features
## behavior
- select indicator from poi
- cluster pois
- change color of poi based on data
- change size of poi if selected
- change style of cluster if poi from it selected
- show tooltip on hover with indicator info
- show country borders vectors

**Comment by silvester-pari** [comment]
# Examples:

## show subaoi multipolygon and inverse multipolygon (with 50% opacity)
![image](https://user-images.githubusercontent.com/26576876/151534492-41e0a6a5-7d93-4b1d-b168-f01a4ff630a4.png)

In this example, the sub-AOI polygon is shown "inverse", meaning the contents of the polygon are transparent, whereas the rest of the map has reduced opacity. So basically the actual polygon is "cut out" of an overlay with 50% opacity.

**Comment by silvester-pari** [comment]
Here's the list from above turned into a checklist!

# indicatorMap features
## Behavior
- [ ] Show xyz/wms Baselayers
- [ ] Show/hide xyz/wms Overlays
- [ ] Show WMS/XYZ tile layers based on selected indicator
- [ ] differentiate between "data" (right) and "compare" (left) set of layers. Both are in different "map pane". Compare layer is shown only when "compare button" is toggled.
- [ ] Allow to cycle through time selections for both data/compare. Time and other optional parameters (siteMapping etc.) from configs based on selected time get passed to the wms/xyz url parameters.
- [ ] Show Legend div from url + expand it on click
- [ ] show detection "features" for both data/compare with tooltip div with filtered properties from geojson
- [ ] show detection features clustered (turned on for trucks)
- [ ] show subaoi multipolygon and inverse multipolygon (with 50% opacity)
- [ ] merge layers into layer groups and display them as Leaflet LayerGroup
- [ ] draw bbox or polygon for detection features search, fetch data and display them
- [ ] draw bbox or polygon for custom indicator data chart, initiate fetch + store data
- [ ] fetch mobility data
- [ ] delete currently drawn bbox/polygon
- [ ] select country for some indicators
- [ ] select GSA indicator from feature pois
- [ ] show/hide warning on a limit of features when configured and exceeded
- [ ] display custom label on left/right side of the screen
- [ ] Toggle fullscreen
- [ ] Show loading indicator, current mouse coordinates, attributions
- [ ] Zoom to subaoi bounds +- margin when first shown, constrain map panning to +- margin, largeSubAoi config increases the margin
​
## Configurations
- [ ] allow to disable time selection completely
- [ ] add "extra" time entries, remove time entries or completely replace time entries array for indicator
- [ ] label shown in the time selection box is configurable, time can have different formats (1 value vs array), custom format function, eoSensor is usually appended
- [ ] merge layer/detections configs coming from following sources
    - defaultLayersDisplay
    - indDefinition - indicator code specific configuration
    - display/compareDisplay - coming from js configuration for single indicator
    - configFromInputData - coming from input data value from geodb matching against our config for given time index
- [ ] above mentioned allows to set different layer configuration for data/compare side
    - either via currently selected time index configuration from inputData
    - or via compareDisplay configuration
# main map features
## Behavior
- [ ] select indicator from poi
- [ ] cluster pois
- [ ] change color of poi based on data
- [ ] change size of poi if selected
- [ ] change style of cluster if poi from it selected
- [ ] show tooltip on hover with indicator info
- [ ] show country borders vectors

**Comment by silvester-pari** [comment]
This can be closed since this was just documentation for the migration.
