### ISSUE TITLE
Shipping density indicator

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1201]
Possibility for new indicator:
Alessandro has added new layers

visualization layers:
VIS_SHIPPINGDENSITY_CARGO
VIS_SHIPPINGDENSITY_CARGO
VIS_SHIPPINGDENSITY_PASSENGER
VIS_SHIPPINGDENSITY_TANKER

raw data layers:
RAW_SHIPPINGDENSITY_CARGO
RAW_SHIPPINGDENSITY_CARGO
RAW_SHIPPINGDENSITY_PASSENGER
RAW_SHIPPINGDENSITY_TANKER

Current status, intial implementation in the /shipdensity/ branch, is deployed on testing.

Anca and Alessandro will discuss with creator from another indicator and decide how to continue with implementation

**Comment by santilland** [comment]
possible credits to be added:
https://www.emodnet-humanactivities.eu/search-results.php?dataname=Vessel+Density+

**Comment by santilland** [comment]
new layers:
ID: VIS_VESSELDENSITY_CARGO
ID: RAW_VESSELDENSITY_CARGO
ID: VIS_VESSELDENSITY_TANKER
ID: RAW_VESSELDENSITY_TANKER
ID: VIS_VESSELDENSITY_OTHER
ID: RAW_VESSELDENSITY_OTHER

**Comment by santilland** [comment]
layers added as tabbed content and deployed to testing environment /shipdensity/

**Comment by AlessandroScremin** [comment]
@santilland 
it seems nice to me, only one remarks...is it intended to show data only to 2019/12 insted of 2020/12, or there are no data coming for 2020?

**Comment by santilland** [comment]
@AlessandroScremin i must have understood the dates wrong at some point, i updated the dates to end 2020/12

**Comment by santilland** [comment]
indicator was integrated, closing ticket now
