### ISSUE TITLE
Create landing pages for theme selection and individual themes

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#1217]
The theme selection landing page should
- display a short introduction to eodashboard
- allow the user to choose a specific theme
- show a selection of stories
- show an information about the "explore" mode (=map interface)

The individual theme landing page should
- be styled according to the color scheme of the current theme
- display a short introduction to the current theme
- display all stories for the current theme
- show an information about the "explore" mode (=map interface) which is filtered by the theme
- show a selection of the other available themes

**Comment by silvester-pari** [comment]
For the demo next week, these things need to be added:

- [ ] Landing Page: Stories from multiple themes
- [ ] Landing Page: "Explore" Section (section giving infromation about the dataset exploration and link to map view)
- [ ] Theme Page: Stories from single Theme
- [ ] Theme Page: "Explore" Section (see above) but links to a filtered version of the map view
- [ ] Map/Explore view: Add option to filter POIs depending on theme via query param
- [ ] Map/Explore view: Display Theme colors if filter is active
- [ ] Navigation: Top bar button for "explore" view, that links to unfiltered or filtered map view depending on if a theme is currently selected
- [ ] Custom Dashboard/Story: Show navigation and main button in theme color
- [ ] Review and improve story creation process - is creation of custom dashboard enough or do we need a dedicated create story mode?

**Comment by silvester-pari** [comment]
@spectrachrome idea for top menu bar?

**EARTH OBSERVING DASHBOARD** _(landing page)_
EARTH OBSERVING DASHBOARD / **Ocean** _(theme page)_
EARTH OBSERVING DASHBOARD / Ocean / **Explore** _(theme-filtered explore page)_
EARTH OBSERVING DASHBOARD / **Explore** _(unfiltered explore page)_

Some highlighting is needed to make sure the user knows where he/she is currently

**Comment by spectrachrome** [comment]
@silvester-pari   --- reminder

Users need to know how they can create custom dashboards. Either we make it really clear that one needs to place a POI to create a dashboard, or the link is always active and there is some kind of illustration/text there pointing them to how it's done.
