### ISSUE TITLE
Add new indicator global layer SO2 (N9)

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1230]
Layer identifiers are:
VIS_SO2_DAILY_DATA
RAW_SO2_DAILY_DATA

**Comment by AlessandroScremin** [comment]
Proposed indicator code

N9

**Comment by aapopescu** [comment]
Revert to Terrain light baselayer

**Comment by lubojr** [comment]
Reverted to terrain light baselayer and updated get chart from raw data config. Added in https://github.com/eurodatacube/eodash/pull/1326
