### ISSUE TITLE
Allow storing current time selection in custom dashboard element

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#1232]
Similar to storing the map location, it would be nice to also make storing the selected time possible.
- Add button to store current time state
- Pass additional fields to request
- Add corresponding fields to server code and database
- Implement parsing of time fields and automatically setting the time on data read
- Optional: store if compare mode is active, and also store compare time

**Comment by aapopescu** [comment]
- @silvester-pari , storing time in custom-dashboard could resolve this feature request from JAXA?
"synchronize the time stamp of several time series interactive map images by selecting only one time series tab (attached image) which is in one of the time series interactive map images, which are displayed side by side on the one page."
 
![image](https://user-images.githubusercontent.com/35488732/153827157-08c203b8-3512-4a41-9392-18078aae94ba.png)

**Comment by silvester-pari** [comment]
We agreed to implement a storage of map time selection.
- selected date
- optional: comparison date (if set, then in the custom dashboard mode automatically A/B comparison is activated)
