### ISSUE TITLE
Integration of DLR Feature as basemap layer

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1247]
@santilland @Schpidi @aapopescu @dmoglioni @lubojr 

for the trilateral dashboard, we would be interested in making the DLR World Settlement Footprint (WSF) Evolution layer available for the visual story telling: 
[https://geoservice.dlr.de/web/maps/eoc:wsfevolution]

They share the info on the WMS/WMTS etc. - Would this be sufficient for visualisation purposes in the eo-dash (i.e. no ingestion needed)? 

![layer](https://user-images.githubusercontent.com/65602207/154302407-09aa28c4-9e9d-486b-9040-87007df3262e.gif)

It would be important to also visualise the legend (see below) which is a bit hidden.. 

Patrick

**Comment by santilland** [comment]
Integrated in branch wsf_evolution, pull request created #1253

**Comment by santilland** [comment]
Indicator description text to be provided

**Comment by aapopescu** [comment]
Story is ready https://github.com/eurodatacube/eodash/pull/1308
