### ISSUE TITLE
Expanded indicator Panel goes behind map

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1299]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 3.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://eodash-staging.eox.at/?poi=WorldCO-N1">https://eodash-staging.eox.at/?poi=WorldCO-N1</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 98</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://eodash-staging.eox.at/?poi=WorldCO-N1">https://eodash-staging.eox.at/?poi=WorldCO-N1</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>expanding panel is on top of the map</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by silvester-pari** [comment]
Fixed in d40625c72637e9c0ee25972646b6730447c07163
