### ISSUE TITLE
Data integration overview for new data required for stories

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1307]
We want to have a central location to keep track of all datasets to be integrated into the dashboard in order to support the stories being created.

**JAXA**:
In order to be able to integrate the data into the dashboard also following steps are missing:
- [x] Jaxa to setup domain and https for service endpoint

Datasets

- [x] Sea Ice concentration (North/South) - integrated in `jaxadata` branch
- [x] ONPP GCOMC  - integrated in `jaxadata` branch
- [x] NO2 - currently test data over Cairo. will there be other locations?
- [ ] OIDC - currently test data over Cairo. will there be other locations?
- [x] GOSAT XCO2 - currently test data over Cairo. will there be other locations?
- [x] NDVI test layer, global, no date

**NASA**
Some of the datasets are already available but it would be good to be able to fetch available products/dates through the new stac api
New collections through the new API:
- [x] NO2 (yearly) - OMI_trno2-COG - monthly NO2 from NASA already available (@aapopescu so we need also yearly NO2?)
- [x] SO2 (yearly) - OMSO2PCA-COG 
- [x] Blackmarble HD nightlights dataset - nightlights-hd-monthly - available at NASA API
- [x] ICESat-2 L4 Monthly Gridded Sea Ice Thickness, Version 1 
- [ ] HR Population data

**CCI data**
Status of CCI integration can be followed here:
https://github.com/eurodatacube/eodash/issues/1231

**Comment by aapopescu** [comment]
> We want to have a central location to keep track of all datasets to be integrated into the dashboard in order to support the stories being created.
> 
> **JAXA**: In order to be able to integrate the data into the dashboard also following steps are missing:
> 
> * [ ]  Jaxa to setup domain and https for service endpoint
> 
> Datasets
> 
> * [x]  Sea Ice concentration (North/South) - integrated in `jaxadata` branch
> * [x]  ONPP GCOMC  - integrated in `jaxadata` branch
> * [ ]  NO2 - currently test data over Cairo. will there be other locations? --> NOT in this first batch of stories
> * [ ]  OIDC - currently test data over Cairo. will there be other locations? --> NOT in this first batch of stories
> * [ ]  GOSAT XCO2 - currently test data over Cairo. will there be other locations? --> NOT in this first batch of stories
> * [ ]  NDVI test layer, global, no date
> 
> **NASA** Some of the datasets are already available but it would be good to be able to fetch available products/dates through the new stac api New collections through the new API:
> 
> * [ ]  NO2 (yearly) - OMI_trno2-COG - monthly NO2 from NASA already available (@aapopescu so we need also yearly NO2?)  ----> YES
> * [ ]  SO2 (yearly) - OMSO2PCA-COG
> * [ ]  Blackmarble HD nightlights dataset - nightlights-hd-monthly - monthly nightlight already available for some locations, probably new locations coming @aapopescu ? --> Other locations coming but not in this first batch of stories
> * [ ]  ICESat-2 L4 Monthly Gridded Sea Ice Thickness, Version 1 - example cog file provided by Aimee, to be ingested into EDC (@AlessandroScremin will test ingestion of example into EDC)
> 
> **CCI data** Status of CCI integration can be followed here: #1231
