### ISSUE TITLE
Tile ingestion Issue

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1313]
Dear @gmilcinski @gobaRules cc: @aapopescu 

I Try to check if a new file recieved by a data provder is COG compliant. So I ingested it in the new Bucket and then created a tile in SH.

The ingestion failed with the following error: Ensure tiles of image at index 1 have width and height between 256 and 2048.
and I don't understand what exactly means. Checking the gdalinfo I wasn t able to understand where the issue is.

The file ingested is this one:
[IS2SITMOGR4_01_202101_004_001_COG.zip](https://github.com/eurodatacube/eodash/files/8287052/IS2SITMOGR4_01_202101_004_001_COG.zip)

And the script used is this one
[ingest_ICESAT_test.zip](https://github.com/eurodatacube/eodash/files/8287060/ingest_ICESAT_test.zip)

Could you please check and advise me what I is wrong so that I can report the error to the data provider?

Thanks a lot for the support
Ale

**Comment by gmilcinski** [comment]
Perfect, thanks for a report.

**Comment by silvester-pari** [comment]
@AlessandroScremin is this resolved? If not, feel free to reopen.
