### ISSUE TITLE
Indicators list not visible on mobile

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1322]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 3.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/?poi=World-E13o">https://race.esa.int/?poi=World-E13o</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 13</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>list of indicators is not visible on mobile</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>from the hamburger menu to access the list of indicators</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>anca</p>

**Comment by silvester-pari** [comment]
Thanks for reporting, this has been fixed in https://github.com/eurodatacube/eodash/commit/716c60a83690094844cf16708688478e418b5914 and will be merged soon.
