### ISSUE TITLE
zooming improvements

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#136]
there are various issues around zooming https://github.com/eurodatacube/eodash/issues?q=is%3Aopen+is%3Aissue+label%3Azooming

this issue is to discuss and decide the overall zooming strategy

**Comment by silvester-pari** [comment]
i think this can be closed, as zooming has overall improved and the max zoom has been reduced for single POI filters (8783de2078838c5ea2813a42df94dd6eadc48485)
