### ISSUE TITLE
Unpublish collections on GEODB

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1411]
Dears @dzelge @gmilcinski @AliceBalfanz 

 I would like to un-publish some of the collections I managed on the GEODB for the RACE  dashboard....

I'm able to make collection publich using this command you provided me:
- geodb.publish_collection(collection_name, database=database_name)

but unfortunately I can not unpublish using this command:

- geodb.unpublish_collection(collection_name, database=database_name)

I got this error, but the table is there and is public.

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/xcube_geodb/core/geodb.py:390, in GeoDBClient._post(self, path, payload, params, headers, raise_for_status)
    389     if raise_for_status:
--> 390         r.raise_for_status()
    391 except requests.exceptions.HTTPError:

File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/requests/models.py:960, in Response.raise_for_status(self)
    959 if http_error_msg:
--> 960     raise HTTPError(http_error_msg, response=self)

HTTPError: 404 Client Error: Not Found for url: [https://xcube-geodb.brockmann-consult.de:443/rpc/geodb_revoke_access_from_collection](https://xcube-geodb.brockmann-consult.de/rpc/geodb_revoke_access_from_collection)

During handling of the above exception, another exception occurred:

GeoDBError                                Traceback (most recent call last)
Input In [46], in <module>
      1 ## Add to Public
      2 #geodb.publish_collection("test_accessi", database="eodash_stage")
      3 #remove from public
----> 4 geodb.unpublish_collection("E1a", database="eodash")

File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/xcube_geodb/core/geodb.py:882, in GeoDBClient.unpublish_collection(self, collection, database)
    880     return self.revoke_access_from_collection(collection=collection, usr='public', database=database)
    881 except GeoDBError as e:
--> 882     return self._maybe_raise(e)

File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/xcube_geodb/core/geodb.py:514, in GeoDBClient._maybe_raise(self, e, return_df)
    512 def _maybe_raise(self, e, return_df=False):
    513     if self._raise_it:
--> 514         raise e
    515     else:
    516         if return_df:

File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/xcube_geodb/core/geodb.py:880, in GeoDBClient.unpublish_collection(self, collection, database)
    877 database = database or self.database
    879 try:
--> 880     return self.revoke_access_from_collection(collection=collection, usr='public', database=database)
    881 except GeoDBError as e:
    882     return self._maybe_raise(e)

File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/xcube_geodb/core/geodb.py:903, in GeoDBClient.revoke_access_from_collection(self, collection, usr, database, **kwargs)
    901     return Message(f"Access revoked from {self.whoami} on {collection}")
    902 except GeoDBError as e:
--> 903     return self._maybe_raise(e)

File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/xcube_geodb/core/geodb.py:514, in GeoDBClient._maybe_raise(self, e, return_df)
    512 def _maybe_raise(self, e, return_df=False):
    513     if self._raise_it:
--> 514         raise e
    515     else:
    516         if return_df:

File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/xcube_geodb/core/geodb.py:900, in GeoDBClient.revoke_access_from_collection(self, collection, usr, database, **kwargs)
    897 dn = f"{database}_{collection}"
    899 try:
--> 900     self._post(path='/rpc/geodb_revoke_access_from_collection', payload={'collection': dn, 'usr': usr})
    901     return Message(f"Access revoked from {self.whoami} on {collection}")
    902 except GeoDBError as e:

File /opt/conda/envs/eurodatacube-2022.02/lib/python3.8/site-packages/xcube_geodb/core/geodb.py:392, in GeoDBClient._post(self, path, payload, params, headers, raise_for_status)
    390         r.raise_for_status()
    391 except requests.exceptions.HTTPError:
--> 392     raise GeoDBError(r.text)
    394 return r

GeoDBError: {"hint":null,"details":null,"code":"42P01","message":"relation \"eodash_e1a\" does not exist"}

**Comment by AliceBalfanz** [comment]
Hi Alessandro, thank you for reporting! My collegue @thomasstorm will have a look.

**Comment by AlessandroScremin** [comment]
@thomasstorm 

not sure it is a case sensitive, I received this error. Whatever I add in table name receive as prefix the database name)

GeoDBError: {"hint":null,"details":null,"code":"42P01","message":"relation \"**eodash_eodash**_e1a\" does not exist"}

> Dear Alessandro,
> 
> could you please try again with the command `geodb.unpublish_collection('eodash_E1A', database=database_name)` ? I suspect a case sensitivity issue; we would need to handle that better at the geoDB side.
> 
> If this does not work, I could unpublish the collection manually, if you want me to.
> 
> Thanks!

**Comment by thomasstorm** [comment]
@AlessandroScremin 

Ah, sorry, the command should be:
`geodb.unpublish_collection('E1A', database=database_name)`

Could you please try again and let me know?
Also, please let me know if I shall unpublish the collection manually. Thanks!

**Comment by AlessandroScremin** [comment]
@thomasstorm 
Not working...
command: geodb.unpublish_collection('E1A', database="eodash")
error: GeoDBError: {"hint":null,"details":null,"code":"42P01","message":"relation \"eodash_e1a\" does not exist"}

**Comment by thomasstorm** [comment]
@AlessandroScremin 

Ok, thank you.

Shall unpublish the collection manually, so that it does not appear publicly?

**Comment by AlessandroScremin** [comment]
@thomasstorm 
yes Please, unpublish from database=eodash.  The tables to unpublish are:
E1a
E13d2
E2
E8_tri

**Comment by thomasstorm** [comment]
@AlessandroScremin done - please have a look, and let me know if anything's not as expected.

I will look into the issue as soon as possible.

**Comment by AliceBalfanz** [comment]
This issue has been addressed in the newest xcube geodb version and is available in the newest base image on eox-hub. 
It can be closed.
