### ISSUE TITLE
Hide Sentinel Hub instance IDs

### ISSUE THREAD

**Issue by gmilcinski** [eurodatacube/eodash#142]
It seems that Sentinel Hub instance IDs are openly accessible in git:  
https://github.com/eurodatacube/eodash/blob/9002c320b44d92313196ad27c67d6c7ca847bc1a/app/src/config/esa.js#L133-L193

Instance IDs should be treated same as usernames and passwords and should not be openly revealed.

**Comment by gmilcinski** [comment]
I have created a new instance, a copy of the existing one (0635c213-MASKED). I will send id by e-mail.  
The old one (a60a37cc-MASKED) should no longer be changed (cc @AlessandroScremin @fbarchetta )

**Comment by gmilcinski** [comment]
@Schpidi let me know, once it will be safe to remove the old instance.

**Comment by Schpidi** [comment]
thanks, I'm planning to switch to the new one later in the evening and test a bit. will let you know when done.

**Comment by Schpidi** [comment]
the deployments have been switched to the new instance id. I propose to leave the old one active for another day or at least an hour to not disrupt active sessions.

**Comment by gmilcinski** [comment]
I moved the old configuration to another account where it can no longer be abused.
