### ISSUE TITLE
Integration of additional data from NASA or JAXA sources

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1459]
Possible datasets, list will be updated to specify which ones to include

JAXA:

- [x] - ODIAC (Cairo)
- [x] - NDVI Anomaly
- [x] - FNF-PALSAR2-Equatorial-[2017,2018,2019,2020]-Yearly (WMTS-custom tilematrix)

https://ogcpreview2.restecmap.com/example/WMTS/wmtsFNF.html

NASA (looking at their endpoint):

- [ ] - HLSS30.002
- [ ] - HLSL30.002
- [x] - grdi-shdi-raster
- [x] - grdi-vnl-slope-raster
- [x] - grdi-vnl-raster
- [x] - grdi-v1-raster
- [x] - grdi-v1-built
- [x] - grdi-cdr-raster
- [x] - grdi-imr-raster
- [x] - blue-tarp-detection
- [x] - grdi-filled-missing-values-count
- [x] - geoglam
- [ ] - Any of the Social Vulnerability Index? or similar collections? There is an "overall" version of it

Possible NASA datasets related to biomass coming in the future:
https://earthdata.nasa.gov/maap-biomass/

- [ ] -  CCI Biomass
- [ ] -  GEDI Gridded Biomass - still marked as not yet available, source unknown
- [ ] -  ICESat-2 Boreal 2020
- [ ] -  NASA JPL 2020

**Comment by lubojr** [comment]
FNF-PALSAR2 WMS test for 2017 in https://github.com/eurodatacube/eodash/tree/test-palsar-fnf-wms
