### ISSUE TITLE
Mobile website - issues

### ISSUE THREAD

**Issue by spectrachrome** [eurodatacube/eodash#1563]
### **Indicator description does not scroll properly, so not all text is readable**

When opening a specific point of interest, it is not possible to scroll the description text in the bottom of the modal.

- [x] Fixed in [`5bb1094c`](https://github.com/eurodatacube/eodash/commit/5bb1094cc622073b971c569cd8a4a776ee9b19fc)

_(iOS and Android)_

---

### **Time selection not accessible in portrait mode**

While the dropdown that allows selecting times works well in landscape mode, it is covered entirely by the partially retractable indicator description.

- [ ] Open

_(iOS 15.5)_

---

### **Map controls are not aligned to the right when partially retracted and a POI is selected**

When the panel at the bottom containing charts and description is partially retracted and there is a POI selection, the map controls "attach" themselves to the right of the input field instead of the screen. 

This changes to the way it should be as soon as the POI is deselected.

- [x] Fixed in [`e32a435`](https://github.com/eurodatacube/eodash/commit/e32a435b204474f77d772a01616ec588f1b039da)

_(iOS 15.5)_

**Comment by santilland** [comment]
Closing issue, opening new one for not closed subitem https://github.com/eurodatacube/eodash/issues/1972
