### ISSUE TITLE
Load NUTS region for Austria as selection method

### ISSUE THREAD

**Issue by slumnitz** [eurodatacube/eodash#1581]
How big is the data, how can it best be loaded?

**Comment by slumnitz** [comment]
## Data resources:
* European level: https://ec.europa.eu/eurostat/web/nuts/local-administrative-units

**Comment by santilland** [comment]
We will need even higher level after L3 NUTS, data can be found here:
https://ec.europa.eu/eurostat/de/web/gisco/geodata/reference-data/administrative-units-statistical-units/lau

**Comment by santilland** [comment]
It is under discussion what the next level should be, data from previous comment might not be the one wanted, but actually:
https://www.statistik.at/atlas/?mapid=topo_regionale_gliederung_oesterreich
the data that can be seen under Zählsprengel in the drop down selection. Looking on how to download this...

**Comment by santilland** [comment]
Intermediate between NUTS and Zählsprängel is missing:

- NUTS3
- Bezirke: https://data.statistik.gv.at/data/OGDEXT_POLBEZ_1_STATISTIK_AUSTRIA_20220101.zip 
- Gemeinden: https://data.statistik.gv.at/data/OGDEXT_GEM_1_STATISTIK_AUSTRIA_20220101.zip
- Zählsprängel https://data.statistik.gv.at/data/OGDEXT_ZSP_1_STATISTIK_AUSTRIA_20220101.zip (smallest area)

**Comment by ubi15** [comment]
Hi Daniel, Enrico (MindEarth) here.
I just noticed that the Polbez level (the Bezirke one) has a double shape over Vienna: 
- one for the whole city with `id=900`
- one for each Gemeinden within the city (same geometries as the GEM layer) and compatible ids, e.g., 915 for the Gemeinde 91501 .

Shall we ignore the whole city or the Gemeinde geometries?
To keep a solid index correspondence, I would prefer to discard the POL 900 as it has no code mapping to the GEM and ZSP layers.

**Comment by santilland** [comment]
Hello Enrico, good catch, weird thing to have overlapping geometries like that. It seems like discarding the whole city one (id 900) makes the most sense, as the correspondence with the ZSP levels works much better with the Gemeinde ids.
