### ISSUE TITLE
Demonstration "Sustainable Urban Roofscapes"

### ISSUE THREAD

**Issue by slumnitz** [eurodatacube/eodash#1588]
## Science Products

* Area solar radiation: raster data, 1m spatial resolution
* Photovoltaik (PV) installation - Building outlines: vector data, including the following information as attributes
    * PV installed: yes/no
    * PV size in m²
    * PV potential in m²
    * Energy potential in kWh per year
* Greenroof (GR) installation - building outlines: vector data, including the following information as attributes
    * GR installed: yes/no
    * GR size in m²
    * GR suitability: yes/no
    * GR potential area in m²
* Land Surface temperature: raster data, 30m resolution

## Analysis

Visualisation: 
* color scheme depending on total area, total potential
* Aggregation at different administrative levels or per grid (e.g. hexagons, neighbourhoods, census data blocks)

Integrated Analyses
* AOI: user defined, either as selection from available vector data (e.g., admin-units, building outlines), shapefile upload (if possible) or drawing on map
* For selected AOI, the user can 
    * Get information of 
        * Number of buildings with PV installation and GR installation
        * Area of PV installation and GR installation
        * Number and area of non-transformable roofs
        * Show actual roofs on map with PV and/or GR installation
    * Perform analysis on
        * How much renewable energy can be created by installing PV systems on XX% of houses? → slider for selection of percentage
        * How would LST change in an area if XX% of houses would be transformed into GRs? → slider for selection of percentage
		→ Comparison between different areas of interest important

**Comment by santilland** [comment]
In process, conversion of products and analysis sections into defined tasks.

**Comment by santilland** [comment]
Conversion to separate tasks done.
