### ISSUE TITLE
Renewable Energy Production - Data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1597]
All datasets to be used in the tradeoff explorer need to have the same footprint (origin and extent) in order to be loaded as multiband/multisource COG.

Following datasets need to be available to cover the scenario (it might be necessary to track datasets as individual tickets, to be referenced here:

High priority (data will be provided by end of September):
- [x] Solar power potential (kWh/m2) on terrain surface
- [x] Wind energy potential (GWh)
- [x] Slope see #1610 
- [x] Aspect see #1610 
- [x] Distance to urban areas: will be provided 30/09 by DHI using EDC specs
- [x] Distance to electrical grid: will be provided 30/09 by DHI using EDC specs
- [x] Protected areas: will be provided 30/09 by DHI using EDC specs
- [ ] ...?

After October release?:
- [ ] mapping locations of solar PV farms
- [ ] Detected bounding boxes for turbine locations
- [ ] Hydro reservoir dams min, max and current energy storage (dynamic).
- [ ] Micro hydropower, annual power production potential (KW/year)

**Comment by santilland** [comment]
List of outputs to be provided by patrick and replace current list

**Comment by patrick-griffiths** [comment]
![Image](https://user-images.githubusercontent.com/40148967/192501042-d401d389-1235-4ad2-a722-259b4cdf2d7f.png)

**Comment by patrick-griffiths** [comment]
![Image](https://user-images.githubusercontent.com/40148967/192501955-e920b558-2203-4c06-b943-f1513eb7b6c3.png)

**Comment by santilland** [comment]
Data has been integrated and is available in the client. Individual issues have been created for additionaly expected dataset.
https://github.com/eurodatacube/eodash/issues/2082
https://github.com/eurodatacube/eodash/issues/2083
https://github.com/eurodatacube/eodash/issues/2084
https://github.com/eurodatacube/eodash/issues/2085
