### ISSUE TITLE
Tradeoff explorer - scatter plot of data selected on map

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1598]
A scatterplot is shown for the different parameters extracted from the relevant datasets as listed in #1597 .
It needs to be considered how and when the scatterplot is shown, for example one possibility could be after selecting an area (e.g. NUTS region #1581), if this is the case also filtering to selected area should be examined (e.g. with turf.js)

![image](https://user-images.githubusercontent.com/4036819/192329938-2232ba24-cbc6-4d9d-9356-0c9b43da36cc.png)

> 

![Image](https://user-images.githubusercontent.com/40148967/188462374-8f2f0aef-7506-48fa-a1fd-a2f2854c55ed.png)

**Comment by slumnitz** [comment]
linked to #1605 and #1806

**Comment by santilland** [comment]
We have now some scatter plot charts for ZSP level, which also retrieve information of the ZSP from the same region. I think the idea of the issue has been implemented.
What we want to further explore is being able to analyze different administrative levels. This should be covered by following issue #2576 

Closing this issue
