### ISSUE TITLE
Tradeoff explorer - best zone selection: map visualization

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1599]
Showing data on map - one specific layer (for example energy potential data) and allow filtering by multiple sliders which apply filtering based on multiple parameters available from the described data sources in #1597 

for example:
range-sliders to stratify "Solar/Wind potential" layer e.g. to top 25% suitability
additional range-sliders that add further constraints to the stratification
---distance to settlements (pre-computed distance grid)
---terrain (slope, aspect, height)
---land properties (protected, private, public)

![Image](https://user-images.githubusercontent.com/4036819/192332343-dc57ce84-b677-4a22-ab94-f19085b181b6.png)

![Image](https://user-images.githubusercontent.com/4036819/192330314-4af2e2c6-754a-4512-beff-07a0b99ccc9e.png)

**Comment by patrick-griffiths** [comment]
the updated mock up with the actual trade-off explorer (above is just the best zone selection): 

![Image](https://user-images.githubusercontent.com/40148967/194583409-53c804b2-f5df-479c-ad00-318512326b67.png)
