### ISSUE TITLE
Sustainable Urban Roofscapes - Data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1601]
Loading of folowing datasets into EDC/SH/GeoDB:

- [ ] Area solar radiation: raster data, 1m spatial resolution
- [ ] Photovoltaik (PV) installation - Building outlines: vector data, including the following information as attributes
       * PV installed: yes/no
       * PV size in m²
       * PV potential in m²
       * Energy potential in kWh per year
- [ ] Greenroof (GR) installation - building outlines: vector data, including the following information as attributes
       * GR installed: yes/no
       * GR size in m²
       * GR suitability: yes/no
       * GR potential area in m²
- [ ] Land Surface temperature: raster data, 30m resolution

**Comment by AlonsoItziar** [comment]
More detailed description of the output: 
- We will provide a shapefile for each of the 4 case study cities with all the data for the potential and actual PV and Green roof mapping, as was already discussed with Stefanie on Tuesday.

- We will also provide statistics that we compute based on Census Units
