### ISSUE TITLE
Air quality & mobility national scale - Data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1608]
Input data to be defined

**Comment by AlonsoItziar** [comment]
Dummy dataset provided, mobility data budget provided, data access by 29/09

**Comment by patrick-griffiths** [comment]
Hi @santilland, please see this message from SISTEMA from today. 
So final data delivery to be expected for Friday, but with the dummy data we should be able to prepare this to a good extent. 


Dear Patrick,
I would like to highlight that:
•we have already provided samples to EOX to implement the first use case. If they can visualize these products, replacing with the real products it will be easy
•we have received mobility data late last week, so I was basically impossible to generate any usable data layer so far. I will put a deadline for a first release of the mobility data by the upcoming Friday (Oct. 7).
•Satellite data and model data are already available for the identified period (July to September 2021). We can already provide them to EOX
•spatial aggregation over the admin boundaries might require some time and I think we should agree on:
o	data format
o	aggregation modality (e.g. average value over the AOI for each time? Other information ? (min, max, standard deviation)?
o	how were these issues managed for the other use cases ?
Stating this, I have to check with MindEarth whether we can present both visualization ways (satellite and model data are feasible).
About correlations, I can already say that we will not be able to present any correlation indicator at the demo, unless there are already in-platform tools to compare / correlate data available on the same grid that can be used.
I keep you updated.
KR,
Stefano
