### ISSUE TITLE
eo data for E10a

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#161]
E10a1 uses whole days which give reasonable results but sometimes the sub-aoi is not covered at all like for the latest day 2020-05-31:
![Screenshot from 2020-06-04 16-20-52](https://user-images.githubusercontent.com/482265/83768689-6132d480-a67f-11ea-888e-3f60162344d7.png)

E10a2 uses a complete datetime which doesn't result in any S2 data shown:
![Screenshot from 2020-06-04 16-21-34](https://user-images.githubusercontent.com/482265/83768754-790a5880-a67f-11ea-8340-ff4adb8f5d98.png)

what would be the right time to query for? @aapopescu can we ask the scientists what to use?

@aapopescu to aks Benjamin for vector data for the parcels used in the study

**Comment by Schpidi** [comment]
related to https://github.com/eurodatacube/eodash-data/issues/47

**Comment by aapopescu** [comment]
Added GLC layer
