### ISSUE TITLE
DEM Slope and Aspect - sinergise

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1610]
Creation of slope and aspect layers for Austria based on the Copernicus 10m DEM, this will be key datasets to support the interactive exploration of this scenario (best zone selection and tradeoff explorer)

@gmilcinski  could you help in generation of this data and provide it to @AlessandroScremin with following format?

According to the specification below as separate pre-computed COG files (EPSG 4326).

**Comment by patrick-griffiths** [comment]
![Image](https://user-images.githubusercontent.com/40148967/192502315-ab43d429-ad87-4e50-b19f-67a8905abfb8.png)

**Comment by patrick-griffiths** [comment]
DHI confirmed that these layers should be produced by Sinergise/PLES teams.. 
Details on exact bounding box to be defined by DHI - see below



![Image](https://user-images.githubusercontent.com/40148967/192549333-2ab31990-39e0-4988-a7c7-b0e0d29756c3.png)

**Comment by gmilcinski** [comment]
Just to confirm we understand the task well.  What we are responsible for is generating aspect and slope, the rest (i.e. solar power, wind power, etc.) will be done by PLES, is this correct?  
Does PLES need these inputs for their work or is it stand-alone? (just to understand the timelines)

**Comment by AlessandroScremin** [comment]
@gmilcinski 
PLES is involved in coordinating and supporting the GTIF tasks and activities and run some tasks for the project in the future. In this case the GTIF Partners need Slope and Aspect into EDC to perform the tasks mentioned above. So they are needed for the Demo. I asked support also via Mail thorugh the support mail provided by you, with all the specifications,

Thnaks again for your prompt support

Kr
Alessandro
