### ISSUE TITLE
Finishing touches for rebranding/UI update

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#1617]
- [x] clear / reset button in search box does sometimes not appear
- [x] moving/interacting with the map resets search box content
- [x] global layer selection should not automatically move the map
- [x] add search query to url
- [x] check display of TROPOMI POIs
- [x] reduce date selector width to fit between searchbox and legend
- [x] expand date selector menu to bottom instead of top
- [x] check date selector positioning in custom dashboard and in iframe
- [x] view padding fitting: fix the automated fitting of pan&zoom to consider side panel and bottom layer carousel
- [x] area selection highlighting/map blocking: when getting an error from the statistical api, the map is sometimes blocked / greyed out
- [x] map query keeps being added to url even after navigation to different pages (sould be removed when navigating away from explore page)
- [x] connect trilateral themes to new theme filtering functionality
- [x] create global layer quicklooks for RACE & trilateral
- [x] check iframe layout of previously tabbed items
- [x] include scroll blocking for items in custom dashboards (and optionally iframes)
- [x] mobile layout improvement: fix search box colliding with map controls
- [x] mobile layout improvement: date selector positioning
- [x] mobile layout improvement: decide what to do when mobile keyboard comes up - currently squishes interface
- [x] update favicon, key visual, header logo (EC emblem + ESA, remove copernicus)
- [x] fix global layer carousel layout on Firefox (currently sticking to the top)
- [x] welcome-popup (automatic) should contain just the news/info carousel, rest goes to about page
- [x] embed button for maps
- [ ] sometimes custom dashboard button replicates
- [x] generate chart card sometimes has text shifted by one height
- [x] tutorials, how to use dashboard get rid on RACE, rename -> datasets
- [x] chart height on mobile
- [x] add to dashboard and embed button -> only on global pois!
- [x] search text query/input reset after page reload
- [x] make carousel icons more visible
- [x] date selector menu open to top or bottom depending on positioning
- [x] popup header short name for welcome
- [x] generate chart button for trucks
- [x] mobile view: dropdown always opens on POI selection
- [ ] embed/addtodashbaord button sometimes overlap the right global carousel button
- [x] NavigationDuplicated console error
- [x] map fitting sometimes interrupted
- [x] close button on mobile does not clear search text
- [x] wrong indicator names, e.g. Barcelona  TSM and CHL-a
- [x] wrong theme icons, e.g. barcelona Cholrophyll-a concnetration regional map
- [x] z-index of legend is over fullscreen panel
- [x] don't allow side panels to go fullscreen when global indicator data
- [x] check A/B slider positioning when side panel is open
- [ ] disallow zooming out with eo data
- [x] dark mode global layer card highlighting
- [x] clearing of POI after direct link entry

**Comment by aapopescu** [comment]
- [ ] When in filtered view (e.g. country + theme), click on a second POI removes the filters
- [ ] Shaded area outside of AOI is inverted (shade is on AOI instead of outside)

**Comment by santilland** [comment]
Will close this issue, if UI issues become apparent i propose to handle them through new issue.
