### ISSUE TITLE
eo data zoom if no sub-aoi is present

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#162]
in order to mitigate an issue with pleiades data the dashboard now zooms to level 18 if there is no sub-aoi present. this includes a lot of S1 related POIs, e.g., E8. shall we leave it like this or find a more clever strategy @aapopescu ?

**Comment by aapopescu** [comment]
Zoom to be adapted to resolution/sensor when no sub-AOI is present If data with different resolutions are alternating then use the zoom from latest data.

**Comment by lubojr** [comment]
Closing for now. Put on Hold
