### ISSUE TITLE
Carbon Accounting Demo

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1624]
For the GTIF demonstration on 17 Oct. Joanneum Research and VTT will provide:

1. for EO Adaptation Services a showcase on forest disturbance: windfall in Austria over Styria due to storm on 18 August with a before and after scenario (slider) and close ups (the always agreed case). We will also show an example of bark beetle infection probability (as agreed last Tuesday) for later roll out in Austria 

2. for Carbon: a indication of forest carbon monitoring based on biomass estimation and areal changes over Austria (as requested on Tuesday), but neither including dedicated biomass mapping for Austria nor the growth models (available in spring 2023) - illustrative example for Peru in the slides.

So #1 will be under the "carbon accounting" domain while #2 will fall under the "EO Adaptation Services" domain..

![Image](https://user-images.githubusercontent.com/40148967/193333549-33b85fbb-345d-4463-b3af-3c95656ce91c.png)

**Comment by santilland** [comment]
Multiple datasets have already been integrated, future possible datasets to be tracked in separate issues:
https://github.com/eurodatacube/eodash/issues/2070
https://github.com/eurodatacube/eodash/issues/2071
https://github.com/eurodatacube/eodash/issues/2072
https://github.com/eurodatacube/eodash/issues/2073
https://github.com/eurodatacube/eodash/issues/2074
