### ISSUE TITLE
subaoi in map updated only when item is selected from that map

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#163]
for example brandenburg poi -> global no2 does not remove subaoi from map (because subaoi is not reactive)

**Comment by lubojr** [comment]
done in https://github.com/eurodatacube/eodash/commit/d469a8427af9bdd4e8152946b7fe69adef246203

**Comment by aapopescu** [comment]
When POI on Brandenburg is selected, if Air Quality is next selected it removes the AOI from map.

This behaviour should be the same when selecting any other Indicator.

**Comment by lubojr** [comment]
I dont think I follow. The error here was that on changing selected POI (or global indicator), the subaoi on left map did not change (just its color). That should be fixed on staging.
