### ISSUE TITLE
NO2 data from stac api does not contain latest data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1635]
https://staging-stac.delta-backend.com/collections/no2-monthly/items?limit=5000
latest returned date is:
"start_datetime":"2022-05-01
and should be newer

**Comment by santilland** [comment]
See status here:
https://github.com/NASA-IMPACT/veda-data-pipelines/issues/201

**Comment by lubojr** [comment]
Is fixed in eodash-catalog by directly fetching api
