### ISSUE TITLE
Some legacy map baselayers should be removed : S2GLC - Europe Landcover 2017

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1730]

**Comment by lubojr** [comment]
removed in [f5b791ce](https://github.com/eurodatacube/eodash/commit/f5b791cecb483d1927622764ae409c3fcc3ffa35) from eodash config

**Comment by lubojr** [comment]
From the data location perspective, leaving up to discuss for @aapopescu and @AlessandroScremin if data should be also deleted from our buckets?
