### ISSUE TITLE
Allow selection of time of "map" / EO Data by clicking on a point in the chart.

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1735]
Maybe show a line for currently shown date on map.

**Comment by santilland** [comment]
Important for water story data - data integration in process, but concept could be applied to all indicators - important for UX discussion.
Implementation approach needs to be decided - conceptual design created by silvester to be provided

**Comment by silvester-pari** [comment]
Initial concept was to "highlight" data on a line chart - but I haven't checked feasibility with chart.js yet.

![image](https://user-images.githubusercontent.com/26576876/211854215-fcbb7009-6ace-4081-b86f-7aa3d69401e5.png)

**Comment by lubojr** [comment]
The feature has been implemented in #2293 Awaiting feedback before merge.
