### ISSUE TITLE
NO2 flux footprint (Air quality data)

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1736]
In order for that we can all coordinate on how to integrate this data i will try to bring together the information i have. 
This issue is to describe the process of integrating the NO2 flux footprint data:

### Data source:

- data located on a fileshare platfrom from the university of innsbruck
- filenames  "gtif_uibk_<<date>>.nc"
- filesize ~500MB
- daily files containing 30min stepped data
- as far as understood data science team waiting of confirmation of data download to remove current data from fileshare platform and add new batch of data

### Data conversion:
Data to be extracted as described in document (High spatial resolution air quality scenario):
- float64 iao_lat(LAT [°]), float64 iao_lon(LON [°]) → coordinates of the eddy tower
- ffp_x_2d and ffp_y_2d → are the x- and y grid of the 2-D footprint in meter
- nox_cld_flux(Flux [nmol mmol-1 ms-1]) → values of the flux footprint, correct units are [nmol m-2 s-1]
- ffp_baselayer → landuse map

- [ ] Please clarify how x- and y grid is needed or should be used

As far as is understood no other data shall be extracted from the files, such as wind direction, wind speed, mean temperature, no2 concentration, pandora no2, ....

Data to be converted to COG:
- 1 file (COG) for each 30 min and nox_cld_flux( 48 files per day )
- 1 file (COG) for each 30 min and ffp_baselayer ( 48 files per day)
- projection EPSG:3857

### Expected visualization:
![image](https://user-images.githubusercontent.com/4036819/201081034-ac2f3a62-cc2c-4d3f-9fb7-d1e8982a9f84.png)

Related ticket for visualization of product on client: #1737

**Comment by DanGasb** [comment]
Hi Daniel, this is Daniele.
First, the variable that contains the footprint values is "ffp_values" and not "nox_cld_flux" which is related to NOx fluxes.
ffp_x_2d and ffp_y_2d are the coordinates of the footprint values. This means that you need these coordinates for creating a countour plot:
 contourf = ax.contour(ffp_x_2d, ffp_y_2d, ffp_values[i], alpha=0.7, cmap='Reds') 
Regarding the data ingestion maybe we will ingest also Pandora NO2 values but it also depends on what SISETMA will provide.
Daniele

**Comment by DanGasb** [comment]
Ciao Daniel,
yes with data ingestion I mean the data to extract from the Innsbruck files.
Regarding the pandora data no2_pand_du and no2_pand_ppbv are the same variables with different units, let's take onboard both.
For footprint fluxes visualization you mentioned the correct variables to use.
As soon as PLES team is able to download all the Innsbruck files we can have a meeting in order to precisely define what to do.

**Comment by AlonsoItziar** [comment]
A test file for the conversion from netcdf to cog has been loaded to the bucket under /s3/GTIF/new_data/test_nc_COG

**Comment by santilland** [comment]
It seems there is an issue with the projection of the file, feedback sent per email.

**Comment by santilland** [comment]
Last generated file looks as expected, as proposed by Itziar let us start witha stepwise approach

- [ ] Generate a day of data 48 files
- [ ] If day ok, move to month
- [ ] If month ok move to year

**Comment by AlonsoItziar** [comment]
A day of data has been generated and loaded in the bucket, under: /s3/GTIF/new_data/test_nc_COG/day/

**Comment by DanGasb** [comment]
Ciao Daniel,
regarding the other data to show that we have discussed last week (i.e. the time series related to a single point of observation) 
I can produce yearly csv file like the ones attached.
Let me know if it is fine for you.
Daniele

[IBK_2020.csv](https://github.com/eurodatacube/eodash/files/10152403/IBK_2020.csv)

**Comment by santilland** [comment]
> A day of data has been generated and loaded in the bucket, under: /s3/GTIF/new_data/test_nc_COG/day/

Thank you also Itziar, we will try to integrate the datasets as soon as possible into the dashboard and report our results

**Comment by santilland** [comment]
Hello @AlonsoItziar loading of the data looks good, we can now also switch between times and show the dynamic contours on the client, see image below.

There seem to be multiple files that have no values at all, for example:

- gtif_uibk_20201101_ffp_values_b24.tif
- gtif_uibk_20201101_ffp_values_b23.tif
- gtif_uibk_20201101_ffp_values_b9.tif

For these datasets all pixels are equal to 0, could you check the original data and make sure this is expected behavior?
If it is expected behavior i would propose to not create a COG if all values are 0, as on the client it just seems like nothing is loading.

As for the filenames instead of the band number at the end, could we use the time in ISO 8601 in addition to the date?

So filename would be:

`<YYYY-MM-DDThh:mm:ssZ>_gtif_uibk_ffp_values.tif`
so for example:

`20220820T05:30:00Z_gtif_uibk_ffp_values.tif`

The position of where the datetime substring is located in the name is not so important as long as it is constant.

![Image](https://user-images.githubusercontent.com/4036819/207362966-61f7cf5d-61f1-4005-81c1-4656141ace96.png)

**Comment by santilland** [comment]
Completely empty times are expected and should be kept - (will probably need to implement better user notification)

If possible when generating COGs negative values should be masked to NaN
