### ISSUE TITLE
Mobility data national scale (phone data)

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1738]
Data is generated on Zählsprengel level and can be provided as geojson.
This results in a very large geojson in reality only because of the complexity of the geometry. We need to better identify a data provision approach.

**Comment by sistemagmbh** [comment]
GeoPackage might be a better format for such big file. Also a simplify could be applied to reduce some complexity.

**Comment by sistemagmbh** [comment]
So, just to clarify, you want us to send only csv files or format alike with the aforementioned columns?

**Comment by santilland** [comment]
We have not yet made a final decision, but that is an option being considered, might also be a json or other format.
That would greatly reduce the amount of data needed to be passed and stored.
For example previously the geojson containing the Zählsprengel geometry and measurement data was about ~1Gb, but the actual information is probably just some Mb of that.
Would this also be an option for you to generate the data like that?
Maybe we could do a file per timestamp? So in this case daily file (could be csv) with Zählsprangelid and then the available parameters generated on your side.

**Comment by sistemagmbh** [comment]
It should not be a problem for us. It's just dropping the geometry column of the GeoDataframe before storing.

**Comment by santilland** [comment]
Example files provided in hourly resolution (packed in daily files)

**Comment by santilland** [comment]
Data integrated and displayed on client, for further features we can create new dedicated issues, closing this ticket for review.
