### ISSUE TITLE
Define expected behavior for explore tools and use cases

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1740]
In order to be able to define development tasks first the expected behavior of the explore tool needs to be defined.
Current understanding is, selecting an admin unit shall show information on that area based on the selected dataset.
As each dataset is different the expected behavior for each dataset needs to be defined.
For defined use cases a separate item will be created (separating use case by domain):

**Energy transition**
See also #1753 as possible approach to cover explore tool results
- [ ] Wind energy -> statistic summary of admin unit -> 
    - [ ] histogram on remaining wind power density (TODO create issue)
    - [ ] pie chart showing land cover types (TODO create issue)
    - [ ] box plots on elevation and slope/aspect (TODO create issue)
- [ ] Solar energy -> ?
- [ ] Nowcasting?
- [ ] (Micro)Hydro power? 

**Mobility transition**
See also #1754 as possible approach to cover explore tool results

- [ ] Air quality -> Correlation analysis?
- [ ] High resolution data?
- [ ] NO2 flux?
- [ ] Mobility data?
- [ ] Social mobility?

**Sustainable cities**

- [ ] Solar/Green roofs and Urban trees

**Carbon accounting**

- [ ] Biomass
- [ ] CCI Biomass

**EO adaptation services**

- [ ] Heat explorer

**Comment by patrick-griffiths** [comment]
@santilland 
For Wind Energy / Solar energy the most basic statistic would be 
1. the area [km2] of remaining windrower density (WPD) after the constraints have been applied. 
2. a histogram for those remaining areas of the WPD/Solar incidence values, the DEM Elevation/Slope
That would be a great first step

**Comment by santilland** [comment]
This issue is fairly generic and used mostly for initially finding implementation approaches. I will close it now. If we want to discuss further any of the specific points let's open a new dedicated issue
