### ISSUE TITLE
Define list of parameters which can be used as filters

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1742]
In order to allow implementation of adding/removal of constraining variables expected variables need to be defined:

**Wind energy**

- elevation - slider (shown as default)
- slope - slider
- distance to settlements
- distance to energy grid
- protected areas - checkbox (shown as default) - should this be removable?

** Solar energy**

- aspect  - slider (shown as default)
- slope - slider 
- distance to energy grid - slider 
- elevation - slider 
- protected areas - checkbox (shown as default)

**Nowcasting?**
**Hydropower?**
**Micro Hydropower?**

Other thoughts

- [ ] Should selected filters be saved?
- [ ] Filters should be removable? If yes, what about default ones?
- [ ] ...

**Comment by patrick-griffiths** [comment]
optional constraining variables to be grouped in categories e.g.: 
- environmental variables
- policy aspects (distance to settlements, ) 

Kenneth to provide list of siting variables from DTU

**Comment by santilland** [comment]
How and where should grouping be shown?
One option i can think of is when clicking on "Add filter" the list could be "grouped" in categories, so having like headers between items.
I don't know how we could show this categories as part of the range filters already being displayed.

If grouping is wanted, then grouping for all possible datasets needs to be declared.

**Comment by santilland** [comment]
Datasets have been ingested and filters are available for the energy transition datasets, any further changes should be tracked in separate tickets, considering this as closed
