### ISSUE TITLE
Load ARI data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1743]
Data format and source needs to be defined. More information to be provided by Daniele and Christian.

The ARI data shall replace "NO2 data", does this mean that from within "Air Quality Maps" the "Nitrogen Dioxide" option should no longer be shown? Or should the complete content of Air Quality Maps be replaced with the ARI data?

**Comment by AlonsoItziar** [comment]
The ARI data will replace the NO2 data that were provided by the AlpAirEO website, the NO2 air quality map will still be shown, but data will come from a different provider (Sistema)

**Comment by santilland** [comment]
have been uploaded to GTIF/new_data

**Comment by santilland** [comment]
The generated JSON files need to include:

- ARI - Min increased health risk
- ARI - Max increased health risk
- ARI - Mean increased health risk
- PM2.5
- PM10

**Comment by santilland** [comment]
We created an issue trying to summarize what we think are important aspects of what we need to take into account for data exchange #1843 , please take a look at the information there and if there are any questions or suggestions for change we can discuss there.
I think for this concrete example we have also the original information in json format which we might be able to use without a conversion step? Could you provide one example json file in the original format?

**Comment by DanGasb** [comment]
Hi Daniel, the granularity for Austria is Gemeinde, since Bezirke is larger.
If you dive into AlpAirEO maps you can recognize that each polygon corresponds to the name of  city.

**Comment by santilland** [comment]
Hello, great, thanks! So can we assume that the ids are then equivalent to the statistic austria Gemeinde 2022 dataset?:
https://data.statistik.gv.at/data/OGDEXT_GEM_1_STATISTIK_AUSTRIA_20220101.zip

**Comment by santilland** [comment]
So as far as i can see, the json is structured per measurement type, then per country and each country has then a sequential ID  identifier number AT having 1 to 1932. Is there somewhere a mapping for these numbers to actual Gemeinde identifiers?

**Comment by DanGasb** [comment]
Ciao Daniel, unfortunately there is no correspondence and no linear relation between the IDs of the AlpAirEO geojson file and https://data.statistik.gv.at/data/OGDEXT_GEM_1_STATISTIK_AUSTRIA_20220101.zip.

**Comment by santilland** [comment]
That is quite unfortunate, but the geometries or at least the names of the "Gemeinden" should be the same as defined in the  statistik austria file, right?
Maybe we can create a mapping based on the names.

**Comment by DanGasb** [comment]
Yes, the name should be the same between the different sources and maybe is better to create a mapping based on the names while geometries might change over time.....in Italy it happens often

**Comment by DanGasb** [comment]
I found this statement in a document of the project that provide ARI data:
"Using Eurostat shape files for NUTS 3 level covering Alpine regions of bordering countries Germany, Austria, Slowenia, Croatia, Italy, Swiss and France, processed data is aggregated and exported to json formatted files. "
I can ask them if you need more info

**Comment by santilland** [comment]
Thank you @DanGasb for the information, but as far as I can see the data is much more resolved then NUTS3. It matches for the most part the Gemeinde "resolution" at least in Austria.
It would be great if you could ask for further clarification.

In the screenshot you can see NUTS3 geometries in red, and in yellow are the areas retrieved from the air quality file:


![Image](https://user-images.githubusercontent.com/4036819/207095806-e2996484-1b55-4272-8f4d-aa6338de4622.png)

**Comment by AlonsoItziar** [comment]
Hi Daniel, 

the new datasets that include ARI, PM2.5 and PM 10 are available at /s3/GTIF/new_data/geojson/IHR_P25_P10

**Comment by santilland** [comment]
Great, thank you @DanGasb we will use the data to try and see how we can load or show it on the GTIF dashboard.

**Comment by santilland** [comment]
The generated ARI data by rhea has been ingested into geodb and is accessible and queryable through the client, opening a new issue for the NO2 time series https://github.com/eurodatacube/eodash/issues/1936, and closing this one for review as the original task is considered finalized
