### ISSUE TITLE
Integrate "protected areas" dataset as filtering method in wind and solar energy

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1744]
Dataset should have been provided, reprojection and fitting might be needed, once done add to configuration.
Need for implementation of filter types:

- range filter (currently only one used)
- binary filter

**Comment by santilland** [comment]
As far as i can tell we dont have this dataset, @AlonsoItziar or @patrick-griffiths could you please confirm where the protected areas dataset should be?

**Comment by patrick-griffiths** [comment]
@danielfdsilva  @AlonsoItziar 
The two datasets that were delivered by DHI via FTP are the ones below: 
Natura2000_Austria_WGS84_COG.tif
CCDA2022_Austria_WGS84_COG.tif

Both are binary layers (0 and 1) and have not been clipped to the Austrian boarders yet. 
The dataset description is below

@AlonsoItziar is checking if they were ingested into the S3 bucket

Protected areas
Conservation areas such as Natura 2000 sites and Nationally designated areas are protected, and should be avoided when positioning wind turbines. Natura 2000 is the key instrument to protect biodiversity in the European Union. It is an ecological network of protected areas, set up to ensure the survival of Europe's most valuable species and habitats. Natura 2000 is based on the 1979 Birds Directive and the 1992 Habitats Directive. This version covers the reporting in 2021.
Source: https://www.eea.europa.eu/data-and-maps/data/natura-13
The European inventory of nationally designated protected areas holds information about designated areas and their designation types, which directly or indirectly create protected areas. Version 20 is used and covers data reported until May 2022. 
Source: https://www.eea.europa.eu/data-and-maps/data/nationally-designated-areas-national-cdda-17

**Comment by AlonsoItziar** [comment]
The datasets are in the bucket, under this folder: /s3/GTIF/ftp2.dk.dhigroup.com/DHIGRAS/Austria_GTIF

**Comment by santilland** [comment]
Great! Thank you for the info, missed them when looking
