### ISSUE TITLE
Energy Transition: OSM infrastructure layers activated by default

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1751]
the OSM energy infrastructure layers are really valuable, and should be activated for all Energy transition Explore tools by default.

**Comment by patrick-griffiths** [comment]
simple task? can we just enable this?

**Comment by patrick-griffiths** [comment]
@Schpidi - could we get this "small issue" resolved?

**Comment by Schpidi** [comment]
@lubojr didn't we configure something similar for ships like in https://github.com/eurodatacube/eodash/issues/654? do you remember how this could be configured?

**Comment by santilland** [comment]
There were some priorities on configuration and data visualization. I will merge the current approach for flux data visualization which also includes some newly configured base layers and configure the overlay layer.
I think it should be possible to only activate it when looking at the wind and solar energy, i will start with that option, but if @patrick-griffiths you prefer it we can set it to active as soon as the explore mode is opened.

**Comment by santilland** [comment]
Feature is deployed on demo instance
