### ISSUE TITLE
Write notebook/python script that generates statistical evaluation for Energy transition datasets

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1753]
In order to provide the greatest flexibility to the science teams in how they want to report their data and to allow to work on parallel to integrate new features the approach we have discussed is for the science teams to create jupyter notebooks (or python scripts) that take an administrative area as input and output a statistical analysis for that area.
The statistical evaluation outputs could be used for either information directly shown on the client or for concatenating information together into a report that can be downloaded by the user.

For the energy transition we would expect following inputs:

- Relevant datasets (Wind, solar, hydro, ...)
- Area to apply statistics to, i.e. ID for Zählsprengel, Gemeinde, Bezirk, NUTS region
- Possible applied filter ranges on the GTIF client

Possible outputs:

- histogram on remaining wind power density
- pie chart showing land cover types
- box plots on elevation and slope/aspect

Specific output should be discussed with science team

**Comment by patrick-griffiths** [comment]
@santilland could you share the URL for the EDC notebook here? 
Copy @AlonsoItziar and @AlessandroScremin

**Comment by santilland** [comment]
@patrick-griffiths you mean the example notebook i sent you for distribution to the science teams?

**Comment by patrick-griffiths** [comment]
@AlonsoItziar 
@AlessandroScremin 
two of the notebooks from EOX attached: 

[GTIF-data_access_and_widget_example-notebooks.zip](https://github.com/eurodatacube/eodash/files/10288031/GTIF-data_access_and_widget_example-notebooks.zip)

**Comment by santilland** [comment]
Example notebook provided by Sara (waiting for latest update), working on implementation of a service to call the functionality #2044

**Comment by santilland** [comment]
Latest Notebook update was provided, waiting for file dependencies used in notebook, images and shapefiles

**Comment by santilland** [comment]
Notebook update expected for this week, once received we can close this ticket and create a new one to convert notebook into processing service endpoint
