### ISSUE TITLE
Back to main page from Custom Dashboard doesn't load all data

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1756]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/?x=1280174.14412&amp;y=7332148.83319&amp;z=4.46184">https://race.esa.int/?x=1280174.14412&amp;y=7332148.83319&amp;z=4.46184</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 105</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Load one indicator. Add to custom dashboard. Click on &quot;Rapid Action for Citizens with EO&quot; on the page header. 
The homepage is loaded but not with all the data. </p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>All datasets should be visible when going back to the dashboard.</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca Anghelea</p>

**Comment by silvester-pari** [comment]
Thanks for reporting, I can reproduce this bug. It seems like clicking on the header logo does reset the filters, but not recalculate the displayed indicators.
