### ISSUE TITLE
Review available datsets from NASA API

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1767]
Extracted list of collections from stac api, need to organize which ones already included:

EPA-annual-emissions_6D_Composting - Gridded 2012 EPA Methane Emissions - Composting
nightlights-500m-daily - Black Marble 500m Nightlights Daily Dataset
IS2SITMOGR4-cog - ICESat-2 L4 Monthly Gridded Sea Ice Thickness (COGs)
social-vulnerability-index-household - Social Vulnerability Index (Household)
no2-monthly - NO₂
no2-monthly-diff - NO₂ (Diff)
mtbs-burn-severity - MTBS Burn Severity
ecco-surface-height-change - ECCO sea-surface height change from 1992 to 2017
lis-tws-trend - Trend in Terrestrial Water Storage (TWS) Anomalies
social-vulnerability-index-housing
grdi-imr-raster
bangladesh-landcover-2001-2020 - Annual land cover maps for 2001 and 2020
nceo_africa_2017
hls-l30-002-ej-reprocessed - HLSL30.002 Environmental Justice Events
EPA-annual-emissions_1B2b_Natural_Gas_Processing - Gridded 2012 EPA Methane Emissions - Natural Gas Processing
EPA-annual-emissions_6B_Wastewater_Treatment_Domestic - Gridded 2012 EPA Methane Emissions - Domestic Wastewater Treatment
modis-annual-lai-2003-2020 - Annual LAI maps for 2003 and 2021 (Bangladesh)
EPA-annual-emissions_5_Forest_Fire - Gridded 2012 EPA Methane Emissions - Forest Fires
EPA-annual-emissions_6B_Wastewater_Treatment_Industrial - Gridded 2012 EPA Methane Emissions - Industrial Wastewater Treatment
EPA-annual-emissions_1B2a_Petroleum - Gridded 2012 EPA Methane Emissions - Petroleum
EPA-annual-emissions_1B1a_Coal_Mining_Surface - Gridded 2012 EPA Methane Emissions - Surface Coal Mines
EPA-annual-emissions_1A_Combustion_Mobile - Gridded 2012 EPA Methane Emissions - Mobile Combustion
EPA-annual-emissions_4F_Field_Burning - Gridded 2012 EPA Methane Emissions - Field Burning
lis-tws-anomaly - Terrestrial Water Storage (TWS) Anomalies
EPA-annual-emissions_2B5_Petrochemical_Production - Gridded 2012 EPA Methane Emissions - Petrochemical Production
EPA-monthly-emissions_1B2b_Natural_Gas_Production - Gridded 2012 EPA Methane Emissions - Natural Gas Production (monthly)
co2-mean - CO₂ (Avg)
nightlights-hd-monthly - Black Marble High Definition Nightlights Monthly Dataset
grdi-vnl-raster
social-vulnerability-index-housing-nopop
social-vulnerability-index-household-nopop
social-vulnerability-index-socioeconomic
social-vulnerability-index-socioeconomic-nopop
grdi-filled-missing-values-count
OMI_trno2-COG
social-vulnerability-index-overall
social-vulnerability-index-minority-nopop
grdi-cdr-raster
MO_NPP_npp_vgpm
social-vulnerability-index-overall-nopop
grdi-v1-raster
grdi-shdi-raster
blue-tarp-planetscope
nightlights-hd-1band
social-vulnerability-index-minority
OMSO2PCA-COG - OMI/Aura Sulfur Dioxide (SO2) Total Column L3 1 day Best Pixel in 0.25 degree x 0.25 degree V3 as Cloud-Optimized GeoTIFFs (COGs)
EPA-annual-emissions_1B1a_Coal_Mining_Underground - Gridded 2012 EPA Methane Emissions - Underground Coal Mines
hls-s30-002-ej-reprocessed - HLSS30.002 Environmental Justice Events
grdi-v1-built
grdi-vnl-slope-raster
facebook_population_density
EPA-annual-emissions_1B1a_Abandoned_Coal - Gridded 2012 EPA Methane Emissions - Abandoned Coal Mines
EPA-annual-emissions_4B_Manure_Management - Gridded 2012 EPA Methane Emissions - Manure Management
EPA-annual-emissions_1A_Combustion_Stationary - Gridded 2012 EPA Methane Emissions - Stationary Combustion
EPA-annual-emissions_1B2b_Natural_Gas_Production - Gridded 2012 EPA Methane Emissions - Natural Gas Production
EPA-annual-emissions_6A_Landfills_Industrial - Gridded 2012 EPA Methane Emissions - Industrial Landfills
EPA-annual-emissions_2C2_Ferroalloy_Production - Gridded 2012 EPA Methane Emissions - Ferroalloy Production
EPA-annual-emissions_4A_Enteric_Fermentation - Gridded 2012 EPA Methane Emissions - Enteric Fermentation
EPA-annual-emissions_6A_Landfills_Municipal - Gridded 2012 EPA Methane Emissions - Municipal Landfills
EPA-annual-emissions_1B2b_Natural_Gas_Transmission - Gridded 2012 EPA Methane Emissions - Natural Gas Transmission
EPA-annual-emissions_5_Forest_Fires - Gridded 2012 EPA Methane Emissions - Forest Fires
EPA-annual-emissions_1B2b_Natural_Gas_Distribution - Gridded 2012 EPA Methane Emissions - Natural Gas Distribution
EPA-annual-emissions_4C_Rice_Cultivation - Gridded 2012 EPA Methane Emissions - Rice Cultivation
EPA-daily-emissions_5_Forest_Fires - Gridded 2012 EPA Methane Emissions - Forest Fires (daily)
EPA-monthly-emissions_1A_Combustion_Stationary - Gridded 2012 EPA Methane Emissions - Stationary Combustion (monthly)
EPA-monthly-emissions_4F_Field_Burning - Gridded 2012 EPA Methane Emissions - Field Burning (monthly)
EPA-monthly-emissions_4B_Manure_Management - Gridded 2012 EPA Methane Emissions - Manure Management (monthly)
EPA-monthly-emissions_1B2a_Petroleum - Gridded 2012 EPA Methane Emissions - Petroleum (monthly)
blue-tarp-detection
geoglam
EPA-monthly-emissions_4C_Rice_Cultivation - Gridded 2012 EPA Methane Emissions - Rice Cultivation (monthly)
co2-diff

**Comment by lubojr** [comment]
https://radiantearth.github.io/stac-browser/#/external/staging-stac.delta-backend.com/?.language=en Current updated STAC Browser viewed list

**Comment by lubojr** [comment]
Obsolete
