### ISSUE TITLE
Testing_VesselDensity_Indicator_From EDC contest Winner(Cimbelli)

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1773]
@santilland @lubojr  cc: @aapopescu 

We have a template of maps, timeseries and geojson associated.

here are the details of the test data
Scope:
Maps:
- Show on the map the monthly Maps
timeseries:
- Show the timeseries from the geoDB
- show detections from geojson for each record of the geoDB

Timeseries (254 records over Nederland:
database: eodash_stage
table_name: Vessels_density_Cimbelli_test5
and here the associated geojsons
[VesselDensity_test5.zip](https://github.com/eurodatacube/eodash/files/10033215/VesselDensity_test5.zip)

The maps of the monthly aggregations (one image per month for 2020 are in:
service endpoint: 0635c213-17a1-48ee-aef7-9d1731695a54
Layer ID: TEST_VIS_VESSEL_DENSITY_CIMBELLI_TEST5 --> 564708d9-08a1-46cf-ae3f-c1052e0c51b7

kr

Alessandro

**Comment by AlessandroScremin** [comment]
@lubojr  @santilland 

Is there already a staging environmet to udnerstand if it works? I'm on the way to finalize it with the data provider but had no feedback from your side so far.

Let me know

Alessandro

**Comment by lubojr** [comment]
Deployed currently on https://eodash-testing.eox.at/1791-1918-1773/?indicator=E1b

**Comment by lubojr** [comment]
-> I renamed the layer in branch `1791-1918-1773`

**Comment by AlessandroScremin** [comment]
@lubojr cc: @aapopescu 

Dear I updated the Time series in the GEO DB with the last verified data in this database-table

eodash-Sentinel_1_Vessel_Density_Europe

Still working on the geojsons.

I can send you the geojsons and once the tests with Diego are fine we can move them to the GEODB....

here are the geojsons:
[Sentinel_1_Vessel_Density_Europe_geojsons.tar.gz](https://github.com/eurodatacube/eodash/files/10500379/Sentinel_1_Vessel_Density_Europe_geojsons.tar.gz)

**Comment by lubojr** [comment]
@AlessandroScremin I have updated the referenced data from the Sentinel_1_Vessel_Density_Europe table in the branch.

As for the features, these are another 15k geojson files in total, and I would be very in favor of not putting them to the repository but already include them in geodb.
Do you think it will be feasible to do before the demo? The integration of the fetching of detections on from geodb on the dashboard was so far smooth. If not possible, we will add them to the repo and delete later.

**Comment by AlessandroScremin** [comment]
@lubojr 
the idea is to add them to the geoDB, but every table need to be configured manually first based on the field of the geojsons as they are not standardized...so it is not only matter of have a table but to configure it once for each indicator needed. We can try to be ready for the DEMO, but I would strongly reccomend to use the old approach for the demo first... and then delete the geojsons when table is tested and working....if you agree.

**Comment by lubojr** [comment]
@AlessandroScremin If we put something to git, if will stay there forever, so any operation like this that we could prevent by already starting the migration process would be beneficial, but okay we shall push the 15k GeoJSONs there to be ready for the demo.

**Comment by santilland** [comment]
Just to clarify, in order to use this for this specific instance we don't need all indicators features to be fully ready, only one the collection for this geosjon dataset would need to be created.
Do you think the ingestion into geodb of this feature collection set would mean so much effort?
I would really strongly recommend using geodb directly and only as a very last resort load this into the repository.

**Comment by AlessandroScremin** [comment]
@lubojr @santilland    cc: @aapopescu @dmoglioni 

Dear We ingested the new reprocessed data from the contest winner Cimbelli

So here the new references:

MAPS:
configuration ID: 0635c213-17a1-48ee-aef7-9d1731695a54  layer> 18b34412-cea1-43b0-8499-5c5064ea7a3b

eval script 
//VERSION=3
function setup() {
  return {
    input: [{
      bands: ["vessels", "dataMask"], // this sets which bands to use
    }],
    output: { // this defines the output image type
      bands: 4,
      sampleType: "UINT8"
    }
  };
}

function evaluatePixel(sample) {

  //var arr = colorBlend(sample.cargo,    [-100, -38.32, 33.33, 72.55, 100],    [[0,0,0,],[0,0,255],[0,154,87],[251,208,99],[214,130,49] ]); 
  var arr = colorBlend(sample.vessels,    [0, 80, 160, 240 , 320, 400 , 500],    
  [[0,0,0,0],[0,155,143,50],[0,219,0,100],[255,252,0,150],[244,154,0,150],[208,19,0,150], [161,0,0,190] ]); 
  if (sample.dataMask==1)  arr.push(255);
  else arr.push(0);
  return arr;
}



then Timeseries:
database = eodash  table name= Sentinel_1_Vessel_Density_Europe_Timeseries

Geojson ingestion
database = eodash  table name= Sentinel_1_Vessel_Density_Europe-detections

**Comment by lubojr** [comment]
@AlessandroScremin I have integrated the reprocessed cimbelli vessel density indicator on https://eodash-testing.eox.at/E1b-03-2023/ and noticed that in the input_data field for different dates have 4 different values: `S1A-GRD-IW-asc-VV`, `S1A-GRD-IW-des-VV` `S1B-GRD-IW-asc-VV` and `S1B-GRD-IW-des-VV`. In the WMS capabilities, I have found a single corresponding layer: `SENTINEL_1_IW_VV` but configuring it for all 4 input_data fields does not show any images for any tried dates (+-45 minutes around given date). Could you please confirm that we have the mapping `input_data` -> `layer_name` correct? Thank you!

cc @aapopescu

**Comment by lubojr** [comment]
E1b - reconfigure for the maps to be just individual ports + show the monthly map as another layer (inputData needs to be able to show 2 configs!) - dateformatfunction! @lubojr

**Comment by lubojr** [comment]
-> reconfigured
currently using S2L2A until https://github.com/eurodatacube/eodash/issues/2117#issuecomment-1470422280 is resolved
