### ISSUE TITLE
"info button" to show dataset source and metadata

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1777]
Repeatedly during GTIF demos, stakeholders have indicated the importance of being clear on the input data sources and their meta data. For example, the Energy Explore tools provide the "distance to settlements" filter, and here it is important to clarify which layer was used here (WSF2019, DLR) plus additional metadata (S1 S2 devices, Accuracy, URL to source, scientific publication DOI, etc.).  

Similarly, for science products such as Wind Power Density such a info button could provide more in depth information on the methods and models that were used to create this. 

Suggestion: add small info buttons (as below) that display this information on click. 

![Image](https://user-images.githubusercontent.com/40148967/202661509-7325195a-b69b-48fa-b7fc-4e1f9f5a7119.png)

**Comment by patrick-griffiths** [comment]
PS: where possible, connect and expose to STAC metadata?

**Comment by patrick-griffiths** [comment]
Initial list of relevant meta data fields(all TBD): 
-	Product name
-	Key product specs (spatial resolution, temporal reference, CRS, value range, 
-	Product description (external)
-	Methods employed (merge with above?)
-	Source URL
-	Source DOI (sci publication if available)
-	Input datasets (with cross reference) if applicable e.g. WSF uses S1 and S2
-	Reported accuracy

**Comment by santilland** [comment]
Look at how to integrate with catalogue as done in https://collections.eurodatacube.com/

**Comment by kegro** [comment]
> Initial list of relevant meta data fields(all TBD):
> 
> * Product name
> * Key product specs (spatial resolution, temporal reference, CRS, value range,
> * Product description (external)
> * Methods employed (merge with above?)
> * Source URL
> * Source DOI (sci publication if available)
> * Input datasets (with cross reference) if applicable e.g. WSF uses S1 and S2
> * Reported accuracy

To `Key product specs` we could also add: units

**Comment by patrick-griffiths** [comment]
@slumnitz

**Comment by kegro** [comment]
We (DHI) have made the first draft of the data descriptors for the Energy Transition section and send them in a document to @patrick-griffiths. We'll make a quick interation next week and hopefully give the go ahead to start integrating the text into the info button.

**Comment by patrick-griffiths** [comment]
This looks already very good @kegro and team. 
@santilland here is the link to the documents -  
even if it's maybe not yet perfect it would be good to integrate it with the info button functionality: 
https://esait.sharepoint.com/:w:/r/sites/GTIF-TeamSpaces-GTIF_RenewableEnergyScenario/Shared%20Documents/GTIF_RenewableEnergyScenario/[GTIF-energy-transition-data-descriptors.docx](https://esait.sharepoint.com/:w:/r/sites/GTIF-TeamSpaces-GTIF_RenewableEnergyScenario/Shared%20Documents/GTIF_RenewableEnergyScenario/GTIF-energy-transition-data-descriptors.docx?d=w8d8cd6d24f1e479ba77699f7fe4b86f9&csf=1&web=1&e=DINNQB)?d=w8d8cd6d24f1e479ba77699f7fe4b86f9&csf=1&web=1&e=DINNQB

**Comment by santilland** [comment]
Hello @patrick-griffiths im requesting access to the document but not getting it, could you send it to me via email?

**Comment by santilland** [comment]
Implementation finished, possibly updates to content required, should be handled on a different issue

**Comment by patrick-griffiths** [comment]
hi @lubojr 
please see attached some updates on the Renewables data descriptors provided by @kegro 

[GTIF-energy-transition-data-descriptors (002).docx](https://github.com/eurodatacube/eodash/files/10685805/GTIF-energy-transition-data-descriptors.002.docx)

@kegro and team indicated that we should update also the name of the tool for solar irradiation: 

> Attached is the latest data descriptor text. We’ve added the existing solar metadata (last entry in the attached document). The demo GTIF app calls it ‘Solar irradiance’, but its ‘Global horizontal irradiation’, to be more precise.
> /Kenneth
>

**Comment by lubojr** [comment]
Added in https://github.com/eurodatacube/eodash/commit/648e1eae5a6677b32fcce15163503f9558981184 (solar stuff) and https://github.com/eurodatacube/eodash/commit/79d13ec2289b6ef3d9ec225e3803ebb73940cb65 (hydropower initial things)
