### ISSUE TITLE
Detection maps: Two S1 acquisition in the same day

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1783]
@santilland @lubojr 

I have this situation that need attention and support from your side. And maybe a meeting.

I have a time series that in some case has two acquisiton very close in time, and are threated as separated acquisions:
o	               Time      Measurement Value
o	1             2020-12-01T17:32:31      101
o	2             2020-12-01T17:32:56      66

![s1 same day acquisitions](https://user-images.githubusercontent.com/65602207/202732087-f3c9ae0a-2e2a-4039-a257-22eefa6dbe74.png)

but they are adiacent images, so to cover all the AOI both images are needed.

Here the issue

if I keep them as separated records in the timeseries, you will have some issues in dispalying the chart (no aggregation feature for the same day implemented, right?) son same day 101, and same day 66
The second issue is that at each record there is a geojson associated with the detections. So each record has one geojson associated with acquisiton date and time.

but the value for that day is not 101 and not 66, but 167 (the sum of two.

How could we face this issue and allow the geoDB to give the proper amount for that day? =167
and how could we associate S1 image, geoDB recordS  and geojsons?

One solution could be to aggregate the record in the geoDB as one with value 167 (but then how could I associate to that acquistion the 2 images and the json detections?

hope its clear...otherwise we can have a call

**Comment by lubojr** [comment]
All clear, thank you for the detailed description and suggestion of options.
From my point of view it would make most sense to aggregate them in geodb with a timestamp of either first or second scene and also for the purpose of detections use that time only to generate a file with all of them. (167 features in total)

On eodash side, we can already adapt configuration to go around the different times of scenes by adding a margin to our TIME=start/end call, as we do in case of S2 scenes already. (this way we will request both scenes from SH).

**Comment by lubojr** [comment]
Added in https://github.com/eurodatacube/eodash/commit/8094d9653fe09a8b51644dd4f6dba1b493471dcb

**Comment by lubojr** [comment]
Closing the issue. Please reopen if needed.
