### ISSUE TITLE
Displace domain bar down so that breadcrumbs bar is located as for the other pages

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1788]
![Image](https://user-images.githubusercontent.com/4036819/203076166-f2ebd362-d694-455c-a57b-d67e40884faa.png)

**Comment by mariangela-cataldo** [comment]
The same applies to the right side panel. Apparently, the current breadcrumbs bar is located on top of the map viewer, while it should span the whole window like the top menu bar
