### ISSUE TITLE
Loading of new Cryosat data (first new story)

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1791]
To be updated by Anca once more information available.
If content available story release december.

Possible datasets:
- Regular EO-Data
- Envisat data?
- Sentinel-1
- Sentinel-2
- 4d Antartica Project https://4d-antarctica.org/products/

**Comment by aapopescu** [comment]
- Story AOI is Antarctica.  Cc: @AlessandroScremin , @santilland 
- need to display the data in polar coordinates. The Antarctica boundary can be extracted from this dataset: https://nsidc.org/data/nsidc-0756/versions/3 
- Supraglacial lakes dataset https://zenodo.org/record/5642755#.Y39Dwy8w3fZ 
- citation for the supraglacial lakes datasets: https://essd.copernicus.org/articles/14/209/2022/essd-14-209-2022-assets.html 
- Melt products (gridded format) - need to be requested

**Comment by AlessandroScremin** [comment]
@aapopescu @santilland 

I'm starting having a look a the links provided. I will invetigate:
Antartica:
- the Spatial OCverage: -53 -90, 180 -180
- CRS/Projections (at first glance the polar coordinates are not supported in SH so I think we should discuss how to proceed)
- Time interval: is only oine netcdf covering 1970 to 2019 so I'm looking if it is a multi layer, single file or multi parametrs

I will do the same for the other datasets. This is to have an understanding of the strucutre of the files, which are the potential issues with SH ingestion, and which type of datasets are provided. I already saw vector and raster data 

i will update you

**Comment by aapopescu** [comment]
- Antarctica geopackage : https://data.bas.ac.uk/items/1db7f188-6c3e-46cf-a3bf-e39dbd77e14c/

**Comment by aapopescu** [comment]
[ESA Cryosphere Story.docx](https://github.com/eurodatacube/eodash/files/10228030/ESA.Cryosphere.Story.docx)

**Comment by santilland** [comment]
Anca provided new document version (two inputs available NASA/JAXA) https://drive.google.com/drive/folders/1KeX_-uMJGWtuECN129vt-o8i2WF5-5jc

- [ ] EOX to provide feedback on data ingested by Alessandro
- [ ] EOX create initial story based on ESA document (Thwaites Glacierv2) including images/sources NASA and send links to Anca
- [ ] EOX Possiblity to convert geopackage to geojson and show it as "feature"/"detection" as we do for other indicators

**Comment by AlessandroScremin** [comment]
@aapopescu 
from the documentation and link to the project I was not able to find what exactly the maps refer to and their measurement unit as ewquested by @lubojr 

To whom can I ask the unit measure?
we fund that for meltmap the min max values are 0 to 3 but not information about the unit.

**Comment by lubojr** [comment]
:arrow_double_up: Solved
Now waiting for the feedback/modification on the story content + progress on the S1 available dates over Antarctica

**Comment by lubojr** [comment]
-> story will be split to 2/3 individual stories, a new WMS layer `SENTINEL-1-EW` was defined and integrated as &poi=S1GRD-ADD

**Comment by lubojr** [comment]
-> to finalize integrate these 3 layers
- [ ] VIS_4D_ANTARTICA_DAYS, VIS_4D_ANTARTICA_END, VIS_4D_ANTARTICA_ONSET

**Comment by AlessandroScremin** [comment]
@lubojr 
_onset and _end have same color scale from 1 to 365
_days values range from 3 to 210


VIS_4D_antartica_days
ID: VIS_4D_ANTARTICA_DAYS --> 187112e0-de59-46f1-af76-86d7aec33c9e
Color scale:
[3,15,30,45,60,75,90,105,120,135,150,165,180,195,210]
[[48,107,255],[72,142,255],[92,165,255],[111,180,255],[130,190,255],[148,199,255],[163,208,255],[178,216,255],[194,222,255],[206,229,255],[216,236,255],[225,242,255],[233,246,255],[242,251,255],[251,255,255]

VIS_4D_antartica_end
ID: VIS_4D_ANTARTICA_END --> c46a325b-9509-40d2-b0bd-50d73ef86f68
Color scale: 
[1,27,53,79,105,131,157,184,210,236,262,288,314,340,365]														
[48,107,255],	[72,142,255],	[92,165,255],	[111,180,255],	[130,190,255],	[148,199,255],	[163,208,255],	[178,216,255],	[194,222,255],	[206,229,255],	[216,236,255],	[225,242,255],	[233,246,255],	[242,251,255],	[251,255,255]

VIS_4D_antartica_onset
ID: VIS_4D_ANTARTICA_ONSET --> 59d1245b-46ac-438f-b7be-32d550da04f3
color scale:
[1,27,53,79,105,131,157,184,210,236,262,288,314,340,365]														
[48,107,255],	[72,142,255],	[92,165,255],	[111,180,255],	[130,190,255],	[148,199,255],	[163,208,255],	[178,216,255],	[194,222,255],	[206,229,255],	[216,236,255],	[225,242,255],	[233,246,255],	[242,251,255],	[251,255,255]
