### ISSUE TITLE
Zoom to area on Cryospahere data is wrong

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1805]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?search=World%3A+Carbon+Dioxide+%28CO2%29+Difference&amp;x=8348961.8095&amp;y=-1113194.90793&amp;z=2.49185&amp;poi=W5-N2">https://www.eodashboard.org/explore?search=World%3A+Carbon+Dioxide+%28CO2%29+Difference&amp;x=8348961.8095&amp;y=-1113194.90793&amp;z=2.49185&amp;poi=W5-N2</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 105</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Load one cryosphere dataset. Map does not center on the data.</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Map should go to where the data is.</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Fixed by latest developments of new cryo stories. All cryo POIs have a `presetView` config now.
