### ISSUE TITLE
[Urban] metadata reporting of produced datasets

### ISSUE THREAD

**Issue by slumnitz** [eurodatacube/eodash#1808]
Idea: The idea is to provide space to display more detailed information not he generation of scientific products. Ideas so far mentioned where:
* Info button in explore [preferred]
* additional scrollytelling element 
* description in standard explore interface (right lower corner)

Please decide where metadata information should be displayed.

Please communicate with the Science Team to provide metadata information for science products. I.e. to hand over powerpoint discussed at KO.

**Comment by santilland** [comment]
Additional metadata has been provided and added to info button for each dataset, closing issue
