### ISSUE TITLE
Search retrieves wrong result

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#1809]
**Describe the bug**
Search for Economy + Country --> result includes all themes. Should be just Economy in that country

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 105.0.5195.102

**Steps to reproduce**
Steps to reproduce the behaviour.

**Expected behaviour**
If search includes more than 1 filter (e.g. theme + location) the operation should be logical AND

**Screenshots**
<img width="737" alt="Screenshot 2022-11-29 at 09 31 49" src="https://user-images.githubusercontent.com/35488732/204478910-a90565ca-1047-4c8a-88e8-ab473effb4c2.png">

**Comment by silvester-pari** [comment]
More words should actually reduce the search results instead of increasing them

**Comment by santilland** [comment]
Server side search is being evaluated, part of UX evaluation/consultancy

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
