### ISSUE TITLE
Update BIOMASS icon

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1815]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?search=Economy%2C+United+States&amp;x=-3787611.66614&amp;y=2257560.9332&amp;z=3.12416">https://www.eodashboard.org/explore?search=Economy%2C+United+States&amp;x=-3787611.66614&amp;y=2257560.9332&amp;z=3.12416</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Biomass icon should better show a leaf/tree</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
changed to leaf in https://github.com/eurodatacube/eodash/commit/255133ebf4f4ef22962e4cc3ab9be3defe954360
