### ISSUE TITLE
GEOGLAM indicator is duplicated

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1816]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?x=0&amp;y=-1112422.39238&amp;z=2.49285&amp;search=GEOGLAM%20Crop%20Conditions">https://www.eodashboard.org/explore?x=0&amp;y=-1112422.39238&amp;z=2.49285&amp;search=GEOGLAM%20Crop%20Conditions</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Search for GEOGLAM Crop conditions
Select option from search result. Nothing loads on the map.
This indicator is duplicated and it should be removed. There is already the global indicator &quot;Cropped Area&quot;. </p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Indicator should be replaced</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by silvester-pari** [comment]
closed in favor of #1819
