### ISSUE TITLE
Quicklook for NASA OMI NO2 is wrong

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1818]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?x=8343167.94287&amp;y=-1112422.39238&amp;z=2.49285&amp;search=World%3A%20Air%20Quality%20-%20OMI%3A%20Monthly%20NO2&amp;poi=W2-N1">https://www.eodashboard.org/explore?x=8343167.94287&amp;y=-1112422.39238&amp;z=2.49285&amp;search=World%3A%20Air%20Quality%20-%20OMI%3A%20Monthly%20NO2&amp;poi=W2-N1</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Quicklook for NASA OMI NO2 is showing the difference one. </p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Quicklook shows the NASA OMI NO2</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
fixed by https://github.com/eurodatacube/eodash/commit/9a35a38e0a2d808f25d010c3bf3e2f0b91fc5688

**Comment by lubojr** [comment]
@aapopescu Why was this reopened?
