### ISSUE TITLE
Search offers 2 options of the same indicator

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#1819]
**Describe the bug**
Search for any global indicator results in 2 entries in the dropdown list. One option contains the label "World:". This is the only one that loads correctly. The other option does not load the data correctly.

**Desktop (please complete the following information):**
MacOS
Chrome Version 105.0.5195.102

**Steps to reproduce**
Search for any global indicator results in 2 entries in the dropdown list. One option contains the label "World:". This is the only one that loads correctly. The other option does not load the data correctly.

**Expected behaviour**
Single entry for any indicator

**Screenshots**
<img width="716" alt="Screenshot 2022-11-29 at 18 01 47" src="https://user-images.githubusercontent.com/35488732/204595452-0cab03ca-83fa-47bc-a30c-ec433e143a7b.png">

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
