### ISSUE TITLE
unify where modal close button is located

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#182]

**Comment by lubojr** [comment]
implemented in https://github.com/eurodatacube/eodash/commit/e5c8cf2d42b99b0d3ee979f523d21fe55ffc882d
also added close wide screen mode on "esc" button pressed

**Comment by lubojr** [comment]
Ad https://github.com/eurodatacube/eodash/pull/189#issuecomment-641132978 needs further discussion

**Comment by Schpidi** [comment]
agreed to leave current behavior. esc button support is great.
