### ISSUE TITLE
Water Quality regional maps + POIs unification 

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1820]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?search=North+Adriatic+-+Total+Suspended+Matter%3A+Water+Quality+Regional+Maps+%28JAXA%29&amp;x=1398521.6122&amp;y=5611415.02475&amp;z=7.76952&amp;clusterOpen=2&amp;poi=NorthAdriaticTSM_JAXA-N3a2">https://www.eodashboard.org/explore?search=North+Adriatic+-+Total+Suspended+Matter%3A+Water+Quality+Regional+Maps+%28JAXA%29&amp;x=1398521.6122&amp;y=5611415.02475&amp;z=7.76952&amp;clusterOpen=2&amp;poi=NorthAdriaticTSM_JAXA-N3a2</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Select Water and Ocean filter. Search field - drop down options: the POIs are not specified like the POIs in the rest of the themes (&quot;city: indicator&quot;).
Water quality maps do not load. Map does not zoom to AOI</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Map loads. Time series chart loads. Map zooms to AOI. POI is specified like the rest of POIs.</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
renamed theme "oceans and water" to "oceans" and changed "biomass-and-landcover" slug to not contain spaces

temporary solution until new search functionality is implemented
https://github.com/eurodatacube/eodash/commit/ce4ed8420c1608bf5c2f9d0870cdf6954c097e72

**Comment by aapopescu** [comment]
not fully solved but can be included in this release

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach. Aggregation is now done on indicator level and filtering is done via a new tool.
