### ISSUE TITLE
Water quality time series are missing

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1821]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?search=Water+Quality+Time+Series&amp;x=966454.16186&amp;y=4006456.31951&amp;z=2.8678">https://www.eodashboard.org/explore?search=Water+Quality+Time+Series&amp;x=966454.16186&amp;y=4006456.31951&amp;z=2.8678</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>type in search bar water &quot;quality time series&quot;. No points load</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>points load on map</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by silvester-pari** [comment]
closed in favor of #1820 - issue is related to naming of POIs

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
