### ISSUE TITLE
Nightlights legend needs harmonisation

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1822]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?x=19500279.44061&amp;y=-4428352.01392&amp;z=10.04624&amp;search=Auckland%3A+Nightlights&amp;poi=NZ01-N5">https://www.eodashboard.org/explore?x=19500279.44061&amp;y=-4428352.01392&amp;z=10.04624&amp;search=Auckland%3A+Nightlights&amp;poi=NZ01-N5</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Nightlight legend</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Harmonised with the rest of legends</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Fixed by https://github.com/eurodatacube/eodash/commit/b33d5532e9b0d4bf8c6346c89eacf9cdd9b3fe28 
Now only 3 old legends remain as they are specific (classes, instead of values). Palsar Forest map, World settlement footprint and agriculture geoglam.
