### ISSUE TITLE
Blue tarps data implementation

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1823]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?x=-7355391.73806&amp;y=2082761.4407&amp;z=16.49472&amp;clusterOpen=2&amp;poi=det51-N13&amp;search=Detection+source+data%3A+Blue+Tarps+%28PlanetScope%29">https://www.eodashboard.org/explore?x=-7355391.73806&amp;y=2082761.4407&amp;z=16.49472&amp;clusterOpen=2&amp;poi=det51-N13&amp;search=Detection+source+data%3A+Blue+Tarps+%28PlanetScope%29</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Blue tarps POIs are undefined; detections not visible</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Blue tarps POIs are correctly defined and detections are visible</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by silvester-pari** [comment]
Detections are very tiny; disable Blue Tarps Detections for now (including Planet Data) and check how to display them properly

**Comment by lubojr** [comment]
Datasets were removed from eodashboard
