### ISSUE TITLE
Mobility data zoom to location

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1824]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?x=-4305228.47667&amp;y=1404816.89052&amp;z=3.15&amp;clusterOpen=2&amp;poi=BO-GG&amp;search=Bolivia%3A%20Mobility%20Data">https://www.eodashboard.org/explore?x=-4305228.47667&amp;y=1404816.89052&amp;z=3.15&amp;clusterOpen=2&amp;poi=BO-GG&amp;search=Bolivia%3A%20Mobility%20Data</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Selecting Mobility data point from dropdown list does not zoom to location</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>zoom to location</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Should it really zoom to location even though we do not have EO data here?

**Comment by silvester-pari** [comment]
> Should it really zoom to location even though we do not have EO data here?

@lubojr if I remember correctly, it is supposed to zoom to the country bounds

**Comment by lubojr** [comment]
fine then, assigning the issue to me

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
