### ISSUE TITLE
Search field reset

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#1825]
**Describe the bug**
Clearing the text in the search field does has no effect on the map. 

**Desktop (please complete the following information):**
MacOS
Chrome

**Steps to reproduce**
Type search words in Search bar. Select one option from dropdown list. Clear the search bar. Nothing happens on the map

**Expected behaviour**
The user should be able to go back to the full map view.

**Comment by silvester-pari** [comment]
Thanks for reporting! Can you describe how you are trying to clear the text? In the following video, I tried three things (on MacOS/Chrome and on Linux/Firefox):

- pressing `escape` key -> clears the filter :heavy_check_mark: 
- pressing `ctrl+a` and then `delete` key -> clears the filter :heavy_check_mark: 
- pressing `delete` key multiple times to delete entire word -> clears the filter :heavy_check_mark: 

https://user-images.githubusercontent.com/26576876/204741863-0a61a943-a9bd-4a6c-9fca-bb3a6970691c.mp4

**Comment by silvester-pari** [comment]
So, after clicking a POI and loading the POI, clearing the text does not clear the filter;
either only allow back button, or clear filter as soon as the text changes, or clear if completely empty string

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
