### ISSUE TITLE
Search back arrow issue

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1826]
**Describe the bug**
using the back arrow after havin selected different indicators AOI, the URL change but the image/indicator on the map remains the same

**Desktop (please complete the following information):**
 - Windows
 - chrome
 - Version 107.0.5304.108

**Steps to reproduce**
Select economy filter, then click on the dropdown window one AOI the map move on the AOI and indicaotr selcted. Select another proposed AOI and indicator and the new AOI indicator map appear (you can do it how many time you want and works. Then I use the back arrow in the search and here the problem. I see the URL changing to the previous indcaotr but the map don't change

**Expected behaviour**
I would expect that if the URL change also the map change accordingly

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
