### ISSUE TITLE
Zoom to country not working using health indicaotr

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1827]
**Describe the bug**
Health data (covid 19 vaccinations indicator). Selecting a country the map remain where it is zoomed

**Desktop (please complete the following information):**
 - Windows
 - Browser chrome
 - Version 107

**Steps to reproduce**
Select the Health filter in the search and then selct a country for displaying the vaccinations/or covid cases.

**Expected behaviour**
It is expected to move the map on the country selected and at least to see the country highlighted, but the map doesn't move and no zoom on the country or shape selections happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/65602207/204765651-1c1efb90-b928-4060-a378-4aff0f78e57b.png)

**Comment by silvester-pari** [comment]
already reported in #1824

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
