### ISSUE TITLE
Clear search not working properly

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1828]
**Describe the bug**
Oce an indicaotr is selcted and displayed, I try to clear the search to get back to maps and other indicators but nothing happens

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 107

**Steps to reproduce**
I search for ship, and select the indicator Fishing ships in port based on AIS data, on several AOIs. After that I clear the search deleting the content and nothing happen. I can't see the global indicaotrs, nor other AOI.

**Expected behaviour**
When I clear the search I expect to get back to the home.

**Screenshots**
![image](https://user-images.githubusercontent.com/65602207/204767342-222e4d58-d3e6-4be0-8854-35e95715b4e7.png)

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
