### ISSUE TITLE
Country defined as Array is not found in the search

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#1832]
When searching for a country, this is internally translated into the country Code (e.g. "BR"). Some POIs, however, have an Array as country (e.g. `["BR"]`) and are not found during the search.
Either make the search algorithm find coutnries in arrays as well, or flatten the countries if possible

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
