### ISSUE TITLE
permalink feature issues

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#184]
there are multiple points
- [x] country filter doesn't show country selected in filters list
- [x] when to zoom, should e.g. https://race.esa.int/?poi=NorthAdriatic-N3a2 zoom to sub-aoi?
- [x] highlight POI is missing (example same URL as above)

**Comment by silvester-pari** [comment]
related to #185

**Comment by silvester-pari** [comment]
this seems to be only a bug on the production url, as on staging it seems to work :thinking: maybe @lubojr has already done some experimentation?

**Comment by lubojr** [comment]
sub-aoi problem is separate that does not work locally too, as this is not reactive in map
generalized issue is a bug of production url, yes
I have not yet been experimenting with it.

**Comment by silvester-pari** [comment]
somehow, the issue seems to be resolved on production url as of today. magic?

**Comment by Schpidi** [comment]
first point looks solved, cool.

the third point is not working for me:
![Screenshot from 2020-06-15 15-23-42](https://user-images.githubusercontent.com/482265/84662543-3c125180-af1c-11ea-9292-189256596d7a.png)

**Comment by lubojr** [comment]
third point has been fixed with https://github.com/eurodatacube/eodash/commit/46d2b0dd150e990f376a5d16d372fe7c26c9f822 currently (not optimal), we are checking if indicator has aoi and then use its feature id as selected
so AOI and id need to be filled too for indicators appearing on map but not coming from csv (regional)

**Comment by lubojr** [comment]
ad 2 from discussion no, but it will zoom to subaoi if only 1 item is left from filter as in https://race.esa.int/?country=regional or https://race.esa.int/?indicator=E10a1 implemented in https://github.com/eurodatacube/eodash/commit/252cee75b09d9ae874ca2584bbe59e9df0eb4897
