### ISSUE TITLE
Data definition for data exchange

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1843]
In order to provide as clear as possible specification on how to interchange data, and also as reference for what administrative zones should be used for generation we are creating this ticket.

Firstly the administrative zones from statistic austria will be used (from the year 2022):
(NUTS 0-3 to be discussed if necessary for data generation, see links at the bottom)
- Bezirke: https://data.statistik.gv.at/data/OGDEXT_POLBEZ_1_STATISTIK_AUSTRIA_20220101.zip
- Gemeinden: https://data.statistik.gv.at/data/OGDEXT_GEM_1_STATISTIK_AUSTRIA_20220101.zip
- Zählsprängel https://data.statistik.gv.at/data/OGDEXT_ZSP_1_STATISTIK_AUSTRIA_20220101.zip

Even for future generation (next years) or data from previous years we think it would be best to maintain the use of the 2022 geometries to make sure time analysis is possible.

As for the data format for data mapped to these administrative zones we recommend the use of json files following these schema:

**JSON Schema:**

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "items": {
      "type": "array",
      "minItems": 1,
      "items": [
        {
          "type": "object",
          "properties": {
            "adminZoneID": {
              "type": "string"
            },
            "time": {
              "type": "string"
            },
            "parameters": {
              "type": "object"
            }
          },
          "required": [
            "adminZoneID",
            "time",
            "parameters"
          ]
        }
      ]
    }
  },
  "required": [
    "items"
  ]
}
```

**JSON Example:**
```
{
  "items": [
    {
      "adminZoneID": "adminZone1",
      "time": "20220101T00:00:00Z",
      "parameters": {
        "no2": 1.0,
        "pm10": 1.0
      }
    },
    {
      "adminZoneID": "adminZone1",
      "time": "20220102T00:00:00Z",
      "parameters": {
        "no2": 1.0,
        "pm10": 1.0
      }
    }
  ]
}
```
A validator can be used to check if the created JSON matches the schema, e.g.: https://www.jsonschemavalidator.net/

If the format is not possible following aspects would be important for the data:

- Use of same ID as used in the statistic austria administrative zone data listed above
- When using times(stamps) use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format

- https://github.com/eurodatacube/eodash/blob/staging/app/public/data/gtif/data/AT_NUTS_L0.geojson
- https://github.com/eurodatacube/eodash/blob/staging/app/public/data/gtif/data/AT_NUTS_L1.geojson
- https://github.com/eurodatacube/eodash/blob/staging/app/public/data/gtif/data/AT_NUTS_L2.geojson
- https://github.com/eurodatacube/eodash/blob/staging/app/public/data/gtif/data/AT_NUTS_L3.geojson

**Comment by sistemagmbh** [comment]
The creation of such a JSON file would not be a problem at all. The geofile of **Zählsprängel** comes already with a column, `name`, with a numeric unique code that can be used, which if im not mistaken was present in the results that we sent you last time. Otherwise can be sent again. 

One question that I have: As far as I remember, we are computing aggregated data. For instance last time we computed the aggregation of measurements over weekdays and weekends. That is why I am not sure if a `time` paramenter makes sense.

**Comment by santilland** [comment]
Time aggregation might be a bit tricky, good point.
As usually i think we will have a "single" time entry per dataset we could keep `time` as default and add an optional entry called `timeEnd` or `aggregationTimeEnd` when a data is aggregated for longer time periods and use `time` as aggregation start.
If we know the data is aggregated in a specific way, for example daily, we can probably ignore the `timeEnd`, or use only the date in the time string.
In previous discussions i think the Air quality team mentioned wanting to have daily resolution for this data, maybe @DanGasb you could also comment on the expected time aggregation for the mobility data.

**Comment by ubi15** [comment]
Another question: sometimes it may happen (for instance when computing human presence count/density) that some remote areas at some times of the day are empty and they do not appear in our output table.

It may happen that an area is empty at a given hour of the day and then filled during some others.

Shall we:
- leave out the area from the json for the empty hours (no entries for such areas at those problematic hours);
- report the area with a default value (e.g., 0 for human count);
- leave the value as `null`.

Will leave tomorrow a further comment on time aggregation following the previous messages.

**Comment by santilland** [comment]
Also good question. I think this depends a little on how we want to interpret that an area has no value.
If we remove the value from the json i would consider this equivalent to there being no data, which if that were the case would be a good approach.
But i think in this case we want to actually show that a "0 human count" was "detected".
Considering showing a time evolution scatter plot over time for an area, if we leave completely leave out the value we would only see entries for times where humans were counted, but i think we actually also want to show points for times where no humans were counted.

So i think for this particular case setting a default value of 0 makes sense, what do you think?

**Comment by santilland** [comment]
I think the method for data exchange has been clarified for now, closing this issue. If any new issues appear related to data exchange we can either open a new issue or reopen this one
