### ISSUE TITLE
Legend of Builtup Areas missing

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1851]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/?x=260550.31234&amp;y=6243002.19734&amp;z=9.74211&amp;poi=WSF-WSF&amp;search=World%3A+Builtup+areas">https://race.esa.int/?x=260550.31234&amp;y=6243002.19734&amp;z=9.74211&amp;poi=WSF-WSF&amp;search=World%3A+Builtup+areas</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 108</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Load Builtup Areas global layer. Legend is not shown</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Legend is shown</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
fixed in https://github.com/eurodatacube/eodash/commit/febdb6df876036bc7051329c678f27ce322369ea
