### ISSUE TITLE
Add indicators for EO adaptation services

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1858]
Two new entries to be added to the EO adaptation services domain:

- Beetle infestation (focus on  Lower Austria)
- Storm damage (focus on  Styria)

Data available in the FCM folder

**Comment by patrick-griffiths** [comment]
- define names or these two elements (e.g. "storm damages", "bark beetle risk")
- zoom to regions where these can be explored @santilland 
- **ability to overlay S2 images**
   - storm damages August 2022 -  list of all useful S2 images for Styria @AlonsoItziar @AlessandroScremin 
   - [ lower priority: bark beetle 2018 (lower Austria)

**Comment by AlonsoItziar** [comment]
These are the 2 (you need both to cover the area) S2 images in August 2022 for the Styria region with less cloud coverage that I could find:
1. 
s3://sentinel-s2-l2a/tiles/33/T/VN/2022/8/18/0/ue
https://scihub.copernicus.eu/dhus/odata/v1/Products('a62b6fbf-d82c-4c21-ba07-a4988fc79545')/$value
Additional details
2022-08-18
10:07:40 UTC
18.3%
33TVN
2. 
s3://sentinel-s2-l2a/tiles/33/T/WN/2022/8/18/0/
https://scihub.copernicus.eu/dhus/odata/v1/Products('f5963c2a-0824-4db3-9f4c-50127acf0af4')/$value
Additional details
Sentinel-2 L2A
2022-08-18
10:07:36 UTC
49.0%
33TWN

**Comment by santilland** [comment]
Indicators for EO adaptation services have been integrated, separate issue has been created for s2 data overlay, see https://github.com/eurodatacube/eodash/issues/2081
Closing this issue
