### ISSUE TITLE
handling unclear, no guidance how to sort out viewing.

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#186]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 1.0.0</p>
<p><strong>Current URL:</strong> <a target='_blank'  href="https://race.esa.int/?country=GR&amp;indicator=N1&amp;poi=World-N1">https://race.esa.int/?country=GR&amp;indicator=N1&amp;poi=World-N1</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 13</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>no idea </p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>To see what one selects, e g Country, Air quality. There are two (2) maps, a small one right seems to show what I want. The other , left? No idea..  And why no language to chose from?</p>
<h3 id="contact-information-or-additional-comments-optional">Contact information or additional comments (optional):</h3>
<p><a target='_blank'  href="mailto:&#104;&#106;&#x67;&#x75;&#110;&#64;&#x69;&#99;&#x6c;&#111;&#x75;&#x64;&#x2e;&#99;&#111;&#109;">&#104;&#106;&#x67;&#x75;&#110;&#64;&#x69;&#99;&#x6c;&#111;&#x75;&#x64;&#x2e;&#99;&#111;&#109;</a> 
Hans J Gundlach </p>

**Comment by silvester-pari** [comment]
i think both comments (two maps, and additional languages) are referring to things we do not intend to change. although we could think about ways of improving user guidance witch a tutorial etc. see https://github.com/eurodatacube/eodash/issues/187
