### ISSUE TITLE
Wind Power Density - additional and updated layers

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1861]
Prepare for additional and updated Wind Power Density layers: 

- two seasonal estimates (summer, winter)
- 2-3 different turbine heights

Considering various combinations, this will result in 4-6 layers.. @kegro please confirm

@santilland The explore tools will need provide the option of choosing these

The idea is to provide dummy datasets for this within January, final delivery later...

**Comment by santilland** [comment]
For the flux data we have developed loading of different cogs based on time selection, that would work for the seasons for sure.
If additionally selection options are needed for turbine heights we would need to discuss how to do it. This would require quite probably new logic implementation.

**Comment by patrick-griffiths** [comment]
DHI will provide 3 WPD layers for different turbine heights (50, 100, 200m) 
Thus, we need a drop down menue to select these 3 layers. 
This will be ready for beta release @kegro pls keep us posted

The different seasonal estimation will become available later not for February

**Comment by patrick-griffiths** [comment]
Hi @santilland just FYI the layers (i.e. new ones at 50 and 200m hub height, the one that is online is the 100m which we keep) have yesterday been provided by @kegro and team. @AlonsoItziar is ingesting them. So it would be great to have that dropdown menu option soon...

**Comment by Schpidi** [comment]
I'm afraid the 3 COGs we got so far are all corrupt. I see errors like this for all 3:

```
gdalwarp -of COG -t_srs EPSG:3857 -co BIGTIFF=YES -co COMPRESS=DEFLATE PowerDensity_100m_Austria_WGS84_COG.tif PowerDensity_100m_Austria_WGS84_COG_3857.tif
Creating output file that is 65462P x 33854L.
Using internal nodata values (e.g. nan) for image PowerDensity_100m_Austria_WGS84_COG.tif.
Copying nodata values from source PowerDensity_100m_Austria_WGS84_COG.tif to destination .
0...10...20...30...40.ERROR 1: TIFFFillTile:Read error at row 58880, col 13824, tile 1612; got 450537 bytes, expected 775082
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: PowerDensity_100m_Austria_WGS84_COG.tif, band 1: IReadBlock failed at X offset 116, Y offset 11: TIFFReadEncodedTile() failed.
ERROR 1: IReadBlock failed at X offset 109, Y offset 62: PowerDensity_100m_Austria_WGS84_COG.tif, band 1: IReadBlock failed at X offset 116, Y offset 11: TIFFReadEncodedTile() failed.
```

**Comment by patrick-griffiths** [comment]
Great, thanks for checking and confirming @kegro

We will likely have to update the colour table and stretch avoiding, so stay tuned 😉

**Comment by santilland** [comment]
Layer selection has been implemented in client, datasets have been provided. Implementation considered finished, closing issue
