### ISSUE TITLE
Solar irradiance - additional and updated layers

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1862]
Prepare for additional and updated Solar irradiance layers (Renewable explore tools):

- two seasonal estimates (summer, winter)
- different times of the day (2-3)

Considering various combinations, this will result in 4-6 layers.. @kegro please confirm

@santilland The explore tools will need provide the option of choosing these different layers

The idea is to provide dummy datasets for this within January, final delivery later...

**Comment by santilland** [comment]
From a technical standpoint same as #1861 
For keeping track on data to be provided and need for loading it is good to keep this ticket

**Comment by santilland** [comment]
Waiting for data inputs

**Comment by santilland** [comment]
Data has been delivered, integration into client has been done, data description is outdated, should we still merge newest data to demonstrator @patrick-griffiths ?

**Comment by patrick-griffiths** [comment]
@santilland
Let's maybe just wait for updated days descriptions before going live with this.


@kegro could you and team update these next week, please?

**Comment by santilland** [comment]
Data descriptions received, ready to merge to demosntrator

**Comment by santilland** [comment]
Merge done, closing issue
