### ISSUE TITLE
Hydropower explore tools

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1863]
current thinking: 
- hydro reservoir geometries will be displayed in map view (exist already at DHI - could be integrated early @kegro?)
- cursor query functionality allows displaying hydro reservoir metadata (e.g. name, damm height, building year, etc.)
- cursor query functionality allows investigating (1) dynamic lake level monitoring time series, (2) equivalent energy storage potential, which are precomputed (lake levels come from DHI altimery algorithms)

beta delivery within January

**Comment by santilland** [comment]
Very preliminary dataset integrated, waiting for full dataset. Leaving this issue open for now as reference of what parameters are expected to be present. Issue could be extended to better define expected information to be shown on selection.

Selection method being tracked in new issue:
https://github.com/eurodatacube/eodash/issues/2094

**Comment by lubojr** [comment]
Integrated already
