### ISSUE TITLE
Micro-Hydropower explore tools

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1864]
Visualize and enable information queries for suitable Micro-Hydropower location points (run-of-river) 

beta delivery in January 2023 (TBC)

**Comment by patrick-griffiths** [comment]
@santilland 
part of this will require hover functionality, that allows displaying the information of a point dataset of micro hydro estimates.. 
@AlonsoItziar @kegro 
For visualization here we would also need catchments and small river networks

**Comment by patrick-griffiths** [comment]
@lubojr 
any updates on this? will it be feasible to integrate the one hydro reservoir along with the time series provided earlier?

**Comment by lubojr** [comment]
@patrick-griffiths I am now actually working on this. Yes that one hydro reservoir will be integrated until the release.

**Comment by patrick-griffiths** [comment]
@lubojr and @santilland 

as we will be at the BMK next Monday, it would be good to complete the integration of this first hydro reservoir monitoring preview. Is there any progress to report?

**Comment by lubojr** [comment]
@patrick-griffiths No progress to report yet, but we have now internally decided how we would deal with the fact that we have just data for one reservoir (the geometry selecting logic is something we shall skip for now) and just zoom to the one dam and auto pick it for the user and we shall integrate the provided data returning a chart as close as possible to the example in the provided excel until next Mo.

**Comment by lubojr** [comment]
Micro hydropower datasets are integrated
