### ISSUE TITLE
[renewables] change scrollytelling video triggers

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1885]
in the current scrollytelling the triggers for the first two videos need to be changed. 

first video is currently "triggered" by mouse scrolling - but it is very long and its not ideal. 
This first video should play automatically once it comes into view...

![Image](https://user-images.githubusercontent.com/40148967/211326301-c6d3546a-f0d2-42ca-8507-f3af54cf8d28.png)

The second video is currently triggered automatically when it comes into view, but this one should be triggered by scrolling (individual graphs are shown when the users scrolls further down)

![Image](https://user-images.githubusercontent.com/40148967/211327355-6aba2edf-552f-455e-aa01-48dc6dc8662a.png)

So here the current video triggers need to be swapped

**Comment by danielfdsilva** [comment]
@patrick-griffiths Different Daniel perhaps?
