### ISSUE TITLE
Adding Truck detection maps 2020-2021 Monthly reprocessing

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1918]
@santilland  @lubojr  cc: @aapopescu  Need to add the new reprocessed maps for truck detection on mothly bases. 

Vis_Truck_detection_Motorways_new
ID: VIS_TRUCK_DETECTION_MOTORWAYS_NEW --> 34fbfb05-c3e5-4885-9840-830ee85dddd4
Vis_Truck_detection_Primary_new
ID: VIS_TRUCK_DETECTION_PRIMARY_NEW --> 81201dac-c408-4cf8-b9a5-ca8349e4ab6c

**Comment by lubojr** [comment]
Latest progress on https://eodash-testing.eox.at/1791-1918-1773/?poi=W2-E12c
-> to clarify what to do with features / custom area indicator

**Comment by lubojr** [comment]
Decided to leave features out for now. For custom chart, we are going to need a name of eodash table to fetch the data from.
cc @AlessandroScremin

**Comment by lubojr** [comment]
-> Data are currently being ingested to production tables (E12d running now)

ETA Friday -> @lubojr test visualisation of the multipoint & adapt if needed

**Comment by AlessandroScremin** [comment]
@lubojr 
cc: @dmoglioni 

E12c and E12d geojson for truck detections have been ingested in GEODB
