### ISSUE TITLE
Layers menu is hidden behind legend

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1920]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?search=World%3A+Builtup+areas&amp;x=-13088394.89595&amp;y=4003604.51015&amp;z=9.94333&amp;poi=WSF-WSF">https://www.eodashboard.org/explore?search=World%3A+Builtup+areas&amp;x=-13088394.89595&amp;y=4003604.51015&amp;z=9.94333&amp;poi=WSF-WSF</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 108</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Click on layers button on map. The options are behind the legend</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>The options should be in front of the legend</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Fixed already
