### ISSUE TITLE
Change colormap for mobility data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1939]
possibly
export const colorRange = [
  [1, 152, 189],
  [73, 227, 206],
  [216, 254, 181],
  [254, 237, 177],
  [254, 173, 84],
  [209, 55, 78]];

![Image](https://user-images.githubusercontent.com/4036819/215103748-64712619-e944-49a7-9550-3e4fd3a29f81.png)

**Comment by santilland** [comment]
Duplicate of https://github.com/eurodatacube/eodash/issues/1940

**Comment by patrick-griffiths** [comment]
@lubojr  looks good but can we please add the color bar info such as units and color bar, sent earlier by Mindearth, attached below

[MindEarth - mobility - missing elements.pdf](https://github.com/eurodatacube/eodash/files/10720592/MindEarth.-.mobility.-.missing.elements.pdf)
[MindEarth - mobility - missing elements.docx](https://github.com/eurodatacube/eodash/files/10720591/MindEarth.-.mobility.-.missing.elements.docx)

**Comment by lubojr** [comment]
@patrick-griffiths Just as a clarification, we currently use different colorscale (discrete instead of continuous and with different colors) than in the documents that we have received and that are attached here.

Document uses Spectral_r, while we use the one defined in this issue.

Should I recreate images of those legends according to our used colors? We have already existing script for that, so it should not be much work. Please confirm. Thanks

**Comment by patrick-griffiths** [comment]
@lubojr 
ok - i was not aware that we are using discrete..
Pragmatic solution: grab the classification from the above PDF? We certainly need this information (with units) and asking Mindearth again will take too long...

**Comment by lubojr** [comment]
-> received confirmation that no rescaling, conversion or aggregation on our end was done while ingesting the JSONs to geodb, so I expect the values to be "true" 

users_count is really number of people, and I would create legend 0-500
users_density is really number of people/km2  would create legend 0-200
duration is in seconds, so I would use the stretch 0-3600 (0h - 60 minutes) and create a legend

**Comment by ubi15** [comment]
Hi Lubomir,
Regarding the population density: you were working on a non-calibrated preview of the data. The dataset contained the raw counts of the people observed in each area, thus accounting for a few percent of the total population.

I have now uploaded to the eox-gtif-data s3 bucket under the MINDEARTH/population_presence/Austria_December_2022 the updated version of the human presence data for December 2022, featuring a preliminary calibration.
These data should replace all the previously shared population data figures.

I report here the loglog Probability Density Functions of the number of people and density (pp/km2) for each (area, hour). 

![image](https://user-images.githubusercontent.com/3873512/218552314-1e2737e6-ddc8-4a9a-9b1d-50a334550117.png)

As you can see, we are now within the foreseen value ranges for population density and count.

Regarding the trajectories data, also in this case you only have preliminary data that have not been calibrated w.r.t. the real commuting volumes. That is, the current figures are much lower (in terms of traj counts) with respect to the real values ranges, which will be matched once we will share the preliminarily calibrated data (which should be done by this Thursday).

However, you are right about the trip duration: I completely missed the minute scales. In the current data, distances are in meters and duration in seconds, while I will convert these indicators to minutes and km when uploading the updated trajectory data.

Feel free to let me know if you need any other info or details.

**Comment by ubi15** [comment]
One comment: within the human mobility patterns tab we do not display the number of trajectories (under the `n_trajectories` field in the feature properties in the json).

**Comment by lubojr** [comment]
The population density and count is now updated to use calibrated data and reconfiguration to use log scale was done.

As per human mobility patterns - yes we have disabled `total distance` and `n_trajectories` for the sample data. We will enable it with the new data once we receive them.

**Comment by ubi15** [comment]
We uploaded on `eox-gtif-data` under the `/MINDEARTH/trajectories_on_edges/Austria_December_2022` node the updated files.

Some changes have been performed, specifically:
- we removed the `duration_real` and `speed_real` indicators as they make no more sense on per-edge statistics (they simply are the speed-limit and the street length / speed-limit, respectively);
- the congestion index is now a per-cent score between 0 and 100 indicating the relative decrease of the hourly average speed observed w.r.t. the median speed observed on the trimester on that street edge;
- we changed colorbars and data descriptors accordingly, see the document attached to our email.

The data linked to each edge are now like the following:

```
"parameters": {
        "n_trajectories": 0,
        "distance": 0,
        "duration": 0,
        "motorized_share": 100,
        "speed": 56.03
        "congestion_index": 0
      }
```

The colorbars to change are:
- Trajectories count:
    - linear / log

![Image](https://user-images.githubusercontent.com/3873512/221546437-eda2543e-904b-442a-997a-c6af3ea8604e.png)

![Image](https://user-images.githubusercontent.com/3873512/221546323-c9bd4f1c-2a26-4f96-8d27-b92988945825.png)

- congestion index

![Image](https://user-images.githubusercontent.com/3873512/221546656-6e435895-7977-4099-a687-b7ed397635df.png)

- trip distance

![Image](https://user-images.githubusercontent.com/3873512/221546855-b5adb5a1-1cf1-40a1-a8a9-25e67e60c4c1.png)

- motorized trips share

![Image](https://user-images.githubusercontent.com/3873512/221546979-6eb93170-6511-4f4d-902c-94006f28fc14.png)


Please let us know if you need any other info or details.

**Comment by santilland** [comment]
Updated data and provided colormaps have been integrated in client, closing the issue, if any other changes are needed i would propose to open a new issue

**Comment by ubi15** [comment]
I am reopening this to give some feedback on indicators and legends.
@santilland feel free to move to a new issue if preferred.

Some indicators in the human mobility patterns tab still have the wrong naming. The field <-> name mapping should be:
   - `n_trajectories`: Trajectories Count
   - "distance": Trip distance
   - "duration": Trip duration
   - "motorized_share": Congestion Index
   - "speed": Trip average speed
   - "congestion_index":  Motorized trip share index

Then, the legends/colour bars of the population count/density indicators are not updated when passing from one aggregation level to another.

**Comment by ubi15** [comment]
I am bumping this up as the "Human Mobility Patterns" panel still shows the wrong indicators' names.

Also, the MindEarth logo is missing from the trajectories panel.
