### ISSUE TITLE
[mobility] update color ranges

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1940]
current color ranges for the mobility data (aggragated and trajectory) are counterintuitive. 
I propose the below one: 

![Image](https://user-images.githubusercontent.com/40148967/215104021-6a574c9a-1f31-4917-9e9a-0d1a44228256.png)

colorRange = [
  [1, 152, 189],
  [73, 227, 206],
  [216, 254, 181],
  [254, 237, 177],
  [254, 173, 84],
  [209, 55, 78]];

**Comment by santilland** [comment]
Created the issue in parallel, closing the other one https://github.com/eurodatacube/eodash/issues/1939 in favor of this one
