### ISSUE TITLE
GDPR compliance issues for beta release

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1941]
With the beta release under https://gtif.esa.int/ 
we need to ensure that we are GDPR compliant (according to requirements by ESA DPO). 

Fabrizio Pera is kindly supporting us with this. 

He looked at the current status at the above URL and noted the following points that need to be addressed: 
-	On the homepage the Privacy notice and cookie notice link to wrong pages, please, tell to the developers to update it.
-	There is the need to update the Privacy Notice, the ESA WEB analytics Cookie notice is already good as it is (just update reference to race.esa.int with gtif.esa.int).

**Comment by patrick-griffiths** [comment]
@Schpidi and @santilland 

we need to move ahead with the GDPR compliance for the ESA DPO for the beta release.. 
I know there many things you are working on but it would be good if this one could be resolved quickly...

**Comment by lubojr** [comment]
@patrick-griffiths I had a look at review of the links in this issue and for two of them not accessible anymore, I can not find a replacement: 

(i) for data contributed under the Copernicus Contributing Mission scheme https://spacedata.copernicus.eu/documents/20126/0/CSCDA_ESA_User_Licence_last_uploaded_2020_02_10.pdf/b879907e-bd00-688e-bf42-bf27a00d70cb?t=1581335391752

(ii) for data contributed under the ESA Earthnet Third Party Missions scheme - https://earth.esa.int/pi/esa?type=file&amp;table=aotarget&amp;cmd=image&amp;alias=TPMterms 

I was not able to quickly find the new URL links. Please, do you maybe have a pointer to the links, which should replace these?

**Comment by lubojr** [comment]
new working URLs and special t&c and privacy notice to gtif_staging in https://github.com/eurodatacube/eodash/commit/221c982fda6f2443cfd983c6bbc1b484a64aeb51

@patrick-griffiths can this be closed?

**Comment by patrick-griffiths** [comment]
@lubojr thanks this looks very good, I have asked Fabrizio to take a look and confirm...

**Comment by patrick-griffiths** [comment]
@lubojr  see below response from Fabrizio

[11:26] Fabrizio Pera
Hi Patrick, maybe the staging version is not yet released, as in the demo I see the old links

[11:27] Fabrizio Pera
the new ones should be https://gtif.esa.int/privacy and https://gtif.esa.int/privacy#esa-web-analytics-cookie-notice

[11:28] Fabrizio Pera
BTW we still need to updated the text of the privacy policy

**Comment by patrick-griffiths** [comment]
@lubojr quick update here: 

if we click on: https://gtif.esa.int/privacy 
it links to: https://gtif.esa.int/privacy
rather than: https://gtif.esa.int/privacy

Could you fix this please?

**Comment by lubojr** [comment]
> @lubojr quick update here:
> 
> if we click on the "privacy notice" button on the landing page footer it links to: https://www.esa.int/Services/Terms_and_conditions rather than: https://gtif.esa.int/privacy
> 
> Could you fix this please?

@patrick-griffiths 
Ah, good catch. Thanks for reporting. I changed these two links in `gtif_staging` branch in https://github.com/eurodatacube/eodash/commit/d3df86835f99a2e0ecae9747ca5f41c583c8d7a6. The demo that you have looked at is from deployed branch gtif-demo and there the changes will appear once we consolidate other features with it, so later today.

The previous changes (initial one commit from https://github.com/eurodatacube/eodash/commit/221c982fda6f2443cfd983c6bbc1b484a64aeb51) are already now in `gtif-demo` but the new change can not be ported to this branch right away.

**Comment by lubojr** [comment]
Was deployed even to demo already.

@patrick-griffiths Could you please check current state? Feel free to close this issue if OK.

**Comment by patrick-griffiths** [comment]
@lubojr 

there is still an issue, in the landing page footer: 
- when we click on privacy notice, we get taken to the "terms and conditions" page
- when we click on cookie notice, we get taken to the "PRIVACY NOTICE AND CONSENT FORM"

Also I noticed that when we reach either of those pages, the URL does not change, but still shows gtif.esa.int instead of (...)/privacy_notice or similar.. See screenshot below



![Image](https://user-images.githubusercontent.com/40148967/216547038-82d2317e-cc8b-4a81-8614-a04f6427f484.png)

**Comment by lubojr** [comment]
Thanks for the review. Above issues were just fixed by @spectrachrome  and deployed.

**Comment by patrick-griffiths** [comment]
thanks @lubojr the links now point to the right resources,

but the text of the privacy notice still needs to be updated, according to the information that is being tracked.
@Schpidi this is the email thread with Fabrizio Pera and the attached doc...

**Comment by lubojr** [comment]
@patrick-griffiths As I was outside of the email loop, could we please coordinate the discussion regarding content of privacy.md for gtif here? 
I have received a forwarded email with the latest version of the doc from Stephan along with his comments. Should I just take the latest state of the document, convert it to markdown and push it to a new branch in this repo?

**Comment by patrick-griffiths** [comment]
@lubojr almost done here:

Please replace the PRIVACY NOTICE AND CONSENT FORM at https://gtif.esa.int/privacy
with the text from the below document (excluding the table of content) but leaving the ESA WEB analytics Cookie notice as is..
 
[SERCO_ServiceRequest_GTIF_Griffiths.docx](https://github.com/eurodatacube/eodash/files/10695909/SERCO_ServiceRequest_GTIF_Griffiths.docx)

**Comment by lubojr** [comment]
@patrick-griffiths This does not seem like the correct document. Could you please check?

**Comment by patrick-griffiths** [comment]
@lubojr  indeed sorry for that, correct file now below: 
[GTIF PRIVACY NOTICE v02-web.docx](https://github.com/eurodatacube/eodash/files/10709589/GTIF.PRIVACY.NOTICE.v02-web.docx)

**Comment by lubojr** [comment]
Thank you! Updated.
