### ISSUE TITLE
Create concept for demonstrator mode for conferences

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1955]
The goal is to provide a mode of the dashboard that works great for big touchscreen in a demo area.
Things to consider probably are:

- having an entry point showing at a glance some attractive information the user inviting the user to interact
- being able to return to that entry point from anywhere (when a user stops using the device and another user wants to see what the tool is about)
- no keyboard inputs should be expected

**Comment by Schpidi** [comment]
the second point could even be an automatic reset after a configurable time of inactivity

**Comment by lubojr** [comment]
Solved by demo mode
