### ISSUE TITLE
[renewable] add "Ruggedness Index" as additional constrain variable

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1961]
The Ruggedness index was delivered by DHI a while ago and should have been ingested in the S3: 
RuggednessIndex_Austria_WGS84_COG.tif

It should be added as an additional filter variable, only for the wind energy tools, the data descriptors etc have been provided... 

It allows the expert user to exclude areas where the RIX is high and thus WPD is less reliable. 
@kegro can confirm

**Comment by santilland** [comment]
Ruggedness index has been added as filter parameter to wind energy
