### ISSUE TITLE
Mobility transition 

### ISSUE THREAD

**Issue by DanGasb** [eurodatacube/eodash#1989]
- [x] Please group air quality and mobility datasets  in the menu (i.e. ARI, PM10,PM2.5,NO2,Innsbruck hot spot (concentrations), Innsbruck hot spot(emissions),Human mobility, Dynamic human presence)
- [x] Replace "Aggregated Health Risk Index (ARI)" with "Health Risk Index (ARI)" in the menu
- [x] Innsbruck hot spot surface NO2 concentrations --> add the units in the plot (ppbv)
- [x]  There are no units/colorbar for the mobility data (i.e. human presence and mobility pattern)
- [x] When the user zoom over specific area allow the possibility to select different variables remaining at the same zoom level
- [ ] Improve the quality of the isoline in "Innsbruck hot spot- surface NO2 emissions......."

**Comment by lubojr** [comment]
> * [ ]  Improve the quality of the isoline in "Innsbruck hot spot- surface NO2 emissions......."

Could you please explain this point? 

- Improve quality of isolines, in what way?

**Comment by lubojr** [comment]
> * When the user zoom over specific area allow the possibility to select different variables remaining at the same zoom level

Fixed nowthat choosing different admin feature is not needed anymore to trigger custom chart after selecting different data variable from dropdown list

![image](https://user-images.githubusercontent.com/19269667/218274099-de2f23dc-03d5-4702-893f-ab98bda26086.png)

**Comment by DanGasb** [comment]
Regarding the isolines I was referring to improve the graphical quality if possible
![iso](https://user-images.githubusercontent.com/117925117/218422908-e565c219-6c3f-4464-b405-c79acd1f9cc2.PNG)

**Comment by lubojr** [comment]
Having a quick look at the style used for generating the contours, it seems to me that we are using the original raster data resolution (1,5m x 1.5m) to render if a pixel has a color or not. We do not convert the raster data to vectors under the hood (to allow indefinite zooming in and still maintain the possible sharpness.

I am afraid we can not fix this one easily without rethinking how he approach the data to be presented. Here I would wait for @santilland to give more insight.

**Comment by DanGasb** [comment]
ok, no problem for the moment. Maybe in the future we can think about it.

**Comment by lubojr** [comment]
Closing this issue as a followup for flux data visualization was created

**Comment by santilland** [comment]
See https://github.com/eurodatacube/eodash/issues/2037
