### ISSUE TITLE
List of AOI not displaying properly

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1991]
cc: @aapopescu @dmoglioni 
**Describe the bug**
On race dashboard the search doens't display all AOI

**Desktop (please complete the following information):**
 Chrome

**Steps to reproduce**
Access the race dashboard. in the search enter flying. A scrolling windows will appear, but not all the AOI are displayed. last one is OSLO but for example Rome is missing

**Expected behaviour**
I sould be able to scroll all the AOI.

**Screenshots**
![image](https://user-images.githubusercontent.com/65602207/217294342-bcaa9e38-1ffa-4c90-ae8b-a553ad16459d.png)

**Comment by lubojr** [comment]
Connected to the overall search functionality problems. Will be investigated.

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
