### ISSUE TITLE
Statistics selection for sustainable cities datasets

### ISSUE THREAD

**Issue by slumnitz** [eurodatacube/eodash#2008]
Klick

![Image](https://user-images.githubusercontent.com/35147471/217835293-4ced0da1-acb6-4f7b-a35b-5c502f00ed3c.png)

Definition of information needed with statistics selection per Zaehlsprengel:

Displayed aggregated statistical information:

mean land surface temperature (2021): 39 degrees C - nice to have
Existing GR area: 20 m2 - must
Suitable GR area: 40 m2 - must
Unused Potential Area for GR: 50 % - must to nice to have

![Image](https://user-images.githubusercontent.com/35147471/217835264-8015190d-931e-4b93-9737-6f4961c3c8e4.png)

displayed scatterplot is indicating where the Zeahlsprengel is compared to other Zaelsprengel of this city.

Updated as indicated in https://github.com/orgs/eurodatacube/projects/3/views/2?pane=issue&itemId=12099405

**Comment by lubojr** [comment]
@slumnitz @patrick-griffiths 

As a first draft of summary statistics functionality, I have now enabled this aggregation of Green Roofs over ZSP. It is currently not possible for me to additionally configure it to get statistics after drawing a custom area from our geodb unfortunately, so this stays as a future enhancement.

Is the current aggregation like it is now meaningful ? I was not exposed to these data yet before.


variable|aggregated value
-- | --
Mean Land Surface Temperature (2021) | 41.2 degrees C
Total Roof area | 17974 m²
Existing Green Roof area with a slope < 9 degree | 1628 m²
Existing Green Roof area with a slope ≥ 9 and < 15 degree | 2093 m²
Existing Green Roof area with a slope ≥ 15 and < 20 degree | 0 m²
Unused Potential Area for Green Roof | 79.30 %

The Unused potential Area is computed as `1 - (grpotare9 + grpotare15 + grpotare20) / roofArea) * 100;`

Is there any meaningful aggregation also to be configured for Solar roofs?

**Comment by lubojr** [comment]
@slumnitz @patrick-griffiths Amazing, thanks for a review. Yes, this should be feasible to do. Will let you know on progress.

**Comment by lubojr** [comment]
@slumnitz @patrick-griffiths Green roofs statistics of all zsp for a one or more gemeinde have been integrated to gtif.esa.int. Please have a look if okay.

The solar roofs currently do have neither aggregated statistics nor a correct scatter plot. How should we proceed there?

**Comment by lubojr** [comment]
After discussion of @santilland and @FranLeonelli - decided to implement statistics of solar roofs potential vs existing.

In data we have:
```
"pvpotentl": 1,
"pvexisting": 0,
```

**Comment by lubojr** [comment]
@FranLeonelli @Patrick1G @santilland

We have implemented the statistics table and gemeinde-level aggregation chart for solar roofs as well. It displays total area of potential solar roofs (x-axis) vs existing solar roof area (y-axis). 
We have also fixed the computation of the green roof area, so that it behaves the same as above.

Prepared a PR on a testing branch https://gtif-testing.eox.at/ui-panels-cat-roofs-stats-chart/. Please confirm if we can merge the branch and close this issue.

![image](https://github.com/eurodatacube/eodash/assets/19269667/9ef38e4a-d013-41ef-ad10-e9685e3f875a)

Thank you!

**Comment by santilland** [comment]
Ok from @Patrick1G and @FranLeonelli during biweekly, ready to merge.
Look into adding a diagonal line information (create new issue?)

**Comment by santilland** [comment]
Look into adding ZSP name in feature selection overview

**Comment by santilland** [comment]
Reviewing the information available for Zählsprengel it seems that some might have actually a name, but most don't.
"Eine Namensbezeichnung der Zählsprengel ist nicht allgemein erfolgt: Zählsprengel in Wien und anderen Städten werden nur durch ihre Nummern bezeichnet.[[1]](https://de.wikipedia.org/wiki/Z%C3%A4hlsprengel#cite_note-zael-1) Wo es systematische Zählbezirke gibt, sind meist nur diese benannt."
Neither the statistikal austria dataset nor the [STAT Atlas](https://www.statistik.at/atlas/?mapid=topo_regionale_gliederung_oesterreich&layerid=layer5) have Zählsprengel names.
Statistics for different administration levels is being discussed in this issue #2576 
Added enhancement idea of diagonal line as new issue #2578
Closing this issue
