### ISSUE TITLE
GTIF scrollytelling improvements and evolution

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#2034]
This issue is intended as a place to pool ideas for improvements regarding the scrollytelling functionality. Once we agree on certain tasks described here, we can create dedicated individual issues for them.

## Improvements

- [ ] Whitespace: the current setup adds enough whitespace to make it somewhat usable on multiple different screen aspect ratios. In order to provide a truly optimized experience, we would need to consider adding specific rulesets for each screen aspect ratio.
- [ ] Mobile view: mobile view display is generally implemented, but for sticky left / sticky right sections we would need to either come up with a design to move text in front of the image/video/map (which would hinder image readability or video/map interactivity), or have a totally different content structure on mobile than we have on desktop. Both of these approaches probably need some update of the actual content as well.
- [ ] Video scrubbing: the current usage of video scrubbing is the easiest to implement and manage, but for performance reasons, it might be a good idea to consider exporting individual frames as jpgs. On the other hand, this would mean more data volume transferred to the user. A separate approach for mobile and desktop could be necessary here.
- [ ] Minor: EO Adaptation Services text should be wider than 30% width -> should be same as Carbon Accounting

## Evolution

- [ ] Figure captions for images and videos
- [ ] New layout block, such as full screen (width & height!) images overlayed with text
- [ ] Scrubbable maps, or one map that moves and blends in/out layers on scroll (note: interaction only via scrolling, not clicking/hovering!)
- [ ] Scrubbable charts (note: interaction only via scrolling, not clicking/hovering!)
- [ ] General review of the story contents to tell more appealing "stories" making use of scrollytelling functionalities. Currently, most stories could be easily replaced by a very simple static website.

**Comment by santilland** [comment]
Scrollytelling is being redesigned as markdown based concept, i copied over evolutions that i think still apply to the issue here https://github.com/EOX-A/EOxElements/issues/869
Closing this issue as further evolutions of this approach is not planned
