### ISSUE TITLE
Possible race condition in FilterControls

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2035]
There are occasional issues with wind energy and enabling one of the filters (protected areas), the filter is not applied on first load.
It works afterwards to switch to another indicator and back. Other filters, which were by default already enabled are working fine.

I could not replicate it anywhere on browserstack under any configuration, so it could be some race condition? Further investigation needed.

**Comment by jamesemwheeler** [comment]
This or a similar issue is happening with the Wind Energy Distance to Settlements Austrain Cadaster layer, whether another indicator is switched to or not.


https://github.com/eurodatacube/eodash/assets/18290330/b05cfc44-d5f4-4aa8-9e25-9742317fd1e6

**Comment by lubojr** [comment]
Should be now fixed by resetting the source
