### ISSUE TITLE
Possible improvement of isolines visual quality

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2037]
Used in Innsbruck hot spot- surface NO2 emissions

![Current](https://user-images.githubusercontent.com/117925117/218422908-e565c219-6c3f-4464-b405-c79acd1f9cc2.PNG "Current")

https://github.com/eurodatacube/eodash/issues/1989#issuecomment-1427625595

Having a quick look at the style used for generating the contours, it seems to me that we are using the original raster data resolution (1,5m x 1.5m) to render if a pixel has a color or not. We do not convert the raster data to vectors under the hood (to allow indefinite zooming in and still maintain the possible sharpness).

**Comment by santilland** [comment]
If we want to maintain dynamic rendering of isolines done on the client, i don't think there is much we can do. If the visual style of the isolines is more important, we can ingest the data into SH and use WMS endpoint access server side rendered nice tiles.
I will close the issue for now, if we want to do server side rendering let us open a new issue.
