### ISSUE TITLE
Geodb migration for E13d and E12c

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2040]
Complete migration of the truck detections and flying airplanes

**Comment by lubojr** [comment]
We have already received data tables reference for E13d, we just need to reconfigure the client and check how we fetch dates for individual dates for the map.

**Comment by lubojr** [comment]
I am confirming that the E13d detection now are as expected (as were before in geojsons) and we have removed the geojsons for E13d from the eodash repository, which has cut down the repository size and mainly number of individual files needed to be pushed to s3 during each commit significantly! Change is already visible in staging.

With the migration of E13d detections to geodb, we have additionally been able to fix the few minutes difference between adjacent scenes and corresponding detections and we are merging them now on the client - this results in less individual time entries (for example 2021-01-01T13:51:00 and 2021-01-01T13:52:00 are now merged and it works as expected).
