### ISSUE TITLE
Implementation of new layer management concept

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2069]
To consider:

- **main goal** -> allow comparison / orverlay of different "indicators"/datasets 
- change transparency
- reordering of layers?
- have close button

**Comment by patrick-griffiths** [comment]
**hierarchy of layers:** 
1) key science products (e.g. WindPowerDensity) - interactive tools run computations on these
2) indicators and ancillary products (e.g. WorldCover) - to understand context, and include in analyses (e.g. scatterplots)
3) baselayer/maps (e.g. Geoland Basemap Gelaende)  - pure visualization support

@patrick-griffiths to provide matrix view which basemaps and products should be exposed in which domain tools

**Comment by santilland** [comment]
Approach of layer management has been discussed as part of UI redesing concept.
List of layers has been sent, layer/data matrix to be created by @patrick-griffiths team

**Comment by patrick-griffiths** [comment]
@santilland any testing branch for this?

**Comment by santilland** [comment]
No, there is no testing branch for this

**Comment by santilland** [comment]
Approach and concepts have been discussed, implementation of modular tool has started, integration needed. Will rename issue to implementation of new layer management concept

**Comment by lubojr** [comment]
The layer management concept has been integrated. Custom layer is used as a mechanism to freeze a filtered layer to provide it as auxiliary layer for other datasets. Can we close this issue?
