### ISSUE TITLE
N3a2 new POI in Danube delta

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2075]
Create a new configuration for `N3a2` -> Bulgaria Danube delta

**Comment by AlessandroScremin** [comment]
@lubojr  sorry it was romania not bulgaria
Create a new configuration for N3a2 -> Romania Danube delta

**Comment by aapopescu** [comment]
> @lubojr sorry it was romania not bulgaria Create a new configuration for N3a2 -> Romania/Ukraine Danube delta

:) The Danube Delta is in fact only in Romania.

**Comment by lubojr** [comment]
added in https://github.com/eurodatacube/eodash/commit/b9b61753f35d21ae02f661d9e76fb66f595e28f2
