### ISSUE TITLE
support data input from the API provided by NASA

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#208]
example would be the car-count from this endpoint https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/sites/be/

**Comment by Schpidi** [comment]
thanks @olafveerman for the updates via mail.

the new api allows to discover new data like for example for San Francisco from https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/datasets/sf

more information at https://github.com/NASA-IMPACT/covid-api/releases/tag/v0.2.0

**Comment by Schpidi** [comment]
The [file to generate the internal cache](https://github.com/eurodatacube/eodash/blob/staging/app/public/generate_files.py) has recently been updated to support using the GeoDB to retrieve the values for individual indicators. The idea would be to extend the script to also support retrieving values from the NASA API for relevant data instead of using intermediate CSV files like for [E8](https://github.com/eurodatacube/eodash/blob/staging/app/public/generate_files.py#L301).

**Comment by lubojr** [comment]
Closing for now. Put on Hold
