### ISSUE TITLE
Implement selection for Hydropower

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2094]
Should the selection still be based on administrative zones, or should selection of individual features (lakes/dams/...) be possible?

**Comment by patrick-griffiths** [comment]
no relevance of admin zones for the hydro analyses. 

but we have all the geometries for all hydro reservoirs in Austria

**Comment by patrick-griffiths** [comment]
@santilland 
reuse "RACE POI cluster selection" functionality

**Comment by santilland** [comment]
new issue created #2120 for implementing this functionality, closing this
