### ISSUE TITLE
Point of interest visualisation 

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#21]
### Environment
**Operating system:** MacOS

**Affected browser:** Safari 12

### Steps to reproduce:
Zooming in to the various AOI or point of interests

### Expected Behaviour:
A more direct way accessing the AOIs would be more intuitive - in the moment your need to click 2-3 to actually arrive at an indicator on the map, if it is part of a cluster. Also once you choose one indicator the map zooms automatically out to Europe so if you want explore the other indicators of the cluster you have to zoom in again.

### Actual Behaviour:
see above

### Comments:
No comments

**Comment by silvester-pari** [comment]
I believe this has now improved with the current approach. The user has the option to select a country as the first filter and then click through the indicator filter to see where an indicator is available. When the user chooses to return to the country overview, the user only needs to clear the indicator filter (either click on "all indicators" or close the indicator filter chip) and sees all indicators for that counry.

The clicking 2-3 times in clusters is currently the only way to do it in my opinion, not sure how to improve this.
