### ISSUE TITLE
Implement slider for time selection

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2100]
I think the effort/usability gain should be evaluated here. Would this only be for mobility data?
The current main goal is to merge mobility data and air quality data, for this the mobility data needs to be aggregated daily instead of hourly, does the timeslider make also sense for this?

**Comment by santilland** [comment]
After discussion initial approach will be to allow configuration if the time dropdown selection is visualized as slider.
It should be configurable per indicator which one should be used, defaulting to the dropdown selection.
Slider could use index and full steps and show currently selected datetime as label.

**Comment by patrick-griffiths** [comment]
just one more example where this continues slider would be useful is the local emission hotspot in innsbruck: 
https://gtif.esa.int/explore?x=1268101.45883&y=5984981.66732&z=15.59066&poi=AT-AQ2

And in principle for all the long AQ time series (daily and 14-days) e.g.: 
https://gtif.esa.int/explore?x=1252236.47093&y=5975820.54139&z=12.93623&poi=AT-AQ5

And as mentioned before the ADO has a nice example of such a slider: 
https://ado.eurac.edu/

**Comment by spectrachrome** [comment]
Thank you Patrick, will consider this information when I configure the indicators. We are already taking quite some inspiration from the Alpine Drought Observatory, in particular the slider ticks which nicely visualize the number of time entries.

**Comment by patrick-griffiths** [comment]
Some motivation for this new type of continuous slider: 
	
The “event action” statistic show that the indicators with most event clicks are e.g. Human Mobility Patterns (SOL1) and AQ parameters (ARI, PM) (AQ4) –-> all of these have many layers/long time series and require many many clicks to visualize or explore! The continuous slider would remove all those clicks and make this metric more meaningful:  

![Image](https://github.com/eurodatacube/eodash/assets/40148967/f7edaa26-610c-4cdf-86f3-5d156e4e8f94)

**Comment by spectrachrome** [comment]
Maybe we should also show dedicated tick marks for months or years in addition to the continuous bar to make the time range a bit easier to comprehend. In this case they should be visually distinctive so they are easily distinguished from the original ticks.

**Comment by santilland** [comment]
I think we could merge the functionality now, test deployment under:
https://gtif-testing.eox.at/time_slider/
I activated the time slider for the datasets i think makes most sense, it is in any case configurable.
@patrick-griffiths please let me know if we should move this to the demonstrator.

**Comment by patrick-griffiths** [comment]
@santilland great Daniel nice to see. Fine to integrate into the demonstrator. 

A small improvement could be to reduce the overall size by ~a third.. Especially the height is taking up quite some space...

**Comment by santilland** [comment]
Great! I will be merging to the demonstrator for now. 
As for the improvements, i will create another issue to keep track on things and be able to close this overall implementation goal  https://github.com/eurodatacube/eodash/issues/2288
Will be closing this issue once merged
