### ISSUE TITLE
Review current UI design

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2103]
Create user wokflow concepts for mobile and desktop of possible menu and design improvements

**Comment by santilland** [comment]
important to consider initial discussion from #1839 
@mariangela-cataldo

**Comment by mariangela-cataldo** [comment]
Link to preliminary reviewed UI proposal on Figma: https://www.figma.com/file/0N19VKjFrDZC718tVzGORG/GTIF-UI-desktop-and-mobile?node-id=0-1&t=8P9uCNPsdyo4xWiv-0

@santilland @silvester-pari

**Comment by lubojr** [comment]
The UI redesign has been finished. Can we close the issue and create follow-up improvement as separate issues?
