### ISSUE TITLE
Updated calibrated human mobility data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2109]
Important is to keep versioning of data to help keep track of changes

**Comment by patrick-griffiths** [comment]
@santilland pls note the update from ME here: 

By March 24th 2023:
-	Calibrated population data from Jul. 2021 to Dec. 2022
-	Trajectories: definition of models to classify transportation mean modalities (motorised/non-motorised, ASFiNAG data might help)
-	Trajectories: delivery of data from Jul. 2021 to Dec. 2022 with trajectories distance, duration, average speed and congestion index calibrated. The trajectories count and motorization indicators’ calibration will have to be completed with further comparison with ground truth data yet to be obtained (see above for the ASFiNAG data, we requested access to them but we did not receive any reply yet).

**Comment by patrick-griffiths** [comment]
By end of April 2023:
-	Re-calibration of data taking into account 2020 anomaly;
-	Delivery of calibrated population data from Jul. 2019 to Jun. 2021 (to complement the previously-delivered data);
-	Trajectories: delivery of data from Jul. 2019 to Jun. 2021;
-	Final calibration of trajectories count and motorised share for the whole July 2019-December 2022 period.

**Comment by santilland** [comment]
Data should have been received, at least no more updates for this data are expected, closing issue
