### ISSUE TITLE
OC_Water quality MAPS reprocessed by CNR

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2114]
CNR reprocessed the CHL and the TSMNN maps.

Here the new layers ID

AWS_N3_CUSTOM --> 7db8e19e-bf12-4203-bdd1-673455647354
AWS_N3_CUSTOM_TRILATERAL --> 7db8e19e-bf12-4203-bdd1-673455647354
AWS_N3_CUSTOM_TSMNN --> 698ade22-bc30-44d1-8751-159ee135f998
AWS_N3_CUSTOM_TRILATERAL_TSMNN --> 698ade22-bc30-44d1-8751-159ee135f998

**Comment by lubojr** [comment]
fixed by 1334fd8cdd385e02be58e8cf359d587d26ce59a3 - updated dates from new collections and unified referenced
