### ISSUE TITLE
New Indicaotr from CNR: SST

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2116]
CNR provided a new indicator over the same 4 AOI of the water quality

here the datails for reaching the layer

ID:AWS_VIS_SST_MAPS
92780d01-126f-4827-80f8-4e561dd8e228

follow the evalscript
//VERSION=3
function setup() {
  return {
    input: [{
      bands: ["sst", "dataMask"], // this sets which bands to use
    }],
    output: { // this defines the output image type
      bands: 4,
     sampleType: "UINT8"
    }
  };
}

function evaluatePixel(sample) {

   var arr = colorBlend(sample.sst,
[0,5,13,20,28,35], 
[[40,130,180,255],
[170,220,160,255],
[255,255,150,255],
[255,170,100,255],
[210,25,25,255],
[128,0,0,255]
]);   
  if (sample.dataMask===0) {  return[0,0,0,0];}
  else { return arr;
}
}

**Comment by lubojr** [comment]
@AlessandroScremin @aapopescu should I also define the "customAreaIndicator" for these AOIs? We were deliberately not putting it on `water quality` ones, but how about sst?

**Comment by lubojr** [comment]
I have integrated the SST maps as N3a2 indicator (parallel to water quality regional maps) in https://eodash-testing.eox.at/sst-maps-03-2023/ for both trilateral and eodash the same way.

it allows drawing of customAreaIndicator to get statistics and shows the colorscale from above stated values

However, upon random checking of the POIs, the values seem very off to be honest. Both in terms of going far below 0°C in mid summer and by going over 80°C in Danube delta. @AlessandroScremin Could you please double check the data/nodata value or so?

cc @aapopescu

**Comment by lubojr** [comment]
@AlessandroScremin Thank you for the confirmation! I shall then update the legend and descriptions accordingly.

**Comment by lubojr** [comment]
@AlessandroScremin Sorry for delay coming back to this topic. If the maps are anomaly of temperature, should the color scale range also be adapted to be in range -100 -> 100 like the water quality anomaly? Currently it is in range 0-35.

**Comment by AlessandroScremin** [comment]
@lubojr 
thnaks a lot for pointing this out...

I tried to use a custom color scale...
[-70, -38.32, 0, 33.33, 70]
blue if too cold, green normal and red to high , with two intermediate values...

see if it works

//VERSION=3
function setup() {
  return {
    input: [{
      bands: ["sst", "dataMask"], // this sets which bands to use
    }],
    output: { // this defines the output image type
      bands: 4,
      sampleType: "UINT8"
    }
  };
}

function evaluatePixel(sample) {

  var arr = colorBlend(sample.sst,    [-70, -38.32, 0, 33.33, 70],    [[0,0,255],[0,150,200],[0,154,90],[250,180,120],[255,0,0] ]); 
 // var arr = colorBlend(sample.chl,    [0, 30.5882, 66.667, 86.2745, 100],    [[0,0,0,],[0,0,1],[0,154,87],[251,208,99],[214,130,49] ]); 
  if (sample.dataMask==1)  arr.push(255);
  else arr.push(0);
  return arr;
}

**Comment by AlessandroScremin** [comment]
@lubojr 

I just noticed that from the chart the dates don't match...
example
I have a file

**Comment by lubojr** [comment]
@AlessandroScremin Thank you very much for the report. Yes, indeed there was a mistake in the configuration of the /statistics request to SH (weekly aggregation was set), which created these incorrect dates. Now should be correct
