### ISSUE TITLE
Implement new indicator search and selection panel

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2123]
![Image](https://user-images.githubusercontent.com/4036819/225890402-211bc8f0-7b05-4b70-999b-fe96317fb2f4.png)

**Comment by santilland** [comment]
Implementation is in progress. It is being done as a new eoxelements component [eox-itemfilter](https://github.com/EOX-A/EOxElements/blob/main/elements/itemfilter)

**Comment by lubojr** [comment]
Is implemented and deployed
