### ISSUE TITLE
Total electic power productio potential

### ISSUE THREAD

**Issue by FranLeonelli** [eurodatacube/eodash#2127]
- When selecting “Total electric power production potential - Regular performance” in the text high performance and high efficiency should be changed to regular performance and regular efficiency.
- When selecting “Total electric power production potential - Low performance” in the text high performance and high efficiency should be changed to low performance and low efficiency; and the title should change accordingly.

**Comment by slumnitz** [comment]
@santilland can this be changed to reflect a consistent nomenclature? Thank you!
