### ISSUE TITLE
updating sustainable cities layer name

### ISSUE THREAD

**Issue by FranLeonelli** [eurodatacube/eodash#2128]
In the map layers “GTIF_AT_Rooftops_3857” field should have a more user-friendly name, and updating when a different dataset is chosen, as done in Energy and Mobility domains (for example “Green Roof field”/ “Solar Roof field” or something similar)

![Image](https://user-images.githubusercontent.com/128155309/226322406-d5bc90bb-e489-4e10-bdea-d24bd18da354.png)

**Comment by slumnitz** [comment]
We could name them "green roofs" and "solar roofs"
