### ISSUE TITLE
NO2 model data don't move the map on the city

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2134]
I filter in search for air

I clik on amsterdam NO2 S5P and the map move to amsterdam (OK)
If I click on amsterdam NO2 model, or wherever other city with modelled NO2, I get the chart but the  map does't move to the city

It is clear that there is nothing to show, but would be nice to be redirected to the city of reference in the map.

![image](https://user-images.githubusercontent.com/65602207/226892919-35a76ce0-a2f4-4b55-b2f0-321d1b1ac950.png)

**Comment by lubojr** [comment]
Obsolete due to current locations restructuring coming from STAC Catalog approach.
