### ISSUE TITLE
Inland water story

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2135]
Possible focus is to look at lakes across US/Europe/Asia how level of water has changed trying to link to agriculture.
Potential sources MODIS, Sentinel-2, ...

**Comment by santilland** [comment]
CCI Lakes product identified as candidate - not available as ZARR/COG (available as netcdf)
-> Support from Brockmann/Sinergise for conversion

**Comment by aapopescu** [comment]
stories published
