### ISSUE TITLE
N3a2 Indicator to update title & story

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2136]
Anca to provide info on how renaming should be done

**Comment by aapopescu** [comment]
- full story received from CNR, story update on RACE is in progress

**Comment by aapopescu** [comment]
Data panel updated for SST datasets. The markdown files are in https://github.com/eurodatacube/eodash/pull/2144 

@santilland, can you please check the POIs are correctly created? I cannot see the POIs for SST correctly named. For example, when selecting the Rhone Delta SST maps in the URL the POI appears as RhoneDelta-N3a2 which is the same as for Chl-a. 

cc: @lubojr 




-

**Comment by lubojr** [comment]
Fixed the aoi ids and pushed to staging. Closing.
