### ISSUE TITLE
Explore integration of CDS (copernicus data store) datasets

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2137]
e.g. Wind(U/V) / Surface temperature / and others 
Ingestion into SH would be first step
Anca to look at who to contact

**Comment by aapopescu** [comment]
- contacted ECMWF, pending confirmation

**Comment by aapopescu** [comment]
@santilland , can we consider using directly the CDS API to fetch this data and do the analytics?

**Comment by santilland** [comment]
As far as i can see the CDS API is expected to be used through a python library that helps interact with the service endpoint. It should in theory be possible to directly make requests to their endpoint but i don't think this is really documented or wanted. In a sense we would need to reverse engineer their endpoint.
We would need also one user that would be making the requests, and i also don't think it was intended that a "externally facing" client would be used to make direct requests to this api.
We could develop our own endpoint that proxies requests to their endpoint, but I think this is something that we would need to clarify with the service provider.

**Comment by santilland** [comment]
@AlessandroScremin to investigate prolonging temporal coverage for current layers as well as integration of possible new datasets.

**Comment by AlessandroScremin** [comment]
@santilland @aapopescu 

dataset updated: prolonged the avaialbe time from 1959 to 2022.
