### ISSUE TITLE
Tiny improvements in the presentation of Sust. Cities fields

### ISSUE THREAD

**Issue by FranLeonelli** [eurodatacube/eodash#2138]
**Green Roofs:**
- The “Existing Green Roofs” field needs same title in the page when chosen (which now is “Existing green rooftops”). 
- The “GRExisting” written should be taken off. 
- We should give user friendly labels: 0-1 should be modified in “Non-Green Roof/Green Roof” or similar.

![Image](https://user-images.githubusercontent.com/128155309/227278973-89ca86da-8ed4-41b8-bf48-6fd95029d68d.png)

**PV detections**
- PV acronym should be introduced somewhere
- The "Existing PV Panel" field needs the same title in the page (which now is "PV detections"). Also, since it is the only data layer, maybe we should remove  the choice functionality here. 
- The “PVExisting” written before the 0-1 labels should be taken off. 
- We should give user friendly labels: 0-1 should be modified in “Non PV Roof-PV Roof” or similar

![Image](https://user-images.githubusercontent.com/128155309/227280491-d1583938-032d-42ff-870f-d7d5ff39f3a7.png)

PS. Could it be useful to be coherent among Green Roofs and Solar Roofs, in the sense that we decide if to have separate sub-domains for the "existing" data layers for both or for none of them? (now we have "PV Detections" sub-domain for Solar Roofs, but we keep the "Existing Green Roofs" as a data layer within the Green Roofs sub-domain)

**Comment by slumnitz** [comment]
@santilland yes please go ahead with these minor beauty fixes. 

We could name them "PV Detections" and "Green roof detections"

**Comment by santilland** [comment]
As for:
> PS. Could it be useful to be coherent among Green Roofs and Solar Roofs, in the sense that we decide if to have separate sub-domains for the "existing" data layers for both or for none of them? (now we have "PV Detections" sub-domain for Solar Roofs, but we keep the "Existing Green Roofs" as a data layer within the Green Roofs sub-domain)
Currently there are two different "Solar Roofs" and "PV detections" because we have two separate datasets.
PV detections (and only pv detections) done Austrian wide and all other attributes related inside "Solar Roofs" for the 4 austrian cities.
We will receive an Austrian wide product for these two datasets so the "PV detections" indicator will be removed and be part of the then Austrian wide "Solar Roofs" entry.

**Comment by santilland** [comment]
As explained in previous comment the PV Detections will be removed once the updated data has been received.
Following points have been implemented:

- The “Existing Green Roofs” field needs same title in the page when chosen (which now is “Existing green rooftops”).
- The “GRExisting” written should be taken off.
- We should give user friendly labels: 0-1 should be modified in “Non-Green Roof/Green Roof” or similar.

I would consider the issue closed, please repoen it if you find something is missing
