### ISSUE TITLE
S1 backscatter basemap integration

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#2143]
Could we integrate the EODC S1 global backscatter map as a basemap in GTIF?
It seems to be provided as a WMS: https://s1map.eodc.eu/#47.97539,16.89311,14z

**Comment by santilland** [comment]
Yes, should be possible, to which indicator/tool should we add the base layer @patrick-griffiths ?

**Comment by patrick-griffiths** [comment]
It would be valuable as a general base layer, if we have to pick one, the turbine detection for the energy domain to start with

**Comment by santilland** [comment]
@patrick-griffiths the source has strict cross origin policy, (no CORS headers set) it can't be integrated into the client like this. CORS headers need to be set in the server serving the tiles

**Comment by christophreimer** [comment]
@bschumac to be tagged

**Comment by bschumac** [comment]
@santilland we may possibly be capable of whitelist your servers to grab the tiles. Could you provide us a list of domains that should be whitelisted?

**Comment by lubojr** [comment]
@bschumac Our GTIF client is deployed and accessible under following 3 hostnames" `gtif.esa.int`, `gtif-testing.eox.at` and `gtif-staging.eox.at` but the tiles are fetched by the browser directly, we do not have a proxy server in between.

**Comment by christophreimer** [comment]
@lubojr and @santilland the global backscatter model is available as XYZ service via the following endpoints:

- VV - Polarisation: https://s1map.eodc.eu/vv/{z}/{x}/{y}.png
- VH - Polarisation: https://s1map.eodc.eu/vh/{z}/{x}/{y}.png

Can you please verify and confirm that you can access the service and corresponding tiles with your client app.

**Comment by lubojr** [comment]
@christophreimer I have tried the integration and we are experiencing identical issues as before https://github.com/eurodatacube/eodash/issues/2143#issuecomment-1547349607 ```Access to image at 'http://s1map.eodc.eu/vh/11/1114/712.png' from origin 'https://gtif-testing.eox.at/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by christophreimer** [comment]
@lubojr can you please try again to access the TMS.

**Comment by lubojr** [comment]
@christophreimer The CORS issue seems resolved. Thanks
There is still some integration necessary on our side, but that should be straightforward.

**Comment by lubojr** [comment]
Added as a baselayer available for all datasets.
