### ISSUE TITLE
Update demo configuration for EGU

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2156]
Configration file:
app/src/appConfig.js
Section:
demoMode: {
      egu2023:

**Comment by santilland** [comment]
@silvester-pari to provide info on which branch to work on and links to folders

**Comment by silvester-pari** [comment]
> @silvester-pari to provide info on which branch to work on and links to folders

I described the setup and usage of demo mode in the according PR here: https://github.com/eurodatacube/eodash/pull/2141#issue-1647319307
