### ISSUE TITLE
Integration of the "funding map for fast charging stations" as a new layer

### ISSUE THREAD

**Issue by dischon** [eurodatacube/eodash#2157]
Request for the integration of the AustraTech "funding atlas" map, availabile here: https://files.austriatech.at/f/c4e4baeaf6bd4289adec/?dl=1, as a new layer for the GTIF energy transition domain.

green = already enough fast charging available, grey = funding for new charging stations, white = no relevant street infrastructure

![20230317_110205](https://user-images.githubusercontent.com/129982865/230149916-c7c4e588-7147-4e75-a1d4-7ab313f5800b.jpg)

**Comment by santilland** [comment]
hi @dischon while trying to create the styling for the data it is not clear to us which attribute to use to differentiate the listing you made:
green = already enough fast charging available, grey = funding for new charging stations, white = no relevant street infrastructure
We only see attributes Poly_Typ, Version, and ISO_Typ.
Poly_Typ and ISO_Typ have values like CLC2018 or Gr50_10km, could you clarify which parameter and values should be used to create the 3 different availability information?

**Comment by santilland** [comment]
It seems the colors match the poly_typ:
CLC2018 shown in grey
Gr50_10km shown in green


![Image](https://user-images.githubusercontent.com/4036819/236417960-f93e3a1c-187f-4014-863d-daef83872ea4.png)

**Comment by santilland** [comment]
Ready to be merged to demonstrator, @patrick-griffiths could you please confirm we should add this new layer?

**Comment by dischon** [comment]
Perfect!

Grey means subsidies available

Daniel Santillan ***@***.***> schrieb am Fr., 5. Mai 2023,
11:04:

**Comment by patrick-griffiths** [comment]
> Ready to be merged to demonstrator, @patrick-griffiths could you please confirm we should add this new layer?

Absolutely, yes and it's perfect where it is now among the ancillary layers/basemaps.

It was a key wish from bmk and relatively low effort for you, so great.

BTW this layer will also be interesting in the mobility domain....

**Comment by santilland** [comment]
All clear, layer also added to mobility domain datasets, merged to staging, will be added in next deployment.

**Comment by santilland** [comment]
Layer deployed on demonstrator, closing issue
