### ISSUE TITLE
Change projection in Trilateral

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#219]
-       Change map to cylindrical projection

**Comment by aapopescu** [comment]
Received also this comment via feedback form:

Environment
App version: 2.0.0

Current URL: https://www.eodashboard.org/?country=IN&poi=NorthAdriaticESA-N3a2&indicator=E1

Steps to reproduce:
Correct it as per google map

Expected Content:
As per Google map

Comments:
No comments

**Comment by Schpidi** [comment]
@olafveerman does the api provide the global no2 and co2 data in a different projection than 3857?

**Comment by santilland** [comment]
@aapopescu to provide wanted projection to ask if this projection could be provided by data provider (NASA)
@EOX ask sinergise what projections are supported for COGs?
@lubojr to provide list from API (WMS)

**Comment by lubojr** [comment]
SH: list of available projections on WMS:
```
<SRS>EPSG:3857</SRS>
<SRS>CRS:84</SRS>
<SRS>EPSG:4326</SRS>
<SRS>EPSG:3035</SRS>
<SRS>EPSG:27700</SRS>
<SRS>EPSG:2154</SRS>
<SRS>EPSG:3912</SRS>
<SRS>EPSG:3794</SRS>
<SRS>EPSG:5514</SRS>
<SRS>EPSG:3765</SRS>
<SRS>EPSG:4026</SRS>
<SRS>SR-ORG:98739</SRS>
<SRS>EPSG:28992</SRS>
<SRS>EPSG:3003</SRS>
<SRS>EPSG:3004</SRS>
<SRS>EPSG:3844</SRS>
<SRS>EPSG:3346</SRS>
<SRS>EPSG:2180</SRS>
<SRS>EPSG:31287</SRS>
<SRS>EPSG:3416</SRS>
<SRS>EPSG:2193</SRS>
<SRS>EPSG:3995</SRS>
<SRS>EPSG:3031</SRS>
<SRS>EPSG:32601</SRS>
<SRS>EPSG:32701</SRS>
<SRS>EPSG:32602</SRS>
<SRS>EPSG:32702</SRS>
<SRS>EPSG:32603</SRS>
<SRS>EPSG:32703</SRS>
<SRS>EPSG:32604</SRS>
<SRS>EPSG:32704</SRS>
<SRS>EPSG:32605</SRS>
<SRS>EPSG:32705</SRS>
<SRS>EPSG:32606</SRS>
<SRS>EPSG:32706</SRS>
<SRS>EPSG:32607</SRS>
<SRS>EPSG:32707</SRS>
<SRS>EPSG:32608</SRS>
<SRS>EPSG:32708</SRS>
<SRS>EPSG:32609</SRS>
<SRS>EPSG:32709</SRS>
<SRS>EPSG:32610</SRS>
<SRS>EPSG:32710</SRS>
<SRS>EPSG:32611</SRS>
<SRS>EPSG:32711</SRS>
<SRS>EPSG:32612</SRS>
<SRS>EPSG:32712</SRS>
<SRS>EPSG:32613</SRS>
<SRS>EPSG:32713</SRS>
<SRS>EPSG:32614</SRS>
<SRS>EPSG:32714</SRS>
<SRS>EPSG:32615</SRS>
<SRS>EPSG:32715</SRS>
<SRS>EPSG:32616</SRS>
<SRS>EPSG:32716</SRS>
<SRS>EPSG:32617</SRS>
<SRS>EPSG:32717</SRS>
<SRS>EPSG:32618</SRS>
<SRS>EPSG:32718</SRS>
<SRS>EPSG:32619</SRS>
<SRS>EPSG:32719</SRS>
<SRS>EPSG:32620</SRS>
<SRS>EPSG:32720</SRS>
<SRS>EPSG:32621</SRS>
<SRS>EPSG:32721</SRS>
<SRS>EPSG:32622</SRS>
<SRS>EPSG:32722</SRS>
<SRS>EPSG:32623</SRS>
<SRS>EPSG:32723</SRS>
<SRS>EPSG:32624</SRS>
<SRS>EPSG:32724</SRS>
<SRS>EPSG:32625</SRS>
<SRS>EPSG:32725</SRS>
<SRS>EPSG:32626</SRS>
<SRS>EPSG:32726</SRS>
<SRS>EPSG:32627</SRS>
<SRS>EPSG:32727</SRS>
<SRS>EPSG:32628</SRS>
<SRS>EPSG:32728</SRS>
<SRS>EPSG:32629</SRS>
<SRS>EPSG:32729</SRS>
<SRS>EPSG:32630</SRS>
<SRS>EPSG:32730</SRS>
<SRS>EPSG:32631</SRS>
<SRS>EPSG:32731</SRS>
<SRS>EPSG:32632</SRS>
<SRS>EPSG:32732</SRS>
<SRS>EPSG:32633</SRS>
<SRS>EPSG:32733</SRS>
<SRS>EPSG:32634</SRS>
<SRS>EPSG:32734</SRS>
<SRS>EPSG:32635</SRS>
<SRS>EPSG:32735</SRS>
<SRS>EPSG:32636</SRS>
<SRS>EPSG:32736</SRS>
<SRS>EPSG:32637</SRS>
<SRS>EPSG:32737</SRS>
<SRS>EPSG:32638</SRS>
<SRS>EPSG:32738</SRS>
<SRS>EPSG:32639</SRS>
<SRS>EPSG:32739</SRS>
<SRS>EPSG:32640</SRS>
<SRS>EPSG:32740</SRS>
<SRS>EPSG:32641</SRS>
<SRS>EPSG:32741</SRS>
<SRS>EPSG:32642</SRS>
<SRS>EPSG:32742</SRS>
<SRS>EPSG:32643</SRS>
<SRS>EPSG:32743</SRS>
<SRS>EPSG:32644</SRS>
<SRS>EPSG:32744</SRS>
<SRS>EPSG:32645</SRS>
<SRS>EPSG:32745</SRS>
<SRS>EPSG:32646</SRS>
<SRS>EPSG:32746</SRS>
<SRS>EPSG:32647</SRS>
<SRS>EPSG:32747</SRS>
<SRS>EPSG:32648</SRS>
<SRS>EPSG:32748</SRS>
<SRS>EPSG:32649</SRS>
<SRS>EPSG:32749</SRS>
<SRS>EPSG:32650</SRS>
<SRS>EPSG:32750</SRS>
<SRS>EPSG:32651</SRS>
<SRS>EPSG:32751</SRS>
<SRS>EPSG:32652</SRS>
<SRS>EPSG:32752</SRS>
<SRS>EPSG:32653</SRS>
<SRS>EPSG:32753</SRS>
<SRS>EPSG:32654</SRS>
<SRS>EPSG:32754</SRS>
<SRS>EPSG:32655</SRS>
<SRS>EPSG:32755</SRS>
<SRS>EPSG:32656</SRS>
<SRS>EPSG:32756</SRS>
<SRS>EPSG:32657</SRS>
<SRS>EPSG:32757</SRS>
<SRS>EPSG:32658</SRS>
<SRS>EPSG:32758</SRS>
<SRS>EPSG:32659</SRS>
<SRS>EPSG:32759</SRS>
<SRS>EPSG:32660</SRS>
<SRS>EPSG:32760</SRS>
```

**Comment by olafveerman** [comment]
@Schpidi Missed your original question.

The API only supports 3857 at the moment. We are thinking of building in support for other systems in the future, but it's unclear which ones and when that will happen.

**Comment by lubojr** [comment]
@aapopescu We have investigated if there would be an option to include the raster data in other projection than EPSG:3857. Unfortunately Leaflet does not support on the fly raster transformation, so the coordinate system of the map and of the tile layer need to match. Using the https://github.com/kartena/Proj4Leaflet plugin, we would be able to set the map projection to any configured projection - our suggestion for the cylindrical low-mid latitute would be for example https://epsg.io/6933 but this would still mean that tiles/wms layer would need to be served in this projection for dashboard to consume it.

**Comment by aapopescu** [comment]
@olafveerman , @gmilcinski 
can tiles and wms be served in  EPSG 6933?

> @aapopescu We have investigated if there would be an option to include the raster data in other projection than EPSG:3857. Unfortunately Leaflet does not support on the fly raster transformation, so the coordinate system of the map and of the tile layer need to match. Using the https://github.com/kartena/Proj4Leaflet plugin, we would be able to set the map projection to any configured projection - our suggestion for the cylindrical low-mid latitute would be for example https://epsg.io/6933 but this would still mean that tiles/wms layer would need to be served in this projection for dashboard to consume it.

**Comment by gmilcinski** [comment]
@aapopescu : 
Sentinel Hub does not yet support EPSG:6933 but I am pretty confident that we can add this feature. 
Estimated effort: 2 man-days (implementation, integration, testing)

**Comment by lubojr** [comment]
Closing for now. Put on Hold
