### ISSUE TITLE
Integration of cadaster data as filter for Energy transition Wind Energy

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2196]
Data has been converted and integrated as filter to the client.
Used title, unit, placement to be confirmed.
Data description is needed.
Test branch under:
https://gtif-testing.eox.at/gtif_cadaster/
Please @AlonsoItziar and/or @patrick-griffiths look at the branch and provide feedback if integration in client is as expected and the missing information.

**Comment by AlonsoItziar** [comment]
Here is the feedback: 
1)Placement is correct
2)Title to differentiate between the two distance to settlement laters: 
- Already existing layer (Distance to settlements) - should be replaced with "Distance to settlements WSF"
- New layer (cadaster layer) - should be named "Distance to settlements Austrian Cadaster"

3) Unit on the new cadaster layer (Scale) does not seem right, both layers should represent the same. What is represented by 100m in WSF is equivalent to 10km in the cadaster layer, the cadaster scale should be adjusted 

4) Data description 
Each federal province in Austria has distance requirements between wind turbines and settlements. Increase the minimum distance to select areas further from settlements, you can chose between two distance layers:
- WSF: the distance to settlements is based on the World Settlement Footprint (product obtained from satellite data)
- Austrian Cadaster: the distance to settlements layer is based on the national Austrian cadaster data

**Comment by santilland** [comment]
Hello @AlonsoItziar thanks for the feedback, i will add the info you provided.
As for the scale in the cadaster data, as far as i can see the original data you sent, the values go from 0 to 633. With "layer (Scale) does not seem right" do you mean the original data shoul have another value range? Or that we should apply a modifier to the data?
Here is the original data as shown on qgis:
![image](https://github.com/eurodatacube/eodash/assets/4036819/a40b6190-b568-4a39-ad48-069bca327743)

**Comment by AlonsoItziar** [comment]
Hi Daniel, 

yes I agree with your analysis, the *10 difference between the datasets is what I meant yesterday with "100m in WSF is equivalent to 10km". 

The layer based on the cadaster dataset might be less accurate at the borders of Austria than the WSF one, since it considers only the buildings inside Austria, not from the countries at the border. We would need to understand how the WSF distance to settlement was produced, but it is likely that it includes urban information from the neighbouring countries and therefore provides more accurate info at the border. 

I suggest to confirm that the WSF distance layer was computed considering neighbour countries info, in that case I would keep both layers - let's also check with Patrick on Monday.

**Comment by patrick-griffiths** [comment]
@jamesemwheeler is looking into this now

**Comment by santilland** [comment]
@patrick-griffiths @AlonsoItziar integration of newest dataset available on branch. I still had to recompute the overviews for some reason, openlayers said there was a mismatch in them and could not combine the datasets.
The new datasets now behaves very similar to the WSF, there is no longer a disparity in units, so i think it would be ready to be merged.
I found quite some instances where there are only like 1 or 2 houses where the cadaster picks them up nicely but the WSF does not.
For example, these houses are only filtered out with the cadaster layer, not the WSF layer:


![Image](https://github.com/eurodatacube/eodash/assets/4036819/445cf63e-a8e2-47d4-a338-59f292a36abd)

I would propose to add this to the demonstrator now

**Comment by AlonsoItziar** [comment]
I had a look at it as well, it looks good, I agree with adding to demonstrator

**Comment by patrick-griffiths** [comment]
@santilland nice - that's exactly the complementarity that we were hoping for!

**Comment by santilland** [comment]
Data description has been provided and needs to be integrated

**Comment by santilland** [comment]
Data descriptor has been updated, closing the issue
