### ISSUE TITLE
Integrate ADO data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2199]
As provided here https://ado.eurac.edu/

**Comment by lubojr** [comment]
Data have been added to geodb into table ado_data
with columns time	spi-1	spi-12	spei-1	spei-12	nuts_id for NUTS_3

integration WIP in  https://github.com/eurodatacube/eodash/tree/gtif_ado

**Comment by santilland** [comment]
Letest version available under:
https://gtif-testing.eox.at/gtif_ado/

Considered ready to be merged

**Comment by lubojr** [comment]
@patrick-griffiths Please have a look if we can merge to demo.

**Comment by patrick-griffiths** [comment]
looks quite good to me, I asked EURAC to take another look...
data descriptors are also still missing - I will request these..

**Comment by santilland** [comment]
@patrick-griffiths  I added descriptors i have taken from their client, i would propose to merge so that it is included and to do any further updates they would like to have once we get further feedback. Any objections on bringing this to the demonstrator?

**Comment by patrick-griffiths** [comment]
@santilland no - this is good to go into the demo!
