### ISSUE TITLE
Sustainable cities - "city selection"

### ISSUE THREAD

**Issue by Patrick1G** [eurodatacube/eodash#2214]
( @slumnitz created this, i just converted it to an issue )

The current "green roof" and "solar roof" tools have the option to only zoom to or select 4 cities.
Once the Austria wide dataset is provided it would be fantastic to allow for zooming to specific cities or neighbourhoods, beyond these 4 primary cities.

Potential options could be, ordered by nicest to have:

1. Best possible solution: search functionality of specific addresses or cities (type in google maps style), similar to: https://sunroof.withgoogle.com/data-explorer/.
* a user types in an address or city name and the map zooms to the respective area.

2. potential second solution: (less desirable as little overview)
* drop down menu for all major Austrian cities (over 10.000 inhabitants)

3. minimum expectation: 
* highlighting priority cities - add more city names comparable to currently implemented: Innsbruck, Wien, Graz, Linz, St Poelten
(Perhaps Susanne can provide a list of up to 10 priority cities)

@santilland please advise on feasibility of suggestion 1.

**Comment by santilland** [comment]
Implementation of location search is being explored, it is tracked in following issue #2483 
Closing this issue
