### ISSUE TITLE
Add legend to Air Quality Trilateral for OMI

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#222]
- [x] display OMI data in the same colour scale as TROPOMI
- [x] use same legend for OMI and TROPOMI
- [ ] evaluate visual with science teams

**Comment by Schpidi** [comment]
mail from Drew Bollinger "The tiler endpoint supports a rescale parameter which accepts two comma separated values as min and max. So we send "0,1e16" to get the full range scaled from 0-1 (and then afterwards a color ramp is applied). I think you should be able to modify this parameter if you want to convert between the two sensors. Let me know if you have any questions." (https://8ib71h0627.execute-api.us-east-1.amazonaws.com/docs#/tiles/tile_v1__z___x___y___scale_x___ext__get)

**Comment by Schpidi** [comment]
comment from @drewbo via mail: "All of the colormaps are from [rio-tiler](https://github.com/cogeotiff/rio-tiler/blob/master/docs/colormap.md) which is mostly [matplotlib](https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html) colormaps with a few additions that are more suited for raster analysis. Let me know if that helps."

**Comment by lubojr** [comment]
@aapopescu @drewbo @olafveerman  @JPatruno @Schpidi  I have a question regarding the air quality from OMI (nasa api) values. We can control the color range in which we are getting the data from using the "rescale" parameter. I have tried to use the same colorscale ('reds') as S5P pal maps (https://maps.s5p-pal.com/) are using (as Euro Data Cube layer is not available yet on the public instance) I am personally not sure about the actual values units or meaning on the nasa api. I have tried to stretch them to <0, 1.8e14> - see images below, as the legend for tropomi says 0-180 umol/m2 and tried to have a look at the comparison. The images look similar, but the OMI layer looks brighter, so I think I did not catch the scales exactly the same. I would need some feedback which values of the stretch should be used. 
![omi_1](https://user-images.githubusercontent.com/19269667/84877070-4a7d7c00-b088-11ea-920a-123838d31351.png)
![omi_2](https://user-images.githubusercontent.com/19269667/84877075-4c473f80-b088-11ea-9250-ea54b65416a8.png)
![tropomi_1](https://user-images.githubusercontent.com/19269667/84877080-4d786c80-b088-11ea-80fc-4b3ba4b88fbf.png)
![tropomi_2](https://user-images.githubusercontent.com/19269667/84877083-4e110300-b088-11ea-85fb-44b8237a913f.png)

**Comment by Schpidi** [comment]
@drewbo is this legend valid?

![OMI](https://user-images.githubusercontent.com/482265/84884105-97198500-b091-11ea-975f-a7a812dcf908.png)

**Comment by drewbo** [comment]
@Schpidi yes, the legend (both in color scale and units, molecules/cm<sup>2</sup>) you've shown is what the OMI team uses. 

@lubojr our data units match the legend @Schpidi posted. I'm not positive what is occurring since that scaling parameter you used should account for the change in units (per cm<sup>2</sup> vs per m<sup>2</sup>). I guess it's possible differences in the sensor resolution account for some of the visual difference?

**Comment by aapopescu** [comment]
@lubojr OMI and TROPOMI will not show the exact same values. Many factors: different resolution, different sensing dates and times (NO2 is highly volatile, it persists only a few hours). 

what you can do is to verify if you see features i.e. cities popping up in OMI. TROPOMI is higher res, so it will show more.

can we put this in staging and share it with NASA AQ team?

**Comment by lubojr** [comment]
@drewbo @aapopescu Thank you for feedback, it was very helpful. I will leave the scale as 0-1.8e14 to have the legend matching and push to staging for sharing.
