### ISSUE TITLE
run serve (and build) no longer running clean (warnings / issues )

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#223]
- [x] Sometimes build during run serve will hang with message 
WAIT  Compiling...                                                                                                                                                                               12:57:19 PM
40% building 0/3 modules 3 active /home/santilland/Development/eodash/app sync /^\.\/public.*$/
- [x] Issues loading datasets (many warnings)
 warning  in ./public/eodash-data/data/Regional_Global_Indicator_Countries.csv
Module parse failed: Unexpected token (3:6)
You may need an appropriate loader to handle this file type, ...

**Comment by silvester-pari** [comment]
should be fixed with 0b985d29badd4d1032496da714fdd25336a901db

**Comment by Schpidi** [comment]
looks good for me. thanks a lot!
