### ISSUE TITLE
Replace temporary icons

### ISSUE THREAD

**Issue by mariangela-cataldo** [eurodatacube/eodash#2233]

**Comment by mariangela-cataldo** [comment]
Here come the first icons for Green Roofs and Solar Roofs:


![Image](https://github.com/eurodatacube/eodash/assets/115264145/4909b6f7-9e9d-4c30-bb1f-a0fe679c6ca9)
![Image](https://github.com/eurodatacube/eodash/assets/115264145/ec0dcd5c-d1af-47d4-979f-a1940daa0308)

**Comment by santilland** [comment]
Great, thank you, icons have been included in staging environment and will be available in the next push to the demonstrator

**Comment by mariangela-cataldo** [comment]
Two more! (though I am not sure the Carbon Accounting is ready for a Forest Carbon tool yet...)

![Image](https://github.com/eurodatacube/eodash/assets/115264145/24c9ccdb-adc5-4a13-8df1-394810645363)
![Image](https://github.com/eurodatacube/eodash/assets/115264145/e4ad9434-cfe2-443d-bba4-10af8459959e)
