### ISSUE TITLE
Trilateral -Possibility to have story per spotlight additionally to story per indicator

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#224]

**Comment by silvester-pari** [comment]
there is now a first implementation in https://github.com/eurodatacube/eodash/commit/e8d399f5b4286b08a2025d6b77580059a250cde0 that allows to override the default indicator story with a file in the story path. the file has to follow the convention `<AOI_ID>-<Indicator Code>`, for example `FR3-E1` or `BE3-E1a`. let's see if this fits our needs when the first stories arrive.

**Comment by silvester-pari** [comment]
@aapopescu the feature is implemented, now it is up to you to add data ;-)
