### ISSUE TITLE
Mobility data

### ISSUE THREAD

**Issue by DanGasb** [eurodatacube/eodash#2243]
- Regarding the correlation explorer menu:
![image](https://github.com/eurodatacube/eodash/assets/117925117/bba0b707-3640-4d47-acce-d5cd07f0349b)
1) replace "Sentinel5-p values" with "Sentinel5-p NO2"
2) replace "Model value (WRFChem)" with the name of the variable displayed and add the units in the plot
- In the correlation explorer all colorbar related to the different products disappeared
- Disable the possibility to correlate Sentinel5-p data with themselves
![image](https://github.com/eurodatacube/eodash/assets/117925117/12a23db4-af7f-4762-a2c9-0f0806e9acaf)

**Comment by santilland** [comment]
wrfchem model data units "ug m-3"

**Comment by santilland** [comment]
Colormap legends for all parameters added, renamed parameter descriptors.
Created new issue for disabling the possibility of comparing s-5p values to themselves #2257 
Items listed in the issue have been resolved and a dedicated issue has been created. Closing this issue.
