### ISSUE TITLE
Overview/list of current available GTIF features.

### ISSUE THREAD

**Issue by dischon** [eurodatacube/eodash#2245]
Overview/list of current available GTIF features.

**Comment by Schpidi** [comment]
Hi @dischon, what type of list would you envision? When you start the explore mode currently you see below note, is this what you need?

![Screenshot from 2023-06-07 21-11-52](https://github.com/eurodatacube/eodash/assets/482265/5d913892-7795-444e-8ab0-d17a42a825ed)

**Comment by santilland** [comment]
I will close the issue as i think the information was provided and received. Please let us know if there is more information needed and we can reopen the issue
