### ISSUE TITLE
Energy: Turbine detection and S2 overlays

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#2259]
@lubojr Could you please check if the S2 overlay is correctly configured? 

I see a lot of cases as in the example below, where detections seem to be based on very cloudy S2 imagery, which I assume DHI @kegro would have excluded from the detection workflow? 
 

![Image](https://user-images.githubusercontent.com/40148967/246374717-ba1697e4-e752-406d-8df5-2d56a4e93020.png)

**Comment by kegro** [comment]
@patrick-griffiths we'll take a look at this.

**Comment by kegro** [comment]
@patrick-griffiths @lubojr we cannot replicate the problem on our side. When we zoon to the area above, we get the first S2 image below. When we click on the turbine of interest we get the second S2 image, with a small amount of snow cover.
First image

**Comment by patrick-griffiths** [comment]
@lubojr and @santilland 

could you please investigate if this issue is on the side of the S2 overlays?

**Comment by patrick-griffiths** [comment]
@jamesemwheeler 
could we update the stretch on these late season images? they are too dark...

**Comment by patrick-griffiths** [comment]
@lubojr @kegro @jamesemwheeler 

one example below where two things seem strange: 

1) detections seem to be based on this cloudy imagery -  can you confirm? 

2) the S2 imagery appears to be full of artefacts (which like something you get from compositing) - can you confirm that this comes from the source imagery?

![Image](https://github.com/eurodatacube/eodash/assets/40148967/235cf0d9-6544-4005-9347-f2ec6fbab47d)

**Comment by AlessandroScremin** [comment]
@patrick-griffiths  @lubojr @santilland  cc: @jamesemwheeler @AparicioSF 

From what I see I can only work on the brightness, For that I changed the evalscript that now should normalize data for visualisation. Image now should be brighter.

for what concerns the artifacts and the cloudy, the data are as they are in Sentinel Hub (have not been ingested by PLES) so there are two possilbe solution I see:

- To check that the provided dates are really the good ones and the date formats is as expected (maybe months has been confused with days?) @lubojr or @AparicioSF could you please provide me the list of dates?
- TO check the layer EOX is retriving for the Overlay (@lubo coukld you please provide me the info of the IDs used?)

**Comment by AlessandroScremin** [comment]
> @lubojr @kegro @jamesemwheeler
> 
> one example below where two things seem strange:
> 
> 1. detections seem to be based on this cloudy imagery -  can you confirm?
> 2. the S2 imagery appears to be full of artefacts (which like something you get from compositing) - can you confirm that this comes from the source imagery?
> 
> ![Image](https://user-images.githubusercontent.com/40148967/248799954-235cf0d9-6544-4005-9347-f2ec6fbab47d.png)


@patrick-griffiths @lubojr @kegro 
This image is the same I have in SH...can do nothing on the artifacts. Coordinate with Sinergize.

for the Clouds on the 20221106 it is indeed a cloudy image. So please verify the dates!

**Comment by gmilcinski** [comment]
@patrick-griffiths - can you please share the image from EO Browser via URL, i.e. clicking "Share" in the EO Browser, so that we can look into the specific location/date. 
That said, we have noticed such artefacts in the original imagery in the past.

**Comment by AlessandroScremin** [comment]
@gmilcinski 
https://sentinelshare.page.link/k2Ci

**Comment by gmilcinski** [comment]
This is an artefact in the original image. It only appears in the L2A data, see L1C:  
https://sentinelshare.page.link/d638

**Comment by lubojr** [comment]
> @patrick-griffiths @lubojr @santilland cc: @jamesemwheeler @AparicioSF
> 
> From what I see I can only work on the brightness, For that I changed the evalscript that now should normalize data for visualisation. Image now should be brighter.
> 
> for what concerns the artifacts and the cloudy, the data are as they are in Sentinel Hub (have not been ingested by PLES) so there are two possilbe solution I see:
> 
> * To check that the provided dates are really the good ones and the date formats is as expected (maybe months has been confused with days?) @lubojr or @AparicioSF could you please provide me the list of dates?
> * TO check the layer EOX is retriving for the Overlay (@lubo coukld you please provide me the info of the IDs used?)
cc @AlessandroScremin @patrick-griffiths 
- For the S2 Layer I have used SENTINEL-2-L2A-TRUE-COLOR layer from the GTIF SH instance
- Regarding the dates, we are using the source geojson https://eox-gtif-public.s3.eu-central-1.amazonaws.com/wind_turbines/wind_turbines_austria.geojson property detection_time from each feature. The format there seems to be yyyymmdd so we parse it as that and afterwards send a request to SH WMS with TIME parameter of an interval yyyy-MM-dd/yyyy-MM-dd of plus one day. For this concrete case of feature ID=935, the detection_time is 20221106. So we request interval 2022-11-06/2022-11-07 (which is the time interval we have used for most of SH layers up until now) which yields this WMS response that is attached to this issue. If i changed the interval to just the day itself, (20221106/20221106) I receive the same WMS image as well. So this seems like a problem of the original reference inside the GeoJSON that we have received.

**Comment by patrick-griffiths** [comment]
> > @patrick-griffiths @lubojr @santilland cc: @jamesemwheeler @AparicioSF
> > From what I see I can only work on the brightness, For that I changed the evalscript that now should normalize data for visualisation. Image now should be brighter.
> > for what concerns the artifacts and the cloudy, the data are as they are in Sentinel Hub (have not been ingested by PLES) so there are two possilbe solution I see:
> > 
> > * To check that the provided dates are really the good ones and the date formats is as expected (maybe months has been confused with days?) @lubojr or @AparicioSF could you please provide me the list of dates?
> > * TO check the layer EOX is retriving for the Overlay (@lubo coukld you please provide me the info of the IDs used?)
> >   cc @AlessandroScremin @patrick-griffiths
> 
> * For the S2 Layer I have used SENTINEL-2-L2A-TRUE-COLOR layer from the GTIF SH instance
> * Regarding the dates, we are using the source geojson https://eox-gtif-public.s3.eu-central-1.amazonaws.com/wind_turbines/wind_turbines_austria.geojson property detection_time from each feature. The format there seems to be yyyymmdd so we parse it as that and afterwards send a request to SH WMS with TIME parameter of an interval yyyy-MM-dd/yyyy-MM-dd of plus one day. For this concrete case of feature ID=935, the detection_time is 20221106. So we request interval 2022-11-06/2022-11-07 (which is the time interval we have used for most of SH layers up until now) which yields this WMS response that is attached to this issue. If i changed the interval to just the day itself, (20221106/20221106) I receive the same WMS image as well. So this seems like a problem of the original reference inside the GeoJSON that we have received and/or we need to use a different layer which displays S2L1C

@kegro could you take another look at this? we are seeing several examples where the s2 image indicated in the detection Json does not seem to match the one actually used in the detection. See also @lubojr's comment above..

Here is another example I just cam across: (ignore the L2 artifacts) this seems to be an image that should not have been selected for inference (except the L2 SLC does not pick up this cloud over?)
https://gtif.esa.int/explore?x=1402850.95397&y=6026921.0908&z=15.50778&poi=Austria-REP6 
![image](https://github.com/eurodatacube/eodash/assets/40148967/a9ce17fd-e18d-42b0-ab29-471e9cb50062)

**Comment by kegro** [comment]
@patrick-griffiths we'll take a look at the cloudy images today and get back to you.

**Comment by kegro** [comment]
@patrick-griffiths @lubojr @santilland I think I found the issue. It looks like we need to be more aggresive with the cloud masking. In the example [above](https://github.com/eurodatacube/eodash/issues/2259#issuecomment-1609453859), using imagery from `20221106` the Level-2 mask indicates `Cloud medium probability`. This part of the image should not have been included in the inference.
This example is a false detection. And actually we have many false detections in the same region of Austria, caused by the same issue. We can manually remove these as a quick fix and send you the updated layer. My colleague who made the model is on holidays unitl end of July. We could include the medium cloud probability in the masking when he's back, and it should improve the results. As a quick fix we could manually delete the false detections caused by this issue and give you an updated layer?

**Comment by patrick-griffiths** [comment]
@kegro sure that short fix would be valuable for now, many thanks..

Going forward, it probably makes sense to build on a secondary cloud and haze check to flag suspicious scenes... The SCL product will likely have many such shortcomings during low sun elevation angles...

**Comment by lubojr** [comment]
@kegro @patrick-griffiths The new detection file has been referenced in the deployed gtif client now.
