### ISSUE TITLE
Trilateral & RACE: Change default start date for reference in map comparison mode

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#227]
For Air Quality Maps:
the reference map (on the left side) should by default be the closest 2019 map.

E.g. When user loads the maps, the one on the right is the most recent one (e.g. 2020-06-01), and the one one the left is the closest equivalent one in 2019 (e.g. 2020-06-05).

The same for the NASA NO2 maps

**Comment by lubojr** [comment]
done in https://github.com/eurodatacube/eodash/pull/241

**Comment by Schpidi** [comment]
deployed on staging
