### ISSUE TITLE
save map configuration on Sentinel-2 layer

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2275]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/dashboard?id=fa8eb12853a73ec7&amp;">https://www.eodashboard.org/dashboard?id=fa8eb12853a73ec7&amp;</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 16</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>add map element to custom dashboard, acive coompare mode, save map configuration</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>map configuration is saved, comapre mode is visible on view only link</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Documented now in https://github.com/eurodatacube/eodash/issues/2341
