### ISSUE TITLE
Change order in list of Countries in Trilateral

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#228]
Order:

- United States
- Europe (create a title Europe and list European countries below, alphabetical order)
- Japan
- China
- India

**Comment by silvester-pari** [comment]
right now, it is sorted alphabetically. should it then be still alphabetically, but in reverse? or a custom order? if custom, then please provide an order that would suit you.

**Comment by aapopescu** [comment]
Order:

United States
Europe (create a title Europe and list European countries below, alphabetical order)
Japan
China
India

**Comment by silvester-pari** [comment]
added in https://github.com/eurodatacube/eodash/commit/73b16668d59db0bc7c750fd14b55a539fa837184
