### ISSUE TITLE
dynamic image selection based click on point in time series

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#2287]
e.g. for the hydro power monitoring, it would be great to be able to select the corresponding image by clicking on a dot in the time series... 

![Image](https://user-images.githubusercontent.com/40148967/253751840-5dcbe4f0-50b3-47f1-a5eb-14b775c8ff41.png)

**Comment by lubojr** [comment]
Duplicate of https://github.com/eurodatacube/eodash/issues/1735 - raising a priority of this feature.
