### ISSUE TITLE
Trilateral - find a way to deal with indicator versions

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#229]
Water Quality Time series will include:

- For some areas Time series from only 1 sensor
- For other areas Time series from multiple sensors

How to display this in the indicator list?

**Comment by Schpidi** [comment]
@aapopescu was the solution yesterday to use two indicator types or to use almost similar but slightly different coordinates?

**Comment by Schpidi** [comment]
solution is to use slightly different coordinates
