### ISSUE TITLE
Sentinel-1 data doesn't load on SG01-E9 indicator

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2297]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://eodash-trilateral-testing.eox.at/map-chart-time-interaction/explore?x=11563449.38615&amp;y=142340.68548&amp;z=14.01946&amp;poi=SG01-E9&amp;search=Singapore%3A+Activity+indicator">https://eodash-trilateral-testing.eox.at/map-chart-time-interaction/explore?x=11563449.38615&amp;y=142340.68548&amp;z=14.01946&amp;poi=SG01-E9&amp;search=Singapore%3A+Activity+indicator</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 112</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://eodash-trilateral-testing.eox.at/map-chart-time-interaction/explore?x=11563449.38615&amp;y=142340.68548&amp;z=14.01946&amp;poi=SG01-E9&amp;search=Singapore%3A+Activity+indicator">https://eodash-trilateral-testing.eox.at/map-chart-time-interaction/explore?x=11563449.38615&amp;y=142340.68548&amp;z=14.01946&amp;poi=SG01-E9&amp;search=Singapore%3A+Activity+indicator</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Data loads on the map</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
fixed in https://github.com/eurodatacube/eodash/commit/db1d50725e3705ded517adcb97a888312cb8a844
