### ISSUE TITLE
Trilateral - integrate Anomaly Water Quality Graph

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#230]
In trilateral version the water quality time series will display a graph containing 3 line plots.
Each line will be the anomaly chlorophyll concentration computed with 1 agency sensor.

**Comment by santilland** [comment]
Hi, in order to tackle this new visualization we will need the corresponding data in CSV format, could you provide this?

**Comment by Schpidi** [comment]
data added https://github.com/eurodatacube/eodash/blob/staging/app/public/data/trilateral/N3b.csv

**Comment by santilland** [comment]
Need to think about a set of colors that we can use for non indicator status colors, rest should be working as expected

**Comment by aapopescu** [comment]
Use a color-blind friendly color scheme 
Limit time axis (X axis) to start from 2019. Do not plot older values.

to be updated in the data:
- EO sensor values
- time range of NASA

**Comment by santilland** [comment]
https://thenode.biologists.com/wp-content/uploads/2019/08/Fig_1-Palettes-for-blog_v2.png
![image](https://user-images.githubusercontent.com/4036819/85023022-7413d180-b174-11ea-8fbe-f240649aae24.png)
One of these? They seem to be color-blind friendly

**Comment by santilland** [comment]
Added ToI_bright as colors, e.g.:
![image](https://user-images.githubusercontent.com/4036819/85033891-bf80ac80-b181-11ea-9771-110076675018.png)

![image](https://user-images.githubusercontent.com/4036819/85033965-d3c4a980-b181-11ea-9dbb-cc4c90b523d2.png)
