### ISSUE TITLE
Add GHS built-up surface data from JRC

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2312]
**Add GHS-BUILT-S-R2023A dataset.**
Ingest product in EDC, create RACE and EODASHBOARD multi-temporal indicator with the 1975-2030 product 
https://ghsl.jrc.ec.europa.eu/ghs_buS2023.php

**Dataset description**
GHS-BUILT-S R2023A - GHS built-up surface grid, derived from Sentinel2 composite and Landsat, multitemporal (1975-2030)

**Visualisation**
Multitemporal layer with custom AOI feature enabled and Jupyter Notebook linked in the data panel

- [x] ingest Data in EDC and described in edc collections and make available as STAC item
- [x] visualise on RACE and EO DASHBOARD
- [x] prepare JN with example of analytics. JN example to be evaluation of fire impact on populated areas on a European site

 @leahsturm, I'd like you to take the lead on this JN

**Comment by aapopescu** [comment]
@AlessandroScremin , data characteristics from https://ghsl.jrc.ec.europa.eu/documents/GHSL_Data_Package_2023.pdf?t=1683540422 

- Author: Pesaresi, Martino; Politis Panagiotis
- Product name: GHS-BUILT-S_GLOBE_R2023A
- Spatial extent: Global
- Temporal extent: from 1975 to 2030, 5 years interval
- Coordinate Systems: World Mollweide (ESRI:54009), WGS84 (EPSG:4326)
- Spatial resolution available: 10 m, 100 m, and 1 km, 3ss, 30ss
- Encoding: integer (Byte, UInt16, UInt32), unit: built square meters in the grid cell
- Data organisation: GeoTIFF file (10 m, 100m, 1km, 3 ss, 30 ss) with overview images (OVR). Data tiles of
- 100x100 km size in GeoTIFF format (10 m, 100 m, 1 km, 3 ss, 30 ss). Tile schema in shapefile format

**Comment by AlessandroScremin** [comment]
@aapopescu @santilland @lubojr 

The Global layer for the GHS Built S has been prepared, ingested in EDC and provided as layer

Layer ID: ID: GHS_BUILT_S
is: 0c7aa265-50f9-4947-9980-2ee5ae204803

evalscript
//VERSION=3
function setup() {
  return {
    input: [{
      bands: ["BUILT", "dataMask"], // this sets which bands to use
    }],
    output: { // this defines the output image type
      bands: 4,
      sampleType: "UINT8"
    }
  };
}
 


function evaluatePixel(sample) {

  var arr = colorBlend(sample.BUILT,    [0,2500,5000,7500,10000],    [[20, 7, 138,0],[124, 8, 169],[203, 71, 120],[246, 154, 67],[251, 250, 144] ]); 
  if (sample.dataMask==1)  arr.push(255);
  else arr.push(0);
  return arr;
}

**Comment by AlessandroScremin** [comment]
@lubojr

Thnaks for pointing the issue out...indeed those 3 years were somehow corrupted looking at the size, even if correctly ingested. We are working on it to reingest the failed tiles. I will update you...

**Comment by AlessandroScremin** [comment]
@lubojr 
issue should be solved now...

**Comment by aapopescu** [comment]
Thanks, everyone!

@lubojr, the description is updated. We need to add to the description:
- the link to the dataset in EDC  - we need to get this approved https://github.com/eurodatacube/public-collections/pull/309/commits/43388aadd9ace7d0cb1370f8053a37afed402b86 
cc: @AlessandroScremin 

- the link to the notebook cc: @dmoglioni when the notebook is in EDC, please provide the link

**Comment by AlessandroScremin** [comment]
Dear @aapopescu and @lubojr 

federico sent already a pull request the day the issue was rised...so please approve the pull and the new ID will be the correct one.

the pull request is this one

https://github.com/eurodatacube/public-collections/pull/309/commits/9a062294ca5e3ae5ad1576affab07131a7794acb

**Comment by aapopescu** [comment]
PR approved
