### ISSUE TITLE
Migrate CSV entries to GEODB

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2314]
For the ongoing work on STAC Catalog based approach of accessing eodash data, we need to have all to-be used data present in GEODB because we will be removing the possibility to use CSV files for data definitions (which we have up to now been using for collections which were not updated anymore).

@aapopescu @AlessandroScremin We need to coordinate on which - if all or not collections should be migrated to GEODB.

The currently used trilateral CSVs are on https://github.com/eurodatacube/eodash/blob/staging/app/src/scripts/generate_files.py#L757-L766
```
'/public/data/trilateral/E10a1.csv',
'/public/eodash-data/data/E10a2.csv',
'/public/eodash-data/data/E10a3.csv',
'/public/data/trilateral/E10a6.csv',
'/public/data/trilateral/E10a8.csv',
'/public/data/trilateral/E10c.csv',
'/public/data/trilateral/N2.csv',
'/public/data/trilateral/N1_EG.csv',
'/public/data/trilateral/N2_EG.csv',
'/public/data/trilateral/SIF_EG.csv',
```
Used RACE CSVs are on 
https://github.com/eurodatacube/eodash/blob/staging/app/src/scripts/generate_files.py#L794-L818
```
'/public/eodash-data/data/C1.csv',
'/public/eodash-data/data/C2.csv',
'/public/eodash-data/data/C3.csv',
'/public/eodash-data/data/E8.csv',
'/public/eodash-data/data/E10a1.csv',
'/public/eodash-data/data/E10a2.csv',
'/public/eodash-data/data/E10a3.csv',
'/public/eodash-data/data/E10a5.csv',
'/public/data/trilateral/E10a8.csv',
'/public/eodash-data/data/E10a9.csv',
'/public/eodash-data/data/E13b2.csv',  # archived
'/public/eodash-data/data/N1a_PM25_CAMS.csv',
'/public/eodash-data/data/N1b_NO2_CAMS.csv',
'/public/eodash-data/data/N1c_PM10_CAMS.csv',
'/public/eodash-data/data/N1d_O3_CAMS.csv',
'/public/eodash-data/data/E13e_cargo.csv',
'/public/eodash-data/data/E13f_fishing.csv',
'/public/eodash-data/data/E13g_tanker.csv',
'/public/eodash-data/data/E13h_gioiatauro_tug.csv',
'/public/eodash-data/data/E13i_gioiatauro_SearchRescue.csv',
'/public/eodash-data/data/E13l_genova_pleasure.csv',
'/public/eodash-data/data/E13m_genova_passenger.csv',
'/public/eodash-data/data/E13n_traffic.csv',
```

After the decision is made the next task would be to migrate all the CSV tables to corresponding GEODB tables.

**Comment by lubojr** [comment]
Agreed to keep all of the currently used indicators. Some of them were already migrated to tables.
@AlessandroScremin to check and confirm existing tables and if missing add based on existing CSVs.

**Comment by AlessandroScremin** [comment]
cc: @dmoglioni 
Please have a look at the above list and check what is in the geoDB and what is missing

**Comment by dmoglioni** [comment]
@aapopescu 
I've cross-checked the data in the repo with the content present on the geodb for the trilateral list provided by @lubojr and summarized the analysis on the .xlsx attached.
It should be decided on:
- data collection nomenclature (keeping the existing one if present on db or renam
[data_collections_trilateral.xlsx](https://github.com/eurodatacube/eodash/files/12549594/data_collections_trilateral.xlsx)
ing it more intelligibly)
- how to handle misalignment (highlighted in yellow in the .xlsx)

I'll proceed now with the RACE list.

**Comment by dmoglioni** [comment]
@aapopescu 
I've cross-checked the data in the repo with the content present on the geodb for the trilateral list provided by @lubojr and summarized the analysis on the .xlsx attached.
It should be decided on:
- data collection nomenclature (keeping the existing one if present on db or renaming it more intelligibly)
- how to handle misalignment (highlighted in yellow in the .xlsx)

I'll proceed with the RACE list as-well.
[data_collections_trilateral.xlsx](https://github.com/eurodatacube/eodash/files/12549633/data_collections_trilateral.xlsx)

**Comment by dmoglioni** [comment]
Hi Anca @aapopescu,
I went thoroughly through the RACE list, attached below the results analysis.
 
[data_collections_race.xlsx](https://github.com/eurodatacube/eodash/files/12574973/data_collections_race.xlsx)

**Comment by santilland** [comment]
@dmoglioni thank you for the summary on the excel files, quick recap on the discussion, then i will try to comment on possible open points:

- Agreement on "repo" file, being considered the latest state, overwriting of geodb collections if misaligned
- Agreement on keeping indicator_code as collection name in geodb as STAC catalog will provide description when discovering data (in the future renaming of collection name should be trivial as process would overwrite info on geodb and stac configuration file) 
- Possibility of removing `Description` and `Indicator Name` from geodb collection tables, as this information can be provided by stac catalog - list of used parameters in eodash client to be provided

On specific items:

- C1, C2, C3 should have expected structure and can be ingested as 3 separate collections into geodb using indicator_code as collection name (previously they were shown tabbed, but no longer the case)
- E10a1 - in the race excel it says it is not available (a2 and a3 is with identifier _tri), but in trilateral excel it says E10a1 is available as  E10a1_tri, if also available we can use  E10a1_tri,  E10a2_tri,  E10a3_tri for both instances and no changes in geodb are needed
- E10a9 Alessandro explained possible issue of csv where subaoi is only present for first entry of a specific location
- N1_EG.csv, N2_EG.csv, SIF_EG.csv, this data was used to extract available dates for special Cairo JAXA WMS endpoints, with the catalog approach it should be possible to represent this information within stac, these datasets do not need to be ingested into geodb (the used indicator_code in the file name is misleading)

I hope that covers all open points, please let me know if anything else needs clarification.

**Comment by dmoglioni** [comment]
@santilland 
E10a1 for RACE to be checked: file on repo contains more entries wrt the trilateral file with an additional indicator name "Cumulated length of rows with active picking (km). Picking activity of red berries (absolute value and %)"

**Comment by santilland** [comment]
@dmoglioni i think we will need a decision from @aapopescu on what version we should use here, not sure why when the csv was updated

**Comment by santilland** [comment]
this data is the correct one /public/eodash-data/data/E10a1.csv -> E10a1_tri to be updated with it

**Comment by dmoglioni** [comment]
E10a1_tri updated with the data in /public/eodash-data/data/E10a1.csv.

Migration completed.

**Comment by lubojr** [comment]
@dmoglioni 
I've just tried to generate our internal structure from the geodb tables instead of from CSVs for these indicators and all indicators which were migrated look fine. Thank you.
