### ISSUE TITLE
Hydroenergy: different time series icons for different sensor observations

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#2318]
For the time series used in the hydro reservoir monitoring, it would be nice to indicate which sensor (sentinel-1 or -2) observed a point in time. Could be shown using different color and/or symbol. The information should be part of the image identifier. 

![Image](https://github.com/eurodatacube/eodash/assets/40148967/6eda3314-39e9-4676-9947-5c2da8498e7d)

**Comment by lubojr** [comment]
superseded by https://github.com/eurodatacube/eodash/issues/2463
