### ISSUE TITLE
Updating Map position in custom dashboard works only locally and with dev instance, but not production one

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2341]
```
{error: true, type: 'validation', details: Array(1)}
details: Array(1)
0: context
: {child: 'dataLayerTime', label: 'dataLayerTime', value: '2021-10-02', key: 'dataLayerTime'}
message: "\"dataLayerTime\" is not allowed"
path: ['dataLayerTime']
type: "object.unknown"
```
On production dashboard, following validation error is returned by the API

**Comment by lubojr** [comment]
Another symptom appeared as well:

the preselected time and area from custom dashboard (although correctly set in the database) is not reflected by the client in /scrolly endpoint

**Comment by santilland** [comment]
Creation of stories is being re-implemented, this issue no longer applies there, position can be passed as part of configuration object, closing this issue
