### ISSUE TITLE
Snow Water Equivalent is lacking a legend/color bar

### ISSUE THREAD

**Issue by Patrick1G** [eurodatacube/eodash#2362]
nor sure if we had this ever included, but we need a legend or colourmap

![Image](https://github.com/eurodatacube/eodash/assets/40148967/2f5ebedc-7c3c-4399-91fc-42cb94962b51)

**Comment by lubojr** [comment]
@patrick-griffiths Thanks for a report. Could you please tag someone from the team responsible for providing the original dataset to EDC, so they can give information about the legend used?
Or they can even make a PR to this file https://github.com/eurodatacube/eodash-assets/blob/main/generators/legends.json#L218-L222

**Comment by mariangela-cataldo** [comment]
Please add the following legends to the snow depth and snow water equivalent layers:

![snow_depth](https://github.com/eurodatacube/eodash/assets/115264145/b7930ee5-a5c6-4eaf-8436-34d42413e5fc)
![snow_water_equivalent](https://github.com/eurodatacube/eodash/assets/115264145/be7521eb-3dcd-41a1-adf3-e2f24b3e824c)

**Comment by lubojr** [comment]
@mariangela-cataldo Thank you for providing the legend.
We updated it in the catalog and also updated the markdown to bring back original content (before ui overhaul)
Closing the issue as solved.
