### ISSUE TITLE
BiDS bugs & fixes

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#2363]
collecting some smaller issues that should ideally to be fixed before BiDS demo on Tuesday afternoon:

[ The ones below relate to https://gtif-testing.eox.at/ui-panels-cat-changed-layout/ ] 
- [x] Energy > wind > "protected areas" exclusion has no effect
- [x] Energy > wind > filter by distance with Cadaster, acts as a binary exclusion rather than filter (when >0 all areas are excluded)
- [x] Scrolly stories containing embedded datasets do not load

**Comment by mariangela-cataldo** [comment]
- [ ] the new **Add custom layer** functionality doesn't seem to work properly with all tools: e.g. the Sustainable Cities gives an error when visualising the custom layer; the Moving Trucks is not working both in terms of custom layer visualisation and in terms of new layer naming + it seems to trigger a change in the subtools list

**Comment by lubojr** [comment]
> collecting some smaller issues that should ideally to be fixed before BiDS demo on Tuesday afternoon:
> 
> [ The ones below relate to https://gtif-testing.eox.at/ui-panels-cat-changed-layout/ ]
> 
> * [ ]  Energy > wind > "protected areas" exclusion has no effect
> * [ ]  Energy > wind > filter by distance with Cadaster, acts as a binary exclusion rather than filter (when >0 all areas are excluded)

Thank you for the report. We are investigating the issue. I was able to reproduce it on live gtif as well, so it is not connected to the new changes.

> * [ ]  the new **Add custom layer** functionality doesn't seem to work properly with all tools: e.g. the Sustainable Cities gives an error when visualising the custom layer; the Moving Trucks is not working both in terms of custom layer visualisation and in terms of new layer naming + it seems to trigger a change in the subtools list

Custom Layer should now be fixed for Sustainable cities.
Moving trucks - fixed the custom area triggering change in subtools list. Custom Layer visualisation does not work yet.

> * [ ]  the Explore Tools big button on the Home Page doesn't bring to the Explore page but gives an error

This is just connected to the testing instance, it will work on the production version.

**Comment by lubojr** [comment]
Latest version has been deployed to gtif.esa.int now

**Comment by patrick-griffiths** [comment]
- [ ] biomass filter does not work as a filter, but a stretch. See below: values below 180 should be transparent
![image](https://github.com/eurodatacube/eodash/assets/40148967/740044f4-0105-472a-9459-0e1224bb5a71)
- [ ] rather than alphabetic ordering of domains and tools, I would prefer to keep the previous order. This is not critical for BiDS demo, but should be eventually rearranged accordingly (simple as certain tools are more valuable, currently, than others)

**Comment by patrick-griffiths** [comment]
@lubojr

Every > wind tools:
I cannot find the monthly wind profiles anymore!?

**Comment by patrick-griffiths** [comment]
> @patrick-griffiths zooming to a level of Zahlsprengel and clicking on one of them shows the chart with monthly wind speed for that ZSP in the analysis panel.

Ok good to know it's still where is supposed to be... I tried at BiDS and couldn't get it to work, but that might have been a connectivity issue after all...

**Comment by lubojr** [comment]
> * [x]  biomass filter does not work as a filter, but a stretch. See below: values below 180 should be transparent
>   ![image](https://user-images.githubusercontent.com/40148967/280942090-740044f4-0105-472a-9459-0e1224bb5a71.png)
> * [ ]  rather than alphabetic ordering of domains and tools, I would prefer to keep the previous order. This is not critical for BiDS demo, but should be eventually rearranged accordingly (simple as certain tools are more valuable, currently, than others)

Created a new issue in the component itself https://github.com/EOX-A/EOxElements/issues/416



> * [ ]  the new **Add custom layer** functionality doesn't seem to work properly with all tools: e.g. the Sustainable Cities gives an error when visualising the custom layer; the Moving Trucks is not working both in terms of custom layer visualisation and in terms of new layer naming + it seems to trigger a change in the subtools list

Created a new issue in eodash https://github.com/eurodatacube/eodash/issues/2376

Closing this issue
