### ISSUE TITLE
Layers menu disappears from map in custom-dashboard

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2382]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/dashboard">https://race.esa.int/dashboard</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 119</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Add a map to a custom dashboard. Click on layers </p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>layer options appear and user is able to select from the options</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Should get solved by the new UI layout, but leaving the issue open for now.
