### ISSUE TITLE
Overpass API integration enhancements

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2385]
- [x] type of amenity multi-selection UI element (dropdown curated)
- [x] add user warning for request timed out (30s)
- [x] add geometry parsing for other geometry types received from overpass (now only nodes, also consider ways/relations) :heavy_check_mark: 
- [ ] ~more types of features to be "addable" - based on indicator provider requests~ EDIT: we did not get any list which would be accepted

**Comment by UndeadFairy** [comment]
New tag requests:
"power"="cable"
 "cargo"="liquid_bulk"

**Comment by lubojr** [comment]
:arrow_double_up: add the OSM Infrastructure app from GTIF

**Comment by lubojr** [comment]
Implemented and deployed to the feature branch 
![image](https://github.com/eurodatacube/eodash/assets/19269667/abff6dd0-225c-4ee6-bcdb-0c3690a00070)

Following checkbox appears for each new Overpass api key=value pair that is configured.
