### ISSUE TITLE
Minor UI changes GTIF

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2388]
- [x] darker color for panel header background
- [x] remove "Domains" header in the itemfilter (duplicated info)
- [ ] layers panel should open itself automatically after selecting the tool for the first time and switch to analysis panel

**Comment by lubojr** [comment]
## 1.1 Explore Page

### All Panel titles

Text in capital letters, and bold and in Deep Space colour (#003247), and with a grey shaded background (colour: Neutral Space #e8e8e4) - no matter if collapsed or opened
![image](https://github.com/eurodatacube/eodash/assets/19269667/b9cd6c45-80c3-474b-a47e-a0585a58c3dc)

### Zoom button

Move the Information and Analysis Panels completely to the right border and save space.
Move the Zoom icon (+/-) to the left of the analysis/information panel.

### Domains & Tools Panel
The Panel shall be called “DOMAINS” and when open shall have, after the list of the 5 domains, “TOOLS” with the same style of title. Both titles shall be bold
![image](https://github.com/eurodatacube/eodash/assets/19269667/dd781642-0c2c-4e8f-9fcf-c3eafc33b78d)

### Information Panel
Subtitles shall be made smaller (at present they are bigger than Panels titles). - this is to be done via custom style override
Substitute subtitles with “Tips on using this tool” & “Why this data?” - this is to be done by updating asset tex

### Layers Panel
Open automatically at tool selection, so to visualize colour bar immediately.
When deleting a layer via a trash icon, a not aligned pop up with “optional layers” comes out. Think about what to do with the cancelling option.

**Comment by silvester-pari** [comment]
An idea for the admin units selection could be to offer a greyed out information if the zoom level is too low, and switch it to dark if the zoom level is correct. In case of drawing polygons, it would always be black:

![image](https://github.com/eurodatacube/eodash/assets/26576876/b2239014-b64f-43bb-9083-7e62ae092228)

**Comment by santilland** [comment]
Topics have been discussed and implemented.
If there are any aspects considered open, let's create a dedicated issue to help identify any remaining points.
Closing this issue.
