### ISSUE TITLE
Compare two images slider isn't working in 3 different browsers

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2391]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/story?id=nasa-thwaites&amp;page=2">https://www.eodashboard.org/story?id=nasa-thwaites&amp;page=2</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 119</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Encountered problem in Safari, then switched to Chrome and encountered the same issue. I also tried it in Firefox, no change. I accepted all cookies in each browser. I tried these two URLs:
<a target="_blank"  href="https://www.eodashboard.org/story?id=nasa-thwaites&amp;page=1">https://www.eodashboard.org/story?id=nasa-thwaites&amp;page=1</a>
<a target="_blank"  href="https://www.eodashboard.org/story?id=nasa-thwaites&amp;page=2">https://www.eodashboard.org/story?id=nasa-thwaites&amp;page=2</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>When I moved the slider left and right I expected the image to change, but nothing happened.</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>No comments</p>

**Comment by lubojr** [comment]
Thank you for the report. Fixed in f3a64409830e824a506ae92cb03dc0b3810f7bd4
