### ISSUE TITLE
Forestry Story

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2392]
- @AparicioSF is drafting the text
- datasets to be defined

**Comment by aapopescu** [comment]
#2411 
#1725 
#2408

**Comment by aapopescu** [comment]
Please includue these NASA datasets


EPA-annual-emissions_5_Forest_Fires
EPA-daily-emissions_5_Forest_Fires
EPA-monthly-emissions_4F_Field_Burning
hls-ndvi
lis-global-da-evap

**Comment by lubojr** [comment]
@aapopescu :arrow_double_up: 5 datasets are added in a branch `adding-biomass-data` https://github.com/eurodatacube/eodash/pull/2511

https://eodash-trilateral-testing.eox.at/adding-biomass-data/?indicator=EPA_Forest_fire_Methane_Yearly
https://eodash-trilateral-testing.eox.at/adding-biomass-data/?indicator=EPA_Forest_fire_Methane_Daily
https://eodash-trilateral-testing.eox.at/adding-biomass-data/?indicator=EPA_Field_burning_Monthly
https://eodash-trilateral-testing.eox.at/adding-biomass-data/?indicator=LIS_Global_DA_Evap
https://eodash-trilateral-testing.eox.at/adding-biomass-data/?indicator=HLS_NDVI

Empty markdowns are ready:
https://github.com/eurodatacube/eodash/blob/adding-biomass-data/app/public/data/trilateral/EPA_Forest_fire_Methane_Yearly.md
https://github.com/eurodatacube/eodash/blob/adding-biomass-data/app/public/data/trilateral/EPA_Forest_fire_Methane_Daily.md
https://github.com/eurodatacube/eodash/blob/adding-biomass-data/app/public/data/trilateral/EPA_Field_burning_Monthly.md
https://github.com/eurodatacube/eodash/blob/adding-biomass-data/app/public/data/trilateral/LIS_Global_DA_Evap.md
https://github.com/eurodatacube/eodash/blob/adding-biomass-data/app/public/data/trilateral/HLS_NDVI.md

cc @santilland

**Comment by lubojr** [comment]
Is published at https://eodashboard.org/story?id=forests-on-the-brink
