### ISSUE TITLE
Analysis panel additional developments

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2399]
Problems:

- The flow of the analysis to be performed by the user is not so clear on the first sight and is mixed based on method:
Some guidance is given by the customAreaChart placeholder window, some is behind an I icon for admin unit selection based analysis
![image](https://github.com/eurodatacube/eodash/assets/19269667/c7484dad-7ea9-437c-a4ae-188da88fc03d)
![image](https://github.com/eurodatacube/eodash/assets/19269667/4b861dff-c2b5-45ab-861a-fc32802e4d65)

- Draw custom area buttons are outside of the analysis panel, but could be in.

- Custom chart (for wind speed average for example) should be below the filtering options, rather than appear on top

Possible solutions: 

Divide the analysis possible in functionality groups, which names shall be smaller than Panel title, capital letters.

First group: 		FILTERS
Second Group:	GEOGRAPHIC SELECTION
Third Group:		COMPARE

The titles of these groups in the Analysis Panel shall be made visible only when the Tool provides those functionalities. When not, they should not appear at all.

For all tools which have a mouse hover window with statistics popping up, these statistics shall be printed in the Analysis Panel, specifically in the Geographic Selection group.

“Export best zones” & “Create report” functionalities buttons to be placed at the bottom of the Analysis Panel.

See images below for suggestions on a new graphic layout for the Analysis panel and an alternative integration of the time bar (in the layers panel) and compare function (in the analysis panel).

![image](https://github.com/eurodatacube/eodash/assets/19269667/361da193-4978-4fe0-b313-172271d25f9b)

![image](https://github.com/eurodatacube/eodash/assets/19269667/361da193-4978-4fe0-b313-172271d25f9b)

**Comment by santilland** [comment]
Topics have been discussed and implemented.
Missing points created as separate issues:
#2453 #2454 #2455 
If other items are considered open, please open dedicated issues.
Closing this issue.
