### ISSUE TITLE
Energy, solar: change sliders from stretch to filter

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#2404]
the current approach of combining the value stretch with the filtering is not working. 

It would be better to switch to fix the stretch and make the slider perform a filtering, like we recently did for the AGB carbon maps.... 

![Image](https://github.com/eurodatacube/eodash/assets/40148967/d9b30f03-984c-4b62-aa5c-83948553f0c8)

**Comment by lubojr** [comment]
Done in 47179f3c0debe8fdf5ca51db5a2d31b8ff68e7a0
