### ISSUE TITLE
Chart not generated on Water Quality Maps from JAXA

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2416]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?x=15300016.53679&amp;y=4149661.81678&amp;z=9.16314&amp;clusterOpen=1&amp;poi=JP02TSM-N3a2&amp;search=Kobe%3A+TSM+concentration+%28GCOM-W%29&amp;area=POLYGON%28%28135.16484727102215+34.5195747614747%2C135.2652511838465+34.5195747614747%2C135.2652511838465+34.58253464680726%2C135.16484727102215+34.58253464680726%2C135.16484727102215+34.5195747614747%29%29">https://www.eodashboard.org/explore?x=15300016.53679&amp;y=4149661.81678&amp;z=9.16314&amp;clusterOpen=1&amp;poi=JP02TSM-N3a2&amp;search=Kobe%3A+TSM+concentration+%28GCOM-W%29&amp;area=POLYGON%28%28135.16484727102215+34.5195747614747%2C135.2652511838465+34.5195747614747%2C135.2652511838465+34.58253464680726%2C135.16484727102215+34.58253464680726%2C135.16484727102215+34.5195747614747%29%29</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 119</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://www.eodashboard.org/explore?x=15300016.53679&amp;y=4149661.81678&amp;z=9.16314&amp;clusterOpen=1&amp;poi=JP02TSM-N3a2&amp;search=Kobe%3A+TSM+concentration+%28GCOM-W%29&amp;area=POLYGON%28%28135.16484727102215+34.5195747614747%2C135.2652511838465+34.5195747614747%2C135.2652511838465+34.58253464680726%2C135.16484727102215+34.58253464680726%2C135.16484727102215+34.5195747614747%29%29">https://www.eodashboard.org/explore?x=15300016.53679&amp;y=4149661.81678&amp;z=9.16314&amp;clusterOpen=1&amp;poi=JP02TSM-N3a2&amp;search=Kobe%3A+TSM+concentration+%28GCOM-W%29&amp;area=POLYGON%28%28135.16484727102215+34.5195747614747%2C135.2652511838465+34.5195747614747%2C135.2652511838465+34.58253464680726%2C135.16484727102215+34.58253464680726%2C135.16484727102215+34.5195747614747%29%29</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Chart is generated</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by santilland** [comment]
Thank you for letting us know @aapopescu 
It is strange, the statistical api responds without errors, but the responses are all empty (empty array), so there is nothing to show.
Will need to investigate why this is the case, issue created here https://github.com/eurodatacube/eodash/issues/2417
I think if ok by you we can close this issue and continue investigation in the bug report
