### ISSUE TITLE
Review Legends in GTIF

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2420]
Current list of used color legends should be harmonized:

Go through all legends found in folders at https://github.com/eurodatacube/eodash-assets/tree/main/collections which are relevant for GTIF. The automatically generated legends are called cm_legend.png Data provider supplied legends are named with other possible names.

If a new legend is to be added for a dataset which did not have it yet, the file needs to be added in the assets repository to a folder for that collection and additionally a corresponding configuration YAML at https://github.com/eurodatacube/eodash-catalog/tree/main/collections needs to be modified like so https://github.com/eurodatacube/eodash-catalog/blob/main/collections/AQ1_1_aggregated_mobility_data_satellite_values.yaml#L22 (adding the reference to a file inside assets repository).

Most of those legends which were generated by us are defined in https://github.com/eurodatacube/eodash-assets/blob/813577dc4396452546ec94962e60de22aefdffa9/generators/legends.json#L167-L173 and are generated automatically by a script.

You can modify the value ranges there and the label for example or add new entries, where the key of the configuration object will be the folder in which a `cm_legend.png` will be created - ideally the same name as the collection configuration yaml.

Progress sheet sent via email.

Current legends also observable on https://radiantearth.github.io/stac-browser/#/external/eurodatacube.github.io/eodash-catalog/GTIF/catalog.json?.language=en

**Comment by lubojr** [comment]
to look like: [unit of measurement], at least 4 ticks, no name of a layer

discrete legends should be referenced remotely rather than autogenerated

**Comment by lubojr** [comment]
Legends are filled now and we are waiting for data providers response on used color ranges for ADO, EO4A, LST

**Comment by mariangela-cataldo** [comment]
Here are indications on the expected graphic appearance of legends (both color bars and discrete legends) in the LAYERS panel. 

Do we need to provide specific image files for the discrete legends or you can align those you have to the suggested style? If we need to do this, please let us know: file format (.png?), dimension constraints for effective responsiveness if any.   

![color bar](https://github.com/eurodatacube/eodash/assets/115264145/1bebf2e7-a6b1-4369-b3d6-5746fa5a4607)
![discrete legend](https://github.com/eurodatacube/eodash/assets/115264145/e929bf66-8ffe-4c99-b97d-df724c384bd6)

**Comment by lubojr** [comment]
@mariangela-cataldo The source library matplotlib in the way how we use does allow some customization but not all.

Specifically:
- Label [W/m2] can be moved only along the longer axis - so we can move it to the left bottom border or to the right bottom border, but we can not move it vertically. :x: 
- we changed ticks to go inout instead of only out :heavy_check_mark: 
- regarding color of ticks and tick labels - is this black (as is now) or some other color? :question: 
- From mockup, I assume background of the colorbar should be grey, so changed it to transparent in the source PNG (any color of background HTML element that the legend is being placed on will be seen) :heavy_check_mark:
- is the tick label size ok now or should it be smaller ? :question:

What we can change is how many labels we display (for non-linear colorscales, I tried to map every different discrete value to the specific used color). If you need any changes in the existing legends regarding this, let me know.

As for discrete legends, we do not have any other way at the moment to generate discrete values legends than for example this way:
![image](https://github.com/eurodatacube/eodash/assets/19269667/c5502c3c-f501-464b-8dea-72ccafca1b27)

If you prefer other format, please send us a per-tool legends as PNGs. Our legends currently have sizes roughly as 700x150px.

**Comment by lubojr** [comment]
Discrete legends provided via email have been added.

**Comment by lubojr** [comment]
Pending points: 

As for the continuous legends we are automatically generating, suggest is to align them graphically to the discrete ones by:

- [ ] Removing the black outline of bar
- [ ] Using grey (#87898b) for ticks and all text/numbers
- [ ] Using NotesESA fonts for text/numbers

**Comment by lubojr** [comment]
All points have been addressed and new generated legend assets were deployed. https://github.com/eurodatacube/eodash-assets/commit/6b4a6c8128bdfade175822fe703a39c47d19fe93
