### ISSUE TITLE
additional field in air quality time series

### ISSUE THREAD

**Issue by Antonio-Romeo** [eurodatacube/eodash#243]
We have been asked by the air quality team to report in the time series also:
-max
-min
-median
-standard deviation
-percentage of pixels used

would it be possible to possible to plot this information and pass them to the dashboard as an array in the reference value column in the csv?

**Comment by Schpidi** [comment]
agreed during today's call to store this information as array in the "Measurement Value" column comparable to what we do already in N3 for the "Reference value".

**Comment by Schpidi** [comment]
@aapopescu I believe this can be closed right?
