### ISSUE TITLE
IDEAS: Indicators next release

### ISSUE THREAD

**Issue by UndeadFairy** [eurodatacube/eodash#2434]
For next milestone, we need to add new indicators:

## Indicator 1 - Air polution
- raster file as COG :heavy_check_mark: 
- dispaly all layers :heavy_check_mark: 
- possible also use minesweeper over this indicator

## Indicator 2 - Wildlife
- raster file as COG :heavy_check_mark: 
- gamification over biodiversity score :heavy_check_mark: 
- display other layers :heavy_check_mark: 

## Indicator 3 
- unclear what will be delivered for now

## Indicator 4 - Flood risk
- new auxiliary data delivered to bucket 
  - [x] World Population
  - [x] World Cereals
- Implement https://github.com/eurodatacube/eodash/issues/2385

**Comment by UndeadFairy** [comment]
Update after meeting: 

## Indicator 1 - Air polution
- add other layers used for indicator creation visible
- display all layers 
- use minesweeper over this indicator as well

## Indicator 2 - Wildlife
- minesweeper: adding more information on cells (needs to be iterated), high level e.g. info on the preselected area for specific squares, highly "valuable" species info, ...
- display other layers used for indicator creation

## Indicator 3 
- no update

## Indicator 4 - Flood risk
- new auxiliary data delivered to bucket and display for indicator
  - [ ] World Population
  - [ ] World Cereals
- Implement https://github.com/eurodatacube/eodash/issues/2385 
- legend, description
- ideally add year as another selection parameter under scenarios
- If possible, comparison mode of scenarios/years
- remove orange colour and make that part transparent

**Comment by lubojr** [comment]
TODO:

- [ ] i3: 2 legends missing
- [ ] i3: markdown
- [ ] i3: globalImage 
- [ ] i2: update markdown
- [ ] i2: random mines
- [ ] i2: custom loading of popup for animals (csv + geojson)
- [ ] i1: update markdown
- [ ] i1: update visualisation

**Comment by UndeadFairy** [comment]
- [ ] i3: add maize and winter cereal overlay layers @lubojr

**Comment by UndeadFairy** [comment]
- [ ] compare mode for indicator 1 and indicator 3 is not working @lubojr

**Comment by lubojr** [comment]
With https://github.com/eurodatacube/eodash/pull/2551 All parts are done. Closing issue
