### ISSUE TITLE
Polar dashboard datasets

### ISSUE THREAD

**Issue by UndeadFairy** [eurodatacube/eodash#2445]
nitial request for CMEMS data in the Polar Dashboard.
Product ID ARCTIC_ANALYSISFORECAST_PHY_002_001:
https://data.marine.copernicus.eu/product/ARCTIC_ANALYSISFORECAST_PHY_002_001/description :heavy_check_mark: 
- Age of sea ice (SIAGE)
- Sea ice area fraction
- Sea ice thickness (SIT)
- Sea ice x velocity (SIUV)
- Sea ice y velocity (SIUV)
- Sea water x velocity (UV)
- Sea water y velocity (UV)
- Surface snow thickness (SNOW)

Product ID ARCTIC_MULTIYEAR_PHY_002_003:
https://data.marine.copernicus.eu/product/ARCTIC_MULTIYEAR_PHY_002_003/description
- Eastward sea ice velocity[m/s]
- Eastward sea water velocity[m/s]
- Northward sea ice velocity[m/s]
- Northward sea water velocity[m/s]
- Sea ice area fraction
- Sea ice thickness[m]
- Sea ice velocity[m/s]
- Sea water velocity[m/s]
- Surface snow thickness[m]

**Comment by lubojr** [comment]
Datasets are integrated on a `polar` branch as a Demo Mode with `id=polartep` and deployed under [polardashboard.org](polardashboard.org) and [polar-eodash.ows.eox.at](https://eodash-polar.eox.at/)
Corresponding catalog can be browsed: https://radiantearth.github.io/stac-browser/#/external/eurodatacube.github.io/eodash-catalog/polar/catalog.json?.language=en 

Follow-up enhancement issues created:

https://github.com/eurodatacube/eodash/issues/2484
https://github.com/eurodatacube/eodash/issues/2485
