### ISSUE TITLE
information shown on poi hover

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#245]
currently the hover over a poi shows:
- City
- Description
- Latest value

With this information there is no way to distinguish for example between North Adriatic maps from ESA and NASA:

![Screenshot from 2020-06-17 12-59-22](https://user-images.githubusercontent.com/482265/84890354-9507f400-b09a-11ea-8b60-857fe7fa502c.png)

![Screenshot from 2020-06-17 12-59-15](https://user-images.githubusercontent.com/482265/84890362-9802e480-b09a-11ea-9535-db519aa178a9.png)

@aapopescu should we add "Indicator Name" which is used for the sub-title?

**Comment by aapopescu** [comment]
@Schpidi , can we change the hover to display the sensor instead of latest value?

@lubojr, the Air Quality does not have CSV for these maps, I guess we need to set the description parameter to be the same in config, right?

**Comment by Schpidi** [comment]
I believe in an earlier discussion we decided to show the latest value in order to kind of explain the color of the poi but sure, we can change it

**Comment by lubojr** [comment]
Correct, we can set the description in the config to be the same for all Air Qualities. And in order to differentiate them on the map, we could add Indicator Name or switch that for description?
Change hover to display sensor instead of latest value for air quality only or all indicators?

**Comment by Schpidi** [comment]
solved by extending the "City" for these cases
