### ISSUE TITLE
Use different markers for S1 vs S2 observations (Hydropower tools)

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2463]

**Comment by lubojr** [comment]
![image](https://github.com/eurodatacube/eodash/assets/19269667/9d8bf7d9-a9ee-4f8d-a84c-6e99a7dcabb1) ref https://github.com/eurodatacube/eodash/issues/2318

**Comment by lubojr** [comment]
implemented in ae7a318b13b2a6595c8830c66de3b738bad3f7ff
