### ISSUE TITLE
Add Protected areas outlines layer

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2465]
From #2440 
Energy tools: for excluded protected areas, show PA boundaries and keep them visible (e.g. green outlines)

**Comment by lubojr** [comment]
ref https://github.com/eurodatacube/eodash/issues/2246

**Comment by patrick-griffiths** [comment]
@lubojr vector geometries could be made available, if this made it easier.. 
Let us know..

**Comment by santilland** [comment]
@patrick-griffiths vector geometries would for sure be helpful! We could load them as geometries instead of raster

**Comment by Patrick1G** [comment]
@kegro could you provide us the vector geometries for the protected areas we used to create the "exclude protected areas" from the wind turbine analysis? This might also allow us to differentiate between e.g. national parks and natura2000 sites.. 
cc @FranLeonelli

**Comment by santilland** [comment]
Protection areas have been ingested and published. Issues appeared in ingestion and publication on gedb, have been solved now.
Layer now available in test branch, ready to be merged:
https://gtif-testing.eox.at/gtif_protectionareas/

**Comment by Patrick1G** [comment]
@jamesemwheeler please see above

**Comment by santilland** [comment]
Look into having protected area name shown on hover

**Comment by lubojr** [comment]
Integrated in https://github.com/eurodatacube/eodash/pull/2634

Needed to move the protected areas to analysis layers otherwise tooltip can not be configured now, I hope that is fine
https://gtif-testing.eox.at/protected-areas-tooltips/?indicator=REP1_1
