### ISSUE TITLE
gzip compress assets on cloudfront

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#247]
we are not serving assets gzipped, this increases size of some files, that user needs to download even tenfold
at least css and js files should be served gzipped

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

**Comment by Schpidi** [comment]
good point. enabled in staging. please test.

**Comment by lubojr** [comment]
Thanks. Closing issue
