### ISSUE TITLE
Custom layer for Snow_water_equivalent does not work

### ISSUE THREAD

**Issue by Patrick1G** [eurodatacube/eodash#2477]
When trying to add a timeslice of the Snow_water_equivalent product (e.g. 19-02-21) as a custom layer, and reuse this in a other GTIF tool, such as Hydropower SWE daily this does not load... 

The same is true for Snowdepth which does not load as custom layer, 
while Heat Explorer (also WMS based) does load...

**Comment by lubojr** [comment]
fixed in 16cabb04819f33a724ace3b9fb4ab4bd09f2aec1 - TIME parameter was not passed correctly for Custom layers
