### ISSUE TITLE
search location by name

### ISSUE THREAD

**Issue by Patrick1G** [eurodatacube/eodash#2483]
support search by place name would still be valuable. 

I remember that we discussed this some time ago, and it was a bit more tricky as it required an additional service. 

Any news on such a feature? 
Could this help:? https://osmnames.org/api/

**Comment by santilland** [comment]
This feature has been discussed some times, setting up a gazetteer is not a trivial task.
The resource you link seems interesting, as it seems to provide a good starting point. We will look into it.

**Comment by santilland** [comment]
Implementation integrated with https://github.com/eurodatacube/eodash/pull/2615
"Highlights" entries have been removed as requested, as it is now possible to navigate using the location search
