### ISSUE TITLE
Layercontrol JSONForm parameter update clashes with XYZ Source time manipulation

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2485]
Observed in trilateral RECCAP2 XCube server services and polar dashboard Copernicus Marine Data Store datasets.

With the current implementation which uses tileUrlFunction for updating time to work with some specialized XYZ services with some necessary workarounds clashes with the JSONForm in LayerControl functionality for updating the XYZ Source url directly, which uses the setUrl.

**Comment by aapopescu** [comment]
@santilland  can we close?

**Comment by santilland** [comment]
We updated the logic of the tileUrlFunction, so yes, this should be ok to be closed
