### ISSUE TITLE
Overpass API - new tags

### ISSUE THREAD

**Issue by UndeadFairy** [eurodatacube/eodash#2497]
During today meeting we discussed the need to add more OSM tags for Overpass API selection for indicator 4 - Flood risk. 

Lets's collect here what would be interest. Currently we have school and hospital only.

@sistemagmbh @alexaib please add you ideas to this issue.

**Comment by UndeadFairy** [comment]
Based on email from Alexandra, we will add only "building"="residential" and "man_made"="storage_tank" tags

**Comment by lubojr** [comment]
Number of "building"="residential" will be absolutely massive for the client to handle to be usable on anything above a size of a small town although I understand the possible importance.

We can limit the total number of features returned and show a warning https://help.openstreetmap.org/questions/20472/how-to-request-a-limited-no-of-features-in-overpass-api but this will be shared for all requested types of features, not just buildings.

**Comment by alexaib** [comment]
@lubojr  for the "building"="residential" is it possible to show a warning to the user that the chosen area is too large for this feature and a smaller area has to be chosen, instead of limiting the total number of features?

**Comment by lubojr** [comment]
We do not have the framework in place to show custom warnings for a single type of feature and when drawn area is greater than some threshold.
I think adding such custom one-off functionality is not desirable in current state of the demonstrator.

I would suggest a counter proposal - to add the "building"="residential" as a possible new tag, but leave it switched "off" as default.

**Comment by alexaib** [comment]
@lubojr your proposal sounds good

**Comment by lubojr** [comment]
Implemented and deployed in `ideas_i4` branch
