### ISSUE TITLE
Correction to JAXA Indicator

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2503]
Indicator name should be "GOSAT - Carbon Dioxide"

https://www.eodashboard.org/explore?search=New+Delhi%3A+Partial+Column+%28GOSAT+FTS+L1B+V220.220%29&x=8639831.10393&y=3333024.8838&z=10.39679&poi=IN01-N2 

Same for all 
![Image](https://github.com/eurodatacube/eodash/assets/35488732/6e87b1f6-5556-4bcc-a200-6907e00aa7ee)

**Comment by lubojr** [comment]
corrected in the corresponding YAML
