### ISSUE TITLE
CAMS maps not loading

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2523]
Latest Data is not loading for the CAMS datasets. Older dates work

https://race.esa.int/?x=4213377.17174&y=7510461.57021&z=3.48675&poi=GCAQ4-N1b&search=World%3A+Ozone+map+Europe+%28CAMS%29 

https://race.esa.int/?x=4213377.17174&y=7510461.57021&z=3.48675&poi=GCAQ1-N1b&search=World%3A+City+level+NO2+%28model%29

https://race.esa.int/?x=4213377.17174&y=7510461.57021&z=3.48675&poi=GCAQ2-N1b&search=World%3A+PM2.5+map+Europe+%28CAMS%29

https://race.esa.int/?x=4260970.83528&y=7590676.0322&z=3.42342&poi=GCAQ3-N1b&search=World%3A+PM10+map+Europe+%28CAMS%29

https://race.esa.int/?x=4260970.83528&y=7590676.0322&z=3.42342&poi=GCAQ3-N1b&search=World%3A+PM10+map+Europe+%28CAMS%29

**Comment by lubojr** [comment]
@aapopescu yes, there are no new data produced since 2023-11-28 on this endpoint  - we have already fixed the dates config on staging, but this was not yet merged to production instance

https://github.com/eurodatacube/eodash/commit/d46c29779455e547045b62487fc87480f6f86d61
