### ISSUE TITLE
IDEAS Indicator 3

### ISSUE THREAD

**Issue by UndeadFairy** [eurodatacube/eodash#2525]
Integrate indicator 3 into the dashboard:

Overpass API tags:
rice - crop=rice landuse=farmland
sugarcane  - crop=sugarcane landuse=farmland
barley -  crop=barley landuse=farmland
vegetables -  crop=vegetable landuse=farmland :heavy_check_mark: 

Description and legend from email

Visualization:
Values has a range between 0 and 1, however most meaningful values are the one
above 70% of confidence. In order to represent the best the result, color table can
be represented between 0.7 and 1, everything below 0.7 can be set into a
transparent layer. :heavy_check_mark:

**Comment by lubojr** [comment]
Is integrated. Closing
