### ISSUE TITLE
COUNTDOWN for Trilateral Public Release

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#254]
Link to go live without password on 25 June at 13:30 CET
Countdown to be online 24 hours before this.

**Comment by silvester-pari** [comment]
added countdown timer in https://github.com/eurodatacube/eodash/commit/d5e82e3d4c1ad54227b7163c008b8bf6ba759000, but still needs updates regarding key visual (re-used ESA one for now)

**Comment by aapopescu** [comment]
Yves-Louis is handling the key visual, will update as soon as we have the new one.

**Comment by Schpidi** [comment]
@silvester-pari please use the same visual as currently used in the about

**Comment by silvester-pari** [comment]
added in https://github.com/eurodatacube/eodash/commit/04b6098ef4778d63b9d8cde787eef68b40b3fadd

**Comment by Schpidi** [comment]
use latest visual in 60e56c7
