### ISSUE TITLE
Can not see the Ocean Color Plankton maps on Race

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2541]
in Race dashboard, I searched for Ocean and selected the Ocean Colour Plankton...

maps are not displayed in the map.

![image](https://github.com/eurodatacube/eodash/assets/65602207/f3d2d4d5-a5df-4e2e-9cb2-c9f822ab61a5)

**Comment by lubojr** [comment]
@AlessandroScremin thank you for feedback. This is already tracked in https://github.com/eurodatacube/eodash-catalog/issues/86 where I asked you for feedback which should be a new URL after the cmems servers migration. Could you please advise there ?

**Comment by lubojr** [comment]
PR is merged
