### ISSUE TITLE
Charts on the right panel of the race dahbboard can not be expanded or maximized in the screen

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2542]
Race dashboard

if i select an indicaotr with charts (eg Sea surface temperature time series)

the chart shown is quite small and can not be enlarged or expanded to max screen

![image](https://github.com/eurodatacube/eodash/assets/65602207/e7794c80-2967-4ce5-bcc2-2441e660f255)

**Comment by lubojr** [comment]
Chart can now be made fullscreen. Further enhancements of the chart visibility are possible but would be more involved in terms if implementation.
