### ISSUE TITLE
Custom chart not working on JAXA WQ maps

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2567]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?indicator=N3a2_TSM_jaxa&poi=JP01-N3a2_TSM_jaxa&area=POLYGON%28%28139.87707589481602+35.48087241841054%2C139.91121125527928+35.48087241841054%2C139.91121125527928+35.513942267667204%2C139.87707589481602+35.513942267667204%2C139.87707589481602+35.48087241841054%29%29&x=15556898.83836&y=4206754.22014&z=10.28924">https://www.eodashboard.org/explore?indicator=N3a2_TSM_jaxa&amp;poi=JP01-N3a2_TSM_jaxa&amp;area=POLYGON%28%28139.87707589481602+35.48087241841054%2C139.91121125527928+35.48087241841054%2C139.91121125527928+35.513942267667204%2C139.87707589481602+35.513942267667204%2C139.87707589481602+35.48087241841054%29%29&amp;x=15556898.83836&amp;y=4206754.22014&amp;z=10.28924</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 124</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://www.eodashboard.org/explore?indicator=N3a2_TSM_jaxa&poi=JP01-N3a2_TSM_jaxa&area=POLYGON%28%28139.87707589481602+35.48087241841054%2C139.91121125527928+35.48087241841054%2C139.91121125527928+35.513942267667204%2C139.87707589481602+35.513942267667204%2C139.87707589481602+35.48087241841054%29%29&x=15556898.83836&y=4206754.22014&z=10.28924">https://www.eodashboard.org/explore?indicator=N3a2_TSM_jaxa&amp;poi=JP01-N3a2_TSM_jaxa&amp;area=POLYGON%28%28139.87707589481602+35.48087241841054%2C139.91121125527928+35.48087241841054%2C139.91121125527928+35.513942267667204%2C139.87707589481602+35.513942267667204%2C139.87707589481602+35.48087241841054%29%29&amp;x=15556898.83836&amp;y=4206754.22014&amp;z=10.28924</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>chart is generated</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Will be fixed in the source catalog in https://github.com/eurodatacube/eodash-catalog/commit/a3f7e6fd3e64a750fba77566ffd5dfc5b4062bce

essentially a port of original fix https://github.com/eurodatacube/eodash/commit/a4d28fd08cc534e20de9c46cd4425abd45601fc3 to catalog

fyi @aapopescu

**Comment by lubojr** [comment]
fixed in https://github.com/eurodatacube/eodash-assets/commit/740cd89511c369f2fcefde09d1d2cd2368ca8a89

Sorry for an oversight.
