### ISSUE TITLE
Custom chart should be disabled on Landsat-8 data

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2568]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?indicator=NLK&x=15501239.09296&y=4143515.38091&z=3.47371&clusterOpen=1&poi=NLK_lake_vanern-NLK&area=POLYGON%28%2812.885871130902075%2058.78227679879839,13.285938822950078%2058.78227679879839,13.285938822950078%2058.89974241794957,12.885871130902075%2058.89974241794957,12.885871130902075%2058.78227679879839%29%29">https://www.eodashboard.org/explore?indicator=NLK&amp;x=15501239.09296&amp;y=4143515.38091&amp;z=3.47371&amp;clusterOpen=1&amp;poi=NLK_lake_vanern-NLK&amp;area=POLYGON%28%2812.885871130902075%2058.78227679879839,13.285938822950078%2058.78227679879839,13.285938822950078%2058.89974241794957,12.885871130902075%2058.89974241794957,12.885871130902075%2058.78227679879839%29%29</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 124</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://www.eodashboard.org/explore?indicator=NLK&x=15501239.09296&y=4143515.38091&z=3.47371&clusterOpen=1&poi=NLK_lake_vanern-NLK&area=POLYGON%28%2812.885871130902075%2058.78227679879839,13.285938822950078%2058.78227679879839,13.285938822950078%2058.89974241794957,12.885871130902075%2058.89974241794957,12.885871130902075%2058.78227679879839%29%29">https://www.eodashboard.org/explore?indicator=NLK&amp;x=15501239.09296&amp;y=4143515.38091&amp;z=3.47371&amp;clusterOpen=1&amp;poi=NLK_lake_vanern-NLK&amp;area=POLYGON%28%2812.885871130902075%2058.78227679879839,13.285938822950078%2058.78227679879839,13.285938822950078%2058.89974241794957,12.885871130902075%2058.89974241794957,12.885871130902075%2058.78227679879839%29%29</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>custom chart should be disable on this one</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Will be fixed in the source catalog update in https://github.com/eurodatacube/eodash-catalog/commit/f3491f7850c72d30e410cdbc4a39e4358d8d0f33
cc @aapopescu
