### ISSUE TITLE
Polardashboard: Ice charts

### ISSUE THREAD

**Issue by UndeadFairy** [eurodatacube/eodash#2569]
Currently we display sample Ice Charts from DMI and ice fractions form CMEMS. Couple of improvements could be done:

- base maps for polar projection end on one side directly at the south tip of Greenland. Would that be possible to enlarge the are to cover also see below this? Would we need to ask cartography department for map update? :heavy_check_mark: 

- Ice franctions and ice chart data are displaying "same" information. Would that be possible to unify the color map to use the one from ice charts? 

- Ice chart layer should also use polar projection, not mercator. But in case we are not able to display south of Greenland properly, we need to find better solution.

**Comment by lubojr** [comment]
Obsolete now I think as we are moving to eodash v5 version
