### ISSUE TITLE
HR Soil Moisture Product from Sentinel-1

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2577]
Please add this dataset https://stac.eurac.edu:8080/collections/SM_RT

**Comment by lubojr** [comment]
@AlessandroScremin @FedericoRondoni Could you please create a metadata collection YAML for this dataset? We will add the data/resource handling.
@aapopescu:
- until when it should be integrated?
- into which catalog/instance?
- any special remarks about rendering? I see that it is daily 5 year time series over a set of locations for COG data with 0-1 range
  - are we fine with only rendering or do we need custom area chart to display time series?
  - if we need time series chart, we will need this to be ingested to SH

**Comment by aapopescu** [comment]
> @AlessandroScremin @FedericoRondoni Could you please create a metadata collection YAML for this dataset? We will add the data/resource handling. @aapopescu:
> 
> * until when it should be integrated? 
JUNE 2024
> * into which catalog/instance? 
RACE & TRILATERAL
> * any special remarks about rendering? I see that it is daily 5 year time series over a set of locations for COG data with 0-1 range
Same as here:
![Screenshot 2024-05-29 at 11 30 30](https://github.com/eurodatacube/eodash/assets/35488732/0f5f510b-d4cb-46f4-bb19-64b6f364a103)
>   
>   * are we fine with only rendering or do we need custom area chart to display time series?
With custom area
>   * if we need time series chart, we will need this to be ingested to SH

**Comment by lubojr** [comment]
Okay, so there is already a XCUBE API on top of the data ready, therefore we do not need to ingest data into Sentinel Hub.
FYI @AlessandroScremin @FedericoRondoni

@aapopescu I see that you have added an image from https://viewer.earthsystemdatalab.net/ - Should we use this URL for the integration of the tiles (xcube tiles api)? If yes should we use the STAC API from the https://stac.eurac.edu:8080/collections/SM_RT, meaning a different STAC endpoint than the tiles/time series endpoint?

**Comment by lubojr** [comment]
- [ ] Use ESDL https://viewer.earthsystemdatalab.net/ as a source, as it aggregates the different locations into one cube
- [ ] Investigate if we can we do temporal aggregation, weekly/monthly composite? - does the endpoint allow it?

**Comment by lubojr** [comment]
@aapopescu @FedericoRondoni We added a YAML for variable `Soil Moisture` in https://github.com/eurodatacube/eodash-catalog/pull/149 and https://github.com/eurodatacube/eodash-assets/pull/41
There are other 3 parameters `Evaporation, Snow Water Equivalent, Precipitation`, which we did not add.

Aggregation of data over time (e.g. monthly tiles) on the fly is not possible on the XCube-Server side.

Could you please have a look and review + merge? https://eodash-staging.eox.at/?catalog=ESDL_SMOS&indicator=ESDL_Hydrology_SM

**Comment by aapopescu** [comment]
> @aapopescu @FedericoRondoni We added a YAML for variable `Soil Moisture` in [eurodatacube/eodash-catalog#149](https://github.com/eurodatacube/eodash-catalog/pull/149) and [eurodatacube/eodash-assets#41](https://github.com/eurodatacube/eodash-assets/pull/41) There are other 3 parameters `Evaporation, Snow Water Equivalent, Precipitation`, which we did not add. Should we?
> 
> Aggregation of data over time (e.g. monthly tiles) on the fly is not possible on the XCube-Server side.
> 
> Could you please have a look and review + merge? https://eodash-staging.eox.at/?catalog=ESDL_SMOS&indicator=ESDL_Hydrology_SM

Thank you, @lubojr. 
The legend is not loading.
@FedericoRondoni , the description needs to be updated

**Comment by lubojr** [comment]
@aapopescu Thank you for a review.
The legend should now load (I merged the respective eodash-assets PR) and added the `Precipitation` variable with the same styling as the ESDL now has.

https://eodash-staging.eox.at/?catalog=ESDL_SMOS&indicator=ESDL_Hydrology_Precipitation

@FedericoRondoni Descriptions are here:

- https://github.com/eurodatacube/eodash-assets/blob/main/collections/ESDL_Hydrology_Precipitation/ESDL_Hydrology_Precipitation.md

- https://github.com/eurodatacube/eodash-assets/blob/main/collections/ESDL_Hydrology_SM/ESDL_Hydrology_SM.md

**Comment by lubojr** [comment]
Integration finished
