### ISSUE TITLE
Missing Sentinel-1 data

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2579]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/?indicator=E8&poi=DE28-E8&x=752296.10735&y=6334661.38207&z=14.85168&clusterOpen=1">https://race.esa.int/?indicator=E8&amp;poi=DE28-E8&amp;x=752296.10735&amp;y=6334661.38207&amp;z=14.85168&amp;clusterOpen=1</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 125</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://race.esa.int/?indicator=E8&poi=DE28-E8&x=752296.10735&y=6334661.38207&z=14.85168&clusterOpen=1">https://race.esa.int/?indicator=E8&amp;poi=DE28-E8&amp;x=752296.10735&amp;y=6334661.38207&amp;z=14.85168&amp;clusterOpen=1</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Sentinel-1 imagery should load on the map <a target="_blank"  href="https://race.esa.int/?indicator=E8&poi=DE28-E8&x=752296.10735&y=6334661.38207&z=14.85168&clusterOpen=1">https://race.esa.int/?indicator=E8&amp;poi=DE28-E8&amp;x=752296.10735&amp;y=6334661.38207&amp;z=14.85168&amp;clusterOpen=1</a></p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>anca</p>

**Comment by lubojr** [comment]
Confirming a fix in staging and closing the issue.
