### ISSUE TITLE
sentinel-1 data not loading

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2588]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/?indicator=E5&poi=FI3-E5&x=3206118.5931&y=8659108.7741&z=18">https://race.esa.int/?indicator=E5&amp;poi=FI3-E5&amp;x=3206118.5931&amp;y=8659108.7741&amp;z=18</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 125</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://race.esa.int/?indicator=E5&poi=FI3-E5&x=3206118.5931&y=8659108.7741&z=18">https://race.esa.int/?indicator=E5&amp;poi=FI3-E5&amp;x=3206118.5931&amp;y=8659108.7741&amp;z=18</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>senitnel-1 should be one data layer</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>anca</p>

**Comment by lubojr** [comment]
@aapopescu We had an incorrect configuration of TIME parameter formatting for S1GRD layer. Fixed now in staging. Closing the issue.
