### ISSUE TITLE
NASA Nitrogen Dioxide collections updated

### ISSUE THREAD

**Issue by j08lue** [eurodatacube/eodash#2590]
The Nitrogen Dioxide collections have received new data today.

https://github.com/eurodatacube/eodash/blob/38e1d84aba87a5475c2bb7a55d4cf04588478db3/app/src/scripts/generate_files.py#L167-L168

Will the EO Dashboard pull the updates automatically into your static STAC JSON cache, or does it need a manual trigger?

Either way, would be great to see the new data in EO Dashboard soon. 😄 🚀

**Comment by lubojr** [comment]
Thank you for the heads up!
No the catalog cache is not yet generated regularly (e.g. daily/weekly), but only when we push to `main` (change some metadata definitions or add new collections). I have now manually triggered the catalog build, so "soon" the data will be in the production EO Dashboard! :)

**Comment by j08lue** [comment]
Thanks, @lubojr!

Just curious - why are you keeping a cached version? Do you add any information to the collections?

**Comment by lubojr** [comment]
We are generating our own static catalogs based on existing STAC collections and other types of datasources with sometimes a custom structure for multiple reasons:

- adding custom metadata that we either need or standard metadata that are missing in the source endpoints
- subsetting parts of existing collections by date/area
- generating STAC collections for non-stac source data that are not under our control and we just reference them
