### ISSUE TITLE
TROPOMI NO2 Maps not loading

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2592]
https://race.esa.int/?indicator=N1_NO2&x=0&y=-626172.13571&z=3.32193

**Comment by lubojr** [comment]
@AlessandroScremin Is seems like the data ingested look somehow differently now. Last working date is 1.4.2024, the newer ones show only transparent WMS requests.

**Comment by AlessandroScremin** [comment]
dear @aapopescu @lubojr 

the problem should be solved now.

the imges ingested after 1 April were with min max values set to 0. I re-processed all the images from 1 of april and now should be correctly displayed in Race

**Comment by lubojr** [comment]
Thank you! Closing the issue
