### ISSUE TITLE
Add C3S Wind Data 100 m in EO Dashboard

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2597]
Please add this dataset:

https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form

ERA5 hourly data on single levels from 1940 to present
WIND
U and V, 
100m 
all months, daily averages, after converting to local time for New Delhi UTC+05.

**Comment by lubojr** [comment]
Hourly data from 1940 until today will be too many time entries for the dashboard to visualize in the date picker and too many requests for data for generation of the custom area chart and to let the user browse through it comfortably unless we do some time aggregations.

**Comment by santilland** [comment]
@AlessandroScremin will look into how daily average can be extracted (data just for 2023)

**Comment by AlessandroScremin** [comment]
Dear @aapopescu  and @lubojr 

These are the step Remaining to the full integration

- [x] Data ingestion over New Delhi (expanded a bit) for 2023, daily averages at 12:00.
- [x ] Evalscript and lauer generation in the SH Eodashboard Active collections
- [ ] Generation of the Yaml file
- [ ] Generation of the Md file 

sample of the visualisation on SH
![image](https://github.com/eurodatacube/eodash/assets/65602207/0c2bd901-a239-4e7f-9867-fc34bafb8456)

**Comment by AlessandroScremin** [comment]
@lubojr 

the eval script follows: (only bands are changing WindV100m and WindU100m)

//VERSION=3
function setup() {
  return {
    input: [{
      bands: ["WindV100m", "dataMask"], // this sets which bands to use
    }],
    output: { // this defines the output image type
      bands: 4,
      sampleType: "UINT8"
    }
  };
}

function evaluatePixel(sample) {

  var arr = colorBlend(sample.WindV100m,    [-4, -3, -2, -1, 0, 1, 2, 3, 4], [
    [11,53,135],
    [11,116,197],
    [78,181,250],
    [171,234,243],
    [244,252,237],
    [251,212,95],
    [247,133,0],
    [221,24,0],
    [163,1,0]
  ]); 

  if (sample.dataMask == 1) {
    arr.push(255);
  } else {
    arr.push(0);
  }

  return arr;
}

**Comment by AlessandroScremin** [comment]
@lubojr 

new pull request for Md file and Yaml

Yaml
https://github.com/eurodatacube/eodash-catalog/pull/162
https://github.com/eurodatacube/eodash-catalog/pull/161

md
https://github.com/eurodatacube/eodash-assets/pull/48
https://github.com/eurodatacube/eodash-assets/pull/47

**Comment by lubojr** [comment]
Legends and evascripts added.
