### ISSUE TITLE
add/review legal texts

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#260]
- [x] Legal
- [x] Privacy
- [x] Attributions
- [x] Cookie banner

**Comment by aapopescu** [comment]
terms and conditions are OK but the Tab name is still RAPID ACTION ON CORONAVIRUS AND EO, can we update this to be Earth Observing Dashboard?

<img width="838" alt="Screen Shot 2020-06-24 at 16 51 51" src="https://user-images.githubusercontent.com/35488732/85579320-0fa4b680-b63b-11ea-8d6f-0b3e775c5387.png">

**Comment by Schpidi** [comment]
done in 3fc45a1
