### ISSUE TITLE
NASA Nitrogen Dioxide yearly collection updated

### ISSUE THREAD

**Issue by j08lue** [eurodatacube/eodash#2609]
Thanks for the quick action a few weeks ago on

- https://github.com/eurodatacube/eodash/issues/2590

We now also updated the yearly product:

https://github.com/eurodatacube/eodash/blob/4af2069bbea710488e9832438454d4f5e7dd0699/app/src/scripts/generate_files.py#L171

**Comment by lubojr** [comment]
Thank you for the heads up, we have triggered a catalog rebuild.
