### ISSUE TITLE
Ice charts coloring

### ISSUE THREAD

**Issue by UndeadFairy** [eurodatacube/eodash#2610]
Ice charts derived from ML model     

![image](https://github.com/eurodatacube/eodash/assets/18370061/f69cdbd5-d898-4827-aef7-287a1e732619)

 should be colored using the same color scheme as ice charts from DMI
 
 
![image](https://github.com/eurodatacube/eodash/assets/18370061/021b30dc-4ad2-4826-a94c-7a3561dd5450)

**Comment by lubojr** [comment]
Done in https://github.com/eurodatacube/eodash/commit/768facaae3de34fa76f4cd6797b33c81f8759d5c
