### ISSUE TITLE
Display a map scale bar on the map

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#2611]
adding map scale information can help to better understand the spatial reslations and the scale at which the measurements are done

**Comment by lubojr** [comment]
Should be very easy to integrate using the ScaleLine control from https://openlayers.org/en/latest/examples/scale-line.html

**Comment by lubojr** [comment]
added in c7b0027982f8a63e7eb1fb58c2095e8311035440 to staging 
![image](https://github.com/eurodatacube/eodash/assets/19269667/db5445fb-a22a-4e7a-a26e-fdad242a3dbe)
