### ISSUE TITLE
Add sentinel-5p-l2-tropomi as layer to SH

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2616]
See:
https://collections.sentinel-hub.com/sentinel-5p-l2-tropomi/

Once added integrate layer to VIIRS/MODIS fire detections indicator

**Comment by AlessandroScremin** [comment]
Layer ID
TESTING_CO_FROM_SENTINELHUB

working example over Greece, 20230725 youshould have both S5P and S2

**Comment by lubojr** [comment]
It works fine to be added as a layer. @AlessandroScremin What is the used evalscript/color range so that we can generate a legend for this layer?

**Comment by AlessandroScremin** [comment]
> It works fine to be added as a layer. @AlessandroScremin What is the used evalscript/color range so that we can generate a legend for this layer?

Hi @lubojr 

the eval script is the following

//VERSION=3
var minVal = 0.0;
var maxVal = 0.1;
var diff = maxVal - minVal;
const map = [
	[minVal, 0x00007f], 
	[minVal + 0.125 * diff, 0x0000ff],
	[minVal + 0.375 * diff, 0x00ffff],
	[minVal + 0.625 * diff, 0xffff00],
	[minVal + 0.875 * diff, 0xff0000],
	[maxVal, 0x7f0000]
]; 

const visualizer = new ColorRampVisualizer(map)
function setup() {
   return {
    input: ["CO","dataMask"],
    output: { bands: 4 }
  };
}

function evaluatePixel(samples) {
   const [r, g, b] = visualizer.process(samples.CO);
   return [r, g, b, samples.dataMask];
}
