### ISSUE TITLE
Chart missing 

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2624]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?indicator=E13c&poi=BE3-E13c&x=419187.23804&y=6641005.45998&z=11.27015">https://www.eodashboard.org/explore?indicator=E13c&amp;poi=BE3-E13c&amp;x=419187.23804&amp;y=6641005.45998&amp;z=11.27015</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 126</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://www.eodashboard.org/explore?indicator=E13c&poi=BE3-E13c&x=419187.23804&y=6641005.45998&z=11.27015">https://www.eodashboard.org/explore?indicator=E13c&amp;poi=BE3-E13c&amp;x=419187.23804&amp;y=6641005.45998&amp;z=11.27015</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>chart area is visible but no data loads</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>anca</p>

**Comment by lubojr** [comment]
fixed in acf3f17a73d373911c8630ecede700abccccead8
