### ISSUE TITLE
Asparagus indicator

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#264]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 1.1.0</p>
<p><strong>Current URL:</strong> <a target='_blank'  href="https://race.esa.int/?poi=DE11-E10a3">https://race.esa.int/?poi=DE11-E10a3</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 12</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>display of the productive area change (as map) - there are two different AOI for this indicator one active another which still is indicating to be arriving soon. These should be joint...</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Only one AOI on the overview map for this indicator</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>No comments</p>

**Comment by Schpidi** [comment]
This might be a caching issue.

**Comment by lubojr** [comment]
Could not reproduce on race.esa.int on Safari 12.1. Probably was fixed since then.
