### ISSUE TITLE
Enable stories for RACE instance

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2643]
First expected story is for the CropOM data.
Intended approach is to enable the stories endpoint and initially only add the cropom story as "link" to the welcome popup.
We can try the setup in a branch with a dummy story to see if the approach works well

**Comment by lubojr** [comment]
First setup done in https://github.com/eurodatacube/eodash/commit/4a8d231f01b2f7785d4ea297929ebb485441c0ca
Tried attaching an existing story for agriculture theme and it worked.
