### ISSUE TITLE
Trilateral dashboard : Layer for MODIS fires disappears after trying to move up in the layer list

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2654]
@santilland @lubojr 

cc: @aapopescu @dmoglioni @FedericoRondoni 

When I search for modis fire, (https://eodashboard.org/explore?indicator=Modis_SNPP_2023&x=3300549.95032&y=4473090.15005&z=7.69931&area=POLYGON%28%2814.812500000000012+32.07748215822495%2C35.062500000000014+32.07748215822495%2C35.062500000000014+44.394915320248884%2C14.812500000000012+44.394915320248884%2C14.812500000000012+32.07748215822495%29%29)

i go to layers panel. There I noticed that the order of the layers hide the below layers.
I tried to move the modis fires layer up using the = sign below the three vertival points, and moved the layer up. Doing that the layer disappeared and can no be recovered anymore

do you know what happens?

![image](https://github.com/user-attachments/assets/17e5b608-97b9-4d39-ae53-052f260736f7)

instead of the normal ones

![image](https://github.com/user-attachments/assets/7dfb0b45-354d-40ca-9d4c-1c9af50fcdb6)

**Comment by santilland** [comment]
Thank you for reporting this, we can reproduce the issue and will investigate

**Comment by santilland** [comment]
Issue has been addressed with following pull request https://github.com/eurodatacube/eodash/pull/2657
