### ISSUE TITLE
adjust twitter handles in feedback overlay

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#267]
@aapopescu please advise which ones to use

**Comment by Schpidi** [comment]
@ESA_EO @esa @NASAEarth @NASA @JAXA_en @JAXA_jp

use all these

**Comment by silvester-pari** [comment]
added in https://github.com/eurodatacube/eodash/commit/e6ff93dbd7d53b5a5422cb992a16cec58e50d2eb
