### ISSUE TITLE
layer switcher icon not using primary/brand color

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#284]
![Screenshot from 2020-06-23 21-58-16](https://user-images.githubusercontent.com/482265/85454128-e2a1c680-b59c-11ea-9fa8-4c085e4f58f1.png)

**Comment by silvester-pari** [comment]
@Schpidi what is the expected outcome? should all the map controls including the zoom control (+/-) and the attribution (i) also be in primary color?

**Comment by silvester-pari** [comment]
fixed in https://github.com/eurodatacube/eodash/commit/57063022a5f4ce9caa230cde0f4ffe6baa96b4f8
