### ISSUE TITLE
zoom to sub-aoi only working on second click

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#313]
1st click on poi (Ghent moved to North, Dunkirk to West):
![Screenshot from 2020-06-24 21-43-24](https://user-images.githubusercontent.com/482265/85620252-cd439f80-b663-11ea-9469-f7ea123da7fe.png)
![Screenshot from 2020-06-24 21-43-38](https://user-images.githubusercontent.com/482265/85620257-d03e9000-b663-11ea-8f5a-b683c05db6aa.png)

2nd click on poi:
![Screenshot from 2020-06-24 21-43-32](https://user-images.githubusercontent.com/482265/85620270-d6347100-b663-11ea-8fc3-5ce0c0f16f32.png)
![Screenshot from 2020-06-24 21-43-45](https://user-images.githubusercontent.com/482265/85620276-d7fe3480-b663-11ea-9250-b1ae97c525f9.png)

**Comment by Schpidi** [comment]
seems the 1st click zooms to poi and 2nd click to sub-aoi

**Comment by aapopescu** [comment]
<img width="1680" alt="Screen Shot 2020-07-16 at 16 12 46" src="https://user-images.githubusercontent.com/35488732/87681751-4c1d8b00-c77f-11ea-809e-722b3652d494.png">
<img width="1680" alt="Screen Shot 2020-07-16 at 16 12 55" src="https://user-images.githubusercontent.com/35488732/87681760-4fb11200-c77f-11ea-96fe-9789f8622dfe.png">
