### ISSUE TITLE
Canda is not US

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#320]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 2.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://eodashboard.org/?indicator=N3b">https://eodashboard.org/?indicator=N3b</a></p>
<p><strong>Operating system:</strong> Windows OS</p>
<p><strong>Affected browser:</strong> Chrome 83</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Cannot see any indicators on Canadian map, Canada not a country to choose from?</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Canada has it&#39;s own Environment laws and should be represented equally</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p><a target="_blank"  href="mailto:&#x73;&#104;&#97;&#100;&#x65;&#x6f;&#110;&#x79;&#x78;&#x40;&#104;&#x6f;&#x74;&#109;&#x61;&#105;&#x6c;&#x2e;&#99;&#111;&#x6d;">&#x73;&#104;&#97;&#100;&#x65;&#x6f;&#110;&#x79;&#x78;&#x40;&#104;&#x6f;&#x74;&#109;&#x61;&#105;&#x6c;&#x2e;&#99;&#111;&#x6d;</a></p>

**Comment by aapopescu** [comment]
thank you for the suggestion, we're looking to increase the number of AOIs to cover new countries, including Canada
