### ISSUE TITLE
Confused on how to obtain different date comparisons

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#321]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 2.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://eodashboard.org/?poi=W2-N1&amp;indicator=E10a2">https://eodashboard.org/?poi=W2-N1&amp;indicator=E10a2</a></p>
<p><strong>Operating system:</strong> Windows OS</p>
<p><strong>Affected browser:</strong> Firefox 77</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>click &#39;Nightlights&#39;</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Interactive comparison in upper right to switch to Nightlights.<br>Actual: Stayed on NO2.<br> I had turned off uBlock Origin and F5 in case that might matter, and accepted all cookies, no change.</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>No comments</p>

**Comment by aapopescu** [comment]
To view indicator data for a given Point or Area of Interest the user must click on the POI on the map or select the indicator from the table view.
