### ISSUE TITLE
unify how time is displayed in EOData time selection lists

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#322]
current code is formatting nicely only if date is passed, otherwise leaves it be:
https://github.com/eurodatacube/eodash/blob/c62e79f0e2cbe76ebaeb3fa2c46947ab76eeb852/app/src/components/IndicatorMap.vue#L489-L497
either data and respective format functions need to be updated or this function needs to be extended

**Comment by santilland** [comment]
Should be solved in https://github.com/eurodatacube/eodash/pull/339
