### ISSUE TITLE
get Time entries for global indicators from API

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#327]
indicators like Nightlights, etc. could use an automatic way to show new data

**Comment by Schpidi** [comment]
related also to https://github.com/eurodatacube/eodash-data/issues/46

**Comment by Schpidi** [comment]
The new version of the NASA API should support this (see https://github.com/eurodatacube/eodash/issues/208#issuecomment-680751112).

The objective is to get rid of the explicit times configuration (e.g. https://github.com/eurodatacube/eodash/blob/staging/app/src/config/trilateral.js#L586 or https://github.com/eurodatacube/eodash/blob/staging/app/src/config/trilateral.js#L743) and use the API at runtime instead.

**Comment by lubojr** [comment]
Getting times from EDC and overall concept was implemented in https://github.com/eurodatacube/eodash/pull/832 
Extension with using NASA API is a TODO

**Comment by lubojr** [comment]
Closing for now. Put on Hold
