### ISSUE TITLE
Create version for bubble chart visualisation.

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#329]
Replace bubbles by pies.
Each pie the same size.
How full the pie is indicates the percentage.
Hover over pie displays the Area size, which is no longer reflected in the size of bubble.

**Comment by Schpidi** [comment]
to be used for E10a8

**Comment by Schpidi** [comment]
see also https://github.com/eurodatacube/eodash-data/issues/99

**Comment by aapopescu** [comment]
![image](https://user-images.githubusercontent.com/35488732/87655691-db637800-c758-11ea-842d-70dcda4fe99e.png)

**Comment by Schpidi** [comment]
first version implemented in https://github.com/eurodatacube/eodash/tree/E10a8 as shown below. the data needs to be revised to include the values for the size of the bubbles as well as the right colors. also a different legend is needed. for the first version I propose to show the % harvested vs. not-harvested on hover.

![Screenshot from 2020-07-23 23-23-31](https://user-images.githubusercontent.com/482265/88340401-13138680-cd3c-11ea-9cf4-55e15c3b48fc.png)
