### ISSUE TITLE
Correct legend in CO2 Maps in trilateral

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#333]
Show values and units on scale bar on CO2 Difference maps

**Comment by aapopescu** [comment]
![CO2 Difference Legend](https://user-images.githubusercontent.com/35488732/86885052-e41ed300-c0f4-11ea-8443-a43b6281418e.png)

**Comment by aapopescu** [comment]
And the legend for Mean CO2
![Legend Mean CO2](https://user-images.githubusercontent.com/35488732/86889520-2bf52880-c0fc-11ea-856b-38e1b8203701.png)

**Comment by Schpidi** [comment]
Thanks, just note, the legend is shown quite a bit scaled smaller which also makes the labels smaller:
![Screenshot from 2020-07-08 09-27-09](https://user-images.githubusercontent.com/482265/86890218-41b71d80-c0fd-11ea-9c18-23cf12d9c483.png)

Compared to NO2:
![Screenshot from 2020-07-08 09-27-22](https://user-images.githubusercontent.com/482265/86890216-4085f080-c0fd-11ea-8d1a-e4a056b31998.png)

Is this OK?

**Comment by aapopescu** [comment]
![CO2 Difference Legend](https://user-images.githubusercontent.com/35488732/86911703-0a0b9e00-c11c-11ea-9cb0-d9fbe11c2da6.png)
![Legend Mean CO2](https://user-images.githubusercontent.com/35488732/86911705-0aa43480-c11c-11ea-84f1-53cadd8728ca.png)

**Comment by Schpidi** [comment]
added in c0de5a5

**Comment by aapopescu** [comment]
need to correct legend on CO2 Difference map
![CO2diffLegend](https://user-images.githubusercontent.com/35488732/92596527-3f607380-f2a6-11ea-84dd-2087b2b05c17.png)

**Comment by Schpidi** [comment]
@aapopescu if I recall correctly the science team complaint about the green in the legend earlier. should we only change the labels maybe?

**Comment by aapopescu** [comment]
replace Mean CO2 concentration legend https://www.eodashboard.org/?poi=W3-N2 

![CO2meanLegend](https://user-images.githubusercontent.com/35488732/93081768-123e0780-f690-11ea-97d6-57388c5b2216.png)
