### ISSUE TITLE
the selection box for global indicators might be confused with filters

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#334]
no idea how to improve on this, but this was a feedback from users

**Comment by Schpidi** [comment]
Idea to expand the list of global indicators at start is it isn't too long. Allow users to minimize it.

**Comment by silvester-pari** [comment]
also, in the table view, add a visual cue for global indicators (e.g. globe icon instead of "all")

**Comment by silvester-pari** [comment]
regarding icons in data table, it is now tracked in #809
