### ISSUE TITLE
N2 timeseries in timezones "west" of UTC

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#335]
Firefox ESR was the first hint but it seems to be a timezone issue where 00:00:00 gets translated to the day/month before:
![Screenshot from 2020-07-02 14-15-47](https://user-images.githubusercontent.com/482265/86357818-b0fcbf80-bc6e-11ea-94ec-22262cec8eaf.png)

**Comment by Schpidi** [comment]
that's how it should look like:
![Screenshot from 2020-07-02 14-17-48](https://user-images.githubusercontent.com/482265/86357892-d7baf600-bc6e-11ea-83c0-c4148314fd75.png)

**Comment by Schpidi** [comment]
happens also on some versions of safari

**Comment by santilland** [comment]
I imagine this could have to do with the parsing of the date string being handled differently.
In any case it seems to be an issue with the Date object handling, will have a look.

**Comment by santilland** [comment]
should be solved in https://github.com/eurodatacube/eodash/pull/339
