### ISSUE TITLE
Adjust graph type for E10a6, E10a7, E10a8, E10a5

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#355]
E10a6 - graph like E10a2 (
cummulative curve)

E10a7 - graph like E10a2 (cummulative curve)

E10a8 - graph like E10a1 (bar charts: one bar shows Harvested %, one bar shows Non-harvested %) together they sum up to 100. Values are included in Measurement Value and Reference Value.

**Comment by aapopescu** [comment]
@santilland can we include the percentage on the graph in E10a6 and E10a7 like in this figure? 

![image](https://user-images.githubusercontent.com/35488732/87405770-2c8c3400-c5c0-11ea-99c2-0a026a4bd610.png)

**Comment by lubojr** [comment]
@aapopescu Would the following look be okay?
![image](https://user-images.githubusercontent.com/19269667/87533300-b1488200-c694-11ea-9a40-e4af48eecd44.png)
