### ISSUE TITLE
New Water Quality Maps Indicator

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#384]
https://github.com/eurodatacube/eodash-data/issues/135

**Comment by AlessandroScremin** [comment]
the EDC layer: ID: N3_CUSTOM_TSMNN

For colors and other info I'm waiting feedback from the Team. At the moment it is configured as the water quality map N3

**Comment by aapopescu** [comment]
Indicator should appear under Water Quality Maps
The AOI is North Adriatic
The title should be "Total Suspended Matter"
we might need to use the small change in lat/lon so that it appears under North Adriatic

**Comment by Schpidi** [comment]
I get this error from the WMS: "CUSTOM has no band chl"

**Comment by aapopescu** [comment]
Also for Rhone Delta

**Comment by Schpidi** [comment]
`eodash-data/data/waterLegend_tsm.png`

**Comment by Schpidi** [comment]
and `data/trilateral/WaterQuality_legend_trilateral_tsm.png`

**Comment by Schpidi** [comment]
@AlessandroScremin what is the layer name for trilateral? tried `N3_CUSTOM_TSMNN_TRILATERAL` and `N3_CUSTOM_TRILATERAL_TSMNN` without success. thanks.

**Comment by aapopescu** [comment]
![TSMlegend](https://user-images.githubusercontent.com/35488732/87796780-1beeee80-c84a-11ea-87c0-1af568a4db19.png)

**Comment by aapopescu** [comment]
![WaterQuality_legend_race_tsm](https://user-images.githubusercontent.com/35488732/87797363-dc74d200-c84a-11ea-9a7e-8b07ec1008e8.png)

**Comment by aapopescu** [comment]
- [ ] We need to include TSM Maps from JAXA in Trilateral 

@lubojr this is the info provided by Jaxa:

(1) Weekly anomaly images (replace all period at this time)
Anomaly[%]=(DN-1)/254*(300-(-100))-100
(Please display from -100 to "+100" in the dashboard) 

URL example) North Adriatic Sea:
Chl-a:
 s3://covid-eo-jaxa/water_quality/<City>/chla/cog/<City>_D_chla_ano300_weekYYYYMMDD_cog.tif

TSM (new indicator):
 s3://covid-eo-jaxa/water_quality/<City>/tsm/cog/<City>_D_tsm_ano300_weekYYYYMMDD_cog.tif

- [ ] use the provided legend

![](https://user-images.githubusercontent.com/35488732/87796780-1beeee80-c84a-11ea-87c0-1af568a4db19.png)

- [ ] use the same legend for JAXA Chl Maps as for ESA and NASA, currently the JAXA maps on Chl do not show values on the legend

**Comment by Schpidi** [comment]
the JAXA update is tracked in #448. I guess we can close this one can't we?
