### ISSUE TITLE
New Indicators (E12c and E12d): Regional Truck Traffic

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#397]
@aapopescu  @Schpidi 

This are two indicators depending on the Roads:

one for Motorways
One for Primary Roads.

The reqeust is 
the key element of his analysis is that, as he has computet the layer for all EU, he can produce this barchart (2018,2019,2020) for any AOI or specific motorways or logistic routes required. 
So principally a user could freely explore these truck counts for different areas or roads.. Hendrik has a road layer prepared that would facilitate this.

In this way we can not create every aoi for each region as I originally thought...it is more complex. From a European COverage we should be able to let user select the AOI directly on the dashboard and then extract and show the trucks and numbers identified over the AOI the user is looking on.

This presume the data are alaready stored somehwere and you can make a call to the source (have to discuss with the participant if feasable) or we can generate AOIs for each region of European countries and generate csv and geojsons but I think it is going to be a huge amount of records...

Current request:
CSV with annual information at Country Level AOI_ID same of 2 char country code since theya re National Indicator
trucks count (yearly) over COuntry and split for 
E12c Motorways
and 
E12d Primary roads

COGs (layer at 10km spatial resolution) whith detected trucks during the year of acquisitions (one COG per year per country)

**Comment by Schpidi** [comment]
- [ ] Could the y-axis start with 0?
- [ ] Is it possible to depict the period instead of just „1. Apr 20XX“ on the x-axis, which is slightly misleading?
- [ ] there is no legend explaining the colour bar of the aggregated raster (heat map)
- [ ] AOI color should be changed to something not used in the trucks heatmap

**Comment by Schpidi** [comment]
- [ ] show warning/empty chart if geoDB returns empty result
- [ ] show progress spinner/bar while waiting for query result

**Comment by Schpidi** [comment]
7640089 fixes y-axis and labels

**Comment by lubojr** [comment]
https://github.com/eurodatacube/eodash/commit/253c30567d243b9a4f832c3c2feb19c7dabd1302 fixes colors
