### ISSUE TITLE
SISTEMA Geojson testing for visualisation

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#401]
In  attachment some sample from the geojson files of SISTEMA. 
Scope: add the point to the satellite image of acquisition. (same case of Nasa but isntead f polygons we have points identifying the ships. Over the point you could visualize the 
"TYPE_SUMMARY"
"SPEED (KNOTSx10)"
just for testing

These are the sample of tjhe last 4 dates available in Master Branch. If it works I acn provide the whole list

Question: do you need the geojason file named all the same way, right? I received two different nomenclature...so I can inform them about this.

[AIS_geojson.zip](https://github.com/eurodatacube/eodash/files/4952308/AIS_geojson.zip)

**Comment by lubojr** [comment]
@AlessandroScremin Yes, correct, we would need the naming of files to have the same structure - for example based on date or any other column from the data, that we can use in the path template to select a correct one. Attached files naming can be used as is.

**Comment by AlessandroScremin** [comment]
@lubojr 
thanks for the feedback. So are the files as in attachment in the correct naming convention and geojson format you can read? if it is so I would reply to SISTEMA that geojson should be as the ones attached.

**Comment by Schpidi** [comment]
can I propose to follow the established pattern (`<AOI-ID>-<indicator-code>`) and append the date? E.g. `ES7-E1-2020-06-23T18-12.geojson`

**Comment by AlessandroScremin** [comment]
@Schpidi @lubojr 
I changed a bit your proposal to adapt it to other geojson we are going to receive...hope this is fine

In any case this is the whole dataset for sistema

indicatorCode_AOI_ID_timeInyyyymmddThhmm(ss).geojson
(ss) is in bracket as I think it is not necessary for find the image on that date adn time ..if seconds could be an issue I will ask sistema to addalsos econds....since so far they provide till minutes and seconds always 00.

[AIS_E1_ES7_geojson.zip](https://github.com/eurodatacube/eodash/files/4953723/AIS_E1_ES7_geojson.zip)

**Comment by Schpidi** [comment]
Closing as this meanwhile landed on production https://race.esa.int/?poi=ES7-E1
