### ISSUE TITLE
New Indicaotr E14 Ship traffic

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#412]
number of ships for traffic monitoring in areas of 14km x 14km. Also COG heatmaps should be provided

CSV with  acquisiton for 2018 2019 and 2020. THey would need to display on the same graph the three years verlayed (like in agricolture indicator). The graph represent the number of ships  for a specific day.(=acquisition) .

Then they should provide COGs with heatmaps to be displayed over the AOI for each of the years (one map for each AOI for representing 1 year)

Question @Schpidi 
They can't provide the time as the y were not able to extract it from the EDC. Could we get the Satellite image as well with the date? (using sentinel there should be no problem if we have only the date.

**Comment by Schpidi** [comment]
> Then they should provide COGs with heatmaps to be displayed over the AOI for each of the years (one map for each AOI for representing 1 year)

I guess you're going to load those in EDC right?
 
> Question @Schpidi
> They can't provide the time as the y were not able to extract it from the EDC. Could we get the Satellite image as well with the date? (using sentinel there should be no problem if we have only the date.

Not sure I understand the question. Do you mean to use only a date without time in WMS requests? This should work but might most of the time give too many results as a S2 orbit for example takes about 90min.

**Comment by AlessandroScremin** [comment]
@aapopescu  @Schpidi 
I see this issue in High priority for release 3.0, but it is old and no more used as they didn't win the EDC challenge in july.

Only Flying airolanes and truck traffics were included.

I think we could close this issue without any further action

**Comment by lubojr** [comment]
Closing for now. Put on Hold
