### ISSUE TITLE
New Indcator: water quality EDC contest

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#414]
water quality time series with annual COGs maps

They monitored the water turbidity of rivers and streits. THey provide a csv with one record for each Sentinel 2 acquistion and each AOI monitoried. 
THe Maps are one per year per AOI, as average of the Year.

**Comment by santilland** [comment]
Anca to confirm if data can be visualized, internal implementation for visualization can be started (not high priority)

**Comment by aapopescu** [comment]
@santilland this indicator is not to go online, as the data is not validated, confirmed with Patrick
