### ISSUE TITLE
Update text for indicators that are discontinued

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#432]
Custom the text below the chart to be 

- [] "This indicator is no longer updated" 

when value in "Update Frequency" is "Retired"

- [] "Due to end of season, this indicator is no longer updated" when value in "Update Frequency" is "EndSeason"

**Comment by silvester-pari** [comment]
added  in https://github.com/eurodatacube/eodash/commit/26c639219da42ee30cb1b804afe70cd17be0bf4e

**Comment by Schpidi** [comment]
merged in #442
