### ISSUE TITLE
Sensing date EDC and Original file mismatch

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#441]
@gmilcinski @tomislijepcevic 

Dear I noticed something strange.
Ichecked the  Sentinel 2 availability  for 2020 0713 ofver Gjon:
in EDC the sensing time is 11.29.11,
but checking the original file:
20200713T**112119**_20200713T112115_T29TQJ

So what date is in the EDC?

THere are temas that are working directly from the original data  (without using EDC) but if the sensing date are different we can't display taht image in the Dashboard as in the case of E1 over Gjion for 20200713.

**Comment by gmilcinski** [comment]
HI @AlessandroScremin,
we use "sensing time" data from the metadata.xml that comes with the file:  
https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/29/T/QJ/2020/7/13/0/metadata.xml
These information are generally most precise. 

Why exactly is this different than the sensing time in the file name and on SciHub meta-data, is beyond our knowledge. You would have to ask the ESA's ground segment staff.

**Comment by AlessandroScremin** [comment]
@gmilcinski 
yes I was investigating also the metadata on google eath engine...and same sitaution...sensing of acquisition oin the file name is A and the one in the metadata is B...

I have to inform team to use the one in the metadata...
or
@santilland @Schpidi @aapopescu  Is there a wasy to use only the date for Sentinel data? it should not be an issue for Sentinel Data (but it is for Pleiades or Planet....)

it is a proposal...maybe is only the case of sistema...I will continue investigate for Sistema data...they are the one that potentially use their platform for data information extraction (almost sure of that)

Thanks @gmilcinski

**Comment by gmilcinski** [comment]
Sentinel-2's orbit takes 100 minutes so if you add +-45 minutes to whatever time you have, you should be on the safe side that you get exactly the same observation.

**Comment by santilland** [comment]
@AlessandroScremin what do you mean to only use the date? you mean removing the time (so HH:mm:SS) from the request?
I think we should be able to define a date format function for specific data sources, such as Sentinel 2 source.
If the endpoint allows requesting the image with just the date, so YYYY-MM-DD and nothing else we could probably do that.
