### ISSUE TITLE
NEW Indicator - GEOGALM data, Global, Agriculture

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#450]
Indicator already included in NASA dashboard

Info from OIaf: 

Hi Anca,
Here's a link to the code that we use to pull in the agriculture data: https://github.com/NASA-IMPACT/covid-dashboard/blob/develop/app/assets/scripts/components/common/layers/layer-agriculture.js
It contains the full API request, and all the color stops and categories.

Please let me know if you need any more information about how to pull the product into the tri-lateral.
best,
Olaf

**Comment by aapopescu** [comment]
Feedback from Agriculture Team:

GEOGLAM would be interested to improve their visualization by integrating sub-national regions.
They would prefer to use vector data.
They provided the following files:
https://drive.google.com/file/d/1Vp0f4263IL-SCDs1ef7Kwi15z8wY0R91/view

**Comment by aapopescu** [comment]
Indicator Name should be : Cropped Area

**Comment by aapopescu** [comment]
@lubojr here is the geojson prepared by GEOGLAM 
[CM_Subnational_Regions_geojson.zip](https://github.com/eurodatacube/eodash/files/5101669/CM_Subnational_Regions_geojson.zip)
for the color of the outline, they suggested black, but I think the current grey version is OK so no change needed there.

**Comment by aapopescu** [comment]
new legend 
![GEOGLAM_legend](https://user-images.githubusercontent.com/35488732/90825685-8c9d9500-e339-11ea-9138-60d8db94c2d6.png)

**Comment by aapopescu** [comment]
also a smaller size if needed 
![GEOGLAM_legend](https://user-images.githubusercontent.com/35488732/90825824-c4a4d800-e339-11ea-85cf-6a8ee9947c23.png)

**Comment by Schpidi** [comment]
updated in f6e9972
