### ISSUE TITLE
NEW Feature - Switching between different result layers

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#453]
Where we have the same indicator with different views, the user should be able to easily switch between them and should be able to return to a previous view. 

Example:

Again in the truck detection example, we have the individual truck detections as a point layer, 
and then the aggregated detections as 10x10km heatmaps. 

It would be great if a user could switch between these result visualisations.

**Comment by aapopescu** [comment]
> Where we have the same indicator with different views, the user should be able to easily switch between them and should be able to return to a previous view.
> 
> Example:
> 
> Again in the truck detection example, we have the individual truck detections as a point layer,
> and then the aggregated detections as 10x10km heatmaps.
> 
> It would be great if a user could switch between these result visualisations.

@silvester-pari we could use the tab feature for Agriculture. Indicators to be unified in tabs:
- E10a6 and E10a7

**Comment by silvester-pari** [comment]
> > Where we have the same indicator with different views, the user should be able to easily switch between them and should be able to return to a previous view.
> > Example:
> > Again in the truck detection example, we have the individual truck detections as a point layer,
> > and then the aggregated detections as 10x10km heatmaps.
> > It would be great if a user could switch between these result visualisations.
> 
> @silvester-pari we could use the tab feature for Agriculture. Indicators to be unified in tabs:
> 
>     * E10a6 and E10a7

@aapopescu this wouldn't work with the current approach, two or more POIs would need to have the same indicator code to enable grouping. otherwise they appear only in one of the indicator filters.
If feasible, the easiest solution would be to only have E10a6 (convert all POIS of E10a7 to E10a6), and give the POIs unique IDs (such as for example ES30a and ES30b instead of ES30 & ES30). Then it would work out of the box like this:

```
{
    features: [
      'ES30a-E10a6',
      'ES30b-E10a6',
    ],
    label: 'indicator',
},
```

Is this a viable solution?

cc @Schpidi

**Comment by aapopescu** [comment]
@silvester-pari, this could work. Do we need different lat,lon or only the AOI_ID to be different for each POI?

**Comment by silvester-pari** [comment]
I think having AOI_ID different should be fine, no need to have different lat & lon!
