### ISSUE TITLE
Check favicon/favorites icons on safari

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#466]
![image](https://user-images.githubusercontent.com/26576876/90404565-d882dc80-e0a2-11ea-9119-be393b082d3a.png)

**Comment by aapopescu** [comment]
for Trilateral, please use this image

[Picture_1.ico.zip](https://github.com/eurodatacube/eodash/files/5128291/Picture_1.ico.zip)

**Comment by silvester-pari** [comment]
fixed in https://github.com/eurodatacube/eodash/commit/99cc32db83767e5d714648bce404103ff5428881
