### ISSUE TITLE
UI: responsive/browser glitches

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#481]
- [x] mobile: middle section (map/table) is sometimes cut off at bottom, not showing attribution and set filters
- [x] mobile: sometimes the map/table table headers get scrolled upwards and are not clickable anymore
- [x] mobile/iOS iPhone safari: scrolling to the bottom of the indicator filter list makes the list jump back up a bit, hiding the last list item

**Comment by silvester-pari** [comment]
Some graphs such as this have overlapping elements when screen size is too small. 

![Image from iOS.png](https://user-images.githubusercontent.com/26576876/91972351-debbbe80-ed1a-11ea-8078-fbc44d41d453.png)

**Comment by silvester-pari** [comment]
it seems like https://github.com/eurodatacube/eodash/commit/a666ffd551e05a66ae4b5d6b5ad20760d6a14145 solves at least two of the issues - does your reported issue persist @Schpidi ?

**Comment by Schpidi** [comment]
looks mostly good in my testing. definitely better than before. thx

**Comment by silvester-pari** [comment]
> Some graphs such as this have overlapping elements when screen size is too small.
> 
> ![Image from iOS.png](https://user-images.githubusercontent.com/26576876/91972351-debbbe80-ed1a-11ea-8078-fbc44d41d453.png)

regarding ffine-tuning the graphs probably @santilland is our best bet :-) maybe just reducing the size of the map helps for this chart?

**Comment by silvester-pari** [comment]
i have created a dedicated issue for this - #521
