### ISSUE TITLE
Integrate NO2 difference maps in trilateral for OMI data

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#523]
available at NASA dashboard

**Comment by Schpidi** [comment]
@aapopescu the configuration is added on staging. do you maybe have a legend file? thanks

**Comment by aapopescu** [comment]
add legend
![NO2Diff](https://user-images.githubusercontent.com/35488732/93579862-4c185200-f99f-11ea-9699-e3de4a9b6773.png)
