### ISSUE TITLE
Change colour scheme in E10a6 and E10a7

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#526]
Use colour blind scheme for the 2019 and 2020 lines in the chart

Update CSV to use the correct colour to indicate current status of indicator (measurement > reference --> green, < referecne ----> red)

**Comment by santilland** [comment]
Hello @aapopescu , the color is currently "hard coded" taking the opportunity of the changes for E8 i was considering using following colors based on the colour blind scheme:
![image](https://user-images.githubusercontent.com/4036819/98124860-031b4f00-1eb4-11eb-9f1f-7ef72d2f8142.png)

I am not sure if we already use specific colors for specific years, if we do i think it would be good to keep the same colors, i am currently not finding any cases of this.

**Comment by santilland** [comment]
If colors ok changes are combined in pull request #637

**Comment by santilland** [comment]
Pull request was accepted, change is included in staging now
