### ISSUE TITLE
Two Errors in the Color Bar on the Global CO2 Mean Maps

### ISSUE THREAD

**Issue by dcrisp-jpl** [eurodatacube/eodash#529]
There are two errors in the color bar on the Global CO2 Mean maps for the Greenhouse Gases indicator. 
 
1) The lower limit of the color range is stated as "-408". It should be "408" (i.e. positive, not negative).  The full range is 408 to 419 ppm.  
2) The color bar shows the wrong color scale. The color bar shows blue-white-red. The global map uses a blue-yellow-red color scale.  These should be made consistent.

Please make these corrections at your earliest convenience.

**Comment by Schpidi** [comment]
The legend has been updated in 295c0a7 and will soon be deployed.

**Comment by Schpidi** [comment]
The new legend has been deployed and looks like this:
![Screenshot from 2020-09-18 13-12-00](https://user-images.githubusercontent.com/482265/93591412-9950ef80-f9b0-11ea-8cf5-13113663da83.png)

Hope this is correct. Please reopen if there is still an issue.

**Comment by dcrisp-jpl** [comment]
Stephan:

Thanks. Looks good.

Best Regards,
Dave

Dr. David Crisp
Jet Propulsion Laboratory/Caltech
Sent from my phone. Please pardon typos.

On Sep 18, 2020, at 4:13 AM, Stephan Meißl <notifications@github.com> wrote:

﻿

The new legend has been deployed and looks like this:
[Screenshot from 2020-09-18 13-12-00]<https://urldefense.us/v3/__https://user-images.githubusercontent.com/482265/93591412-9950ef80-f9b0-11ea-8cf5-13113663da83.png__;!!PvBDto6Hs4WbVuu7!aG5kYC-QCOo3ACuplwTA9rMuiFIIh5XcJUlOhwiLnsKoF9QjbozFQqf3i3pi1i-e6nmWojM$>

Hope this is correct. Please reopen if there is still an issue.
