### ISSUE TITLE
Legends for SAR proxy maps

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#550]
Add legends for SAR slowdown and recovery maps
![SARRecoveryLegend](https://user-images.githubusercontent.com/35488732/94709870-7c200780-0346-11eb-813d-9d9da21516e8.png)
![SARSlowdownLegend](https://user-images.githubusercontent.com/35488732/94709875-7cb89e00-0346-11eb-9d49-e7b0700be650.png)

**Comment by Schpidi** [comment]
maybe increase the contrast a bit?
![Screenshot from 2020-09-30 19-48-49](https://user-images.githubusercontent.com/482265/94721311-fefc8e80-0355-11eb-97b8-f94f05a0ccf2.png)

**Comment by aapopescu** [comment]
![SARRecoveryLegend](https://user-images.githubusercontent.com/35488732/94726032-f8254a00-035c-11eb-9f70-f07288ad39e1.png)
![SARSlowdownLegend](https://user-images.githubusercontent.com/35488732/94726042-fa87a400-035c-11eb-990a-09e09dc19e11.png)
