### ISSUE TITLE
Multiple COGS overlays are covering data of other layers

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#557]
@gmilcinski @gobaRules @tomislijepcevic 
Coudl you please check  this ?

When I ingested the Cog files for the Motorway and primary Roads Truck detenction I got this coverage of the tiles..

![image](https://user-images.githubusercontent.com/65602207/94826177-54dd3f00-0407-11eb-9285-d327a6cab97d.png)

When we display the layers in the dashboard, we have several holes and we notice these holes are caused by layers overlay. Eventhough we set in some way no data values transparent...(but also using the custom script for the sar data) we noticed that the data under the Overlayed layers are not shown...but data exist and can be retrieved...example here:

Portugal and spain
![Screenshot from 2020-10-01 16-18-50](https://user-images.githubusercontent.com/65602207/94826599-c3ba9800-0407-11eb-9d11-c392b87ae23b.png)

as you see there are not visible values and checking with Qgis we noted that there there is the overlay of bbox as shwon here:
![image (1)](https://user-images.githubusercontent.com/65602207/94826775-f49acd00-0407-11eb-8fa3-eb25f4e68bb7.png)

The issue is mainly a visual issue but opened on the whole Europe this holes are very annoying
oher example of visualisation on the dashboard here
![Screenshot from 2020-10-01 16-10-28](https://user-images.githubusercontent.com/65602207/94826930-22801180-0408-11eb-8e34-9833e94933ca.png)

**Comment by gmilcinski** [comment]
This is not really a bug, it is just wrongly configured BYOCs or layers.  
@gobaRules will support you, but please do properly flag such issues.

**Comment by AlessandroScremin** [comment]
@gmilcinski 
BYOC has been generated following your documentation, so from my point of view it was not a BYOC wrongly configured, as the tif can be normally seen within other gis software...so was open as bug...in any case no problem to flag it properly when I'm able to understand the issue...now is attention needed!

**Comment by gobaRules** [comment]
This has the same root cause as  https://github.com/eurodatacube/eodash/issues/555#issuecomment-702638694 .

**Comment by AlessandroScremin** [comment]
@gobaRules #555 fixed, but overlay issue remains

**Comment by gobaRules** [comment]
Ok, now that we have correct dataMask band, we can do [this](https://docs.sentinel-hub.com/api/latest/data/byoc/#workarounds).

**Comment by AlessandroScremin** [comment]
@gobaRules 
don't know where to start...make a setup for mosiking??where I have to write this setup?

/VERSION=3
 
function setup() {
return {
input: ["PrimaryRoadsActivity", "dataMask"],
output: { bands: 4,
sampleType: "UINT8" }
};
}
 
function evaluatePixel(sample) {
var nodat = sample.dataMask; 
var val = sample.PrimaryRoadsActivity;
var result= colorBlend(val,
[0,5,15,50,100],//,254 ],
[[253,243,237,0], // 0
[248,210,192,100], // 45
[236,115,82,150], // 90
[213,43,34,160], // 135
[93,19,15,170],// 180
]);
  if (nodat==1) {
    return result
  }
  else{
    return[0,0,0,0]
  }
}

**Comment by AlessandroScremin** [comment]
Ok fixed with the indication provided
