### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by hadrilec** [eurodatacube/eodash#583]
Hi!
First of all congrats for this great dashboard!
This data looks very interesting to assess global output in real time.
However, it is not easy to get the data from the app.
Would it be possible to set up a REST API or at least a csv file download button?

Kind regards,
Hadrien

**Comment by Schpidi** [comment]
There is now a button to download the data as CSV available for each chart indicator. Hope this solves your request. Please reopen if you find anything missing.
