### ISSUE TITLE
Use Draw AOI feature on NO2 maps

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#589]
Use the time series graph generation based on used defined AOI on NO2 Maps 

Related issue here:
https://github.com/eurodatacube/eodash-data/issues/42

**Comment by lubojr** [comment]
Just a followup related comment, sorry if redundant: https://github.com/eurodatacube/eodash/issues/451#issuecomment-697273540 - for NO2 derived from SH using FIS request, a new layer configuration needs to be created to return the raw values, in addition to RGBA composite, which will be soon used for visualization.

**Comment by Schpidi** [comment]
adding to trilateral in #606
