### ISSUE TITLE
Feedbacks Reported by the Water quality team

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#594]
@Schpidi @aapopescu @tomislijepcevic  (FYI @JPatruno )

Other feedbacks from the Water quality teams

**Trilateral Dashboard**
1)AAOT=>time series: modis is no longer updating (last point is 8 August 2020)
Did you received udates from NASA?

2) NAS/Rhone=> TSM/Chl maps: once a specific week is chosen, this week should remain the same when moving from a sensor to another sensor; at present, each sensor has an independent calendar and this makes the inter-comparison very hard; moreover, the weeks are not synchronized (i.e., ESA: 2020-08-04; NASA: 2020-08-05; JAXA: 2020-08-08); if NASA and JAXA do not update, the should show blank maps for the ESA weeks.

**Race Dashboard**
1) AAOT => water quality time series: there is an additional blue dot in the legend on top of the figure, next to "Standard deviation (STD)"; it results two annoying blued dots in a row
it refers to:
![image](https://user-images.githubusercontent.com/65602207/95992265-0def4080-0e2e-11eb-9acc-6f2cb8bb7c0e.png)

2) (This is more from my side) Same graph of point 1, When I click on the legenda I can make data not visible in the chart..it is working only for the STD deviation, all other paramters remain visible even if clicked...is that correct?
standar deviation invisible
![image](https://user-images.githubusercontent.com/65602207/95992392-2f502c80-0e2e-11eb-97d5-ccb255fc0e57.png)

Red dots should be invisible???
![image](https://user-images.githubusercontent.com/65602207/95992518-5149af00-0e2e-11eb-90f0-d831a15acbc7.png)

**Comment by lubojr** [comment]
2. still a todo
