### ISSUE TITLE
On desktop the expand chart/map could go more fullscreen

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#597]

**Comment by silvester-pari** [comment]
@Schpidi @aapopescu 
Could you give any more details on this? It is by design that the expand button expands the right panel to take on full width, while keeping the rest as is (top menu bar, the story below the chart, footer).
What is expected instead?

**Comment by aapopescu** [comment]
@silvester-pari 
Being able to put just the map in fullscreen, and escape back to the panel view

**Comment by silvester-pari** [comment]
Should this replace the current full-width panel feature, or should it be additional?

**Comment by silvester-pari** [comment]
Also, if it should only be the map/chart element (and not the whole panel), I would suggest having a fullscreen button directly on the map/chart, and not the panel header.

**Comment by aapopescu** [comment]
> Also, if it should only be the map/chart element (and not the whole panel), I would suggest having a fullscreen button directly on the map/chart, and not the panel header.

Only the map expanding, additionally to the panel full width, with fullscreen button on the map

**Comment by silvester-pari** [comment]
I pushed my proposal for this solution. Now each chart and each map (right panel) additionally has a fullscrene button.
![image](https://user-images.githubusercontent.com/26576876/99944969-0fd4e980-2d74-11eb-902b-bccdc5938101.png)

**Comment by silvester-pari** [comment]
There seems to be an issue with Firefox and different button sizes:
![image](https://user-images.githubusercontent.com/26576876/99946287-65aa9100-2d76-11eb-8fc2-4159bfe6dc28.png)
Need to investigate what happens there, but the functionality itself is working!

**Comment by silvester-pari** [comment]
Added a fix for touch-enabled browsers in https://github.com/eurodatacube/eodash/commit./08f4cdd325aa9de817bfa42336569e4891320000

![image](https://user-images.githubusercontent.com/26576876/99949486-67c31e80-2d7b-11eb-84b8-5bfac725fdf1.png)
