### ISSUE TITLE
Explore possibility to add an interactive chart in a story directly

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#598]
This would be for example useful for archived data like in the airplane case were old data exists that was computed with a different algorithm but is not updated anymore.

**Comment by aapopescu** [comment]
@silvester-pari, can't this already be done with the embed link?

**Comment by silvester-pari** [comment]
Yes, it is possible, so an archived indicator could be integrated into a story. 
Currently, it is only possible to embed an indicator at the current state, not at a certain point in history, but if that is something we want to add it is probably best to create a new issue for this.
