### ISSUE TITLE
review subaoi prominency in indicator map

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#608]
Just summarizing info from internal discussion
- SubAoi should be made less prominent in case, where it does not make much sense.
- Review used subaois if they match where imagery is provided
- try some transparency for subaoi polygon
- Review and extend `flyToBounds()` function in indicatorMap, assure that subaoi property does not need to be filled for world pois (which now does if aoi is filled or the map zooms to Z=18...)
- consider case where we dont want to show too far north/south where data like no2 is not useful
- consider a new approach for additionally **grey-out the rest of the map outside of subaoi** by using half-transparent primary-color polygon (symmetric difference) (as seen in eoxc when area filter is set -> https://ows.eox.at/mundi_staging/eoxc/?area=POLYGON%28%282.564013+51.162743%2C0.8062+48.833641%2C3.772509+46.965965%2C5.859911+49.73452%2C4.585497+50.855125%2C3.794482+52.9645%2C1.311571+52.87661%2C-2.072218+50.305809%2C-2.643507+47.822899%2C2.564013+51.162743%29%29#

![Screenshot from 2020-10-20 14-36-38](https://user-images.githubusercontent.com/19269667/96840340-98492d00-144a-11eb-9415-f5c8b41c01fb.png)
![Screenshot from 2020-10-20 14-36-56](https://user-images.githubusercontent.com/19269667/96840345-9a12f080-144a-11eb-9959-179ae2ba25a1.png)

**Comment by santilland** [comment]
Another example with Slowdown Proxy Maps
![image](https://user-images.githubusercontent.com/4036819/100084546-3023a780-2e4b-11eb-8281-5a507784ec51.png)
