### ISSUE TITLE
CAMS data integration

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#610]
@Schpidi @JPatruno @mdelgadoblasco 
Data to be included:
- [x] NO2 and PM2.5 times series 
- [x] NO2 and PM2.5 maps. 
These data will complement the TROPOMI information. We will need to use the tabbed approach to make the clear distinction between the data sources, @silvester-pari 
 - [x] ECMWF will provide the descriptive text/story.
 - [x] we need to implement #624 until December release
 - [x] We will need a button to point to the CAMS site, similar to the button we have for PAL @silvester-pari 
https://atmosphere.copernicus.eu/european-air-quality-information-support-covid-19-crisis 

Next milestones: 
- [x] by 31/10 - we have the details for the data to be integrated. @miha-at-ecmwf will provide the WMS to get the maps
- time series data will come from here: https://github.com/CopernicusAtmosphere/air-quality-covid19-response
@JPatruno can you please have a look at the csv and propose a conversion to the race format? 
- [x] by 06/11 - first integration of WMS
- 06 Nov @14:00 - next status meeting with CAMS
- [x] by 06/11 - time series /csv in RACE format
- [x] by 13/11 - integration ready
- [x] by 20/11 - story ready and integration done
- [x] by 27/11 - testing

**Comment by miha-at-ecmwf** [comment]
I hope you have enough information to start integrating the CAMS European air quality analysis time series data.

CAMS WMS daily averaged NO2 and PM2.5 analysis layers are available from this endpoint:
https://apps.ecmwf.int/wms/?token=public&request=GetCapabilities&version=1.3.0

Layer names: 
NO2 analysis: composition_europe_no2_analysis_surface
PM2.5 analysis: composition_europe_pm2p5_analysis_surface

There are two WMS styles available (sh_Reds_surface_concentration and sh_Purples_surface_concentration) for each of these layers but we can easily add additional ones if needed.

The physical quantity in all of the above products is mass concentration at surface level and the unit is µg/m3.

**Comment by lubojr** [comment]
Implementation details specified during cams meeting:
- configure tabbing for poi charts (air quality) once data is available
- add tabbing for map layers
- configure times offered as daily up to "yesterday" 
- add external link button
- start working on #624 - have a look at how data is provided + think how to serialize this into configuration property / csv field

**Comment by aapopescu** [comment]
@silvester-pari, the button should point to: https://atmosphere.copernicus.eu/european-air-quality-information-support-covid-19-crisis

**Comment by aapopescu** [comment]
@miha-at-ecmwf, can you please share the code for fetching the lockdown period per location?
