### ISSUE TITLE
Add new base layer for Agriculture

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#614]
Add this base layer and make it default for all agriculture indicators :

http://s2glc.cbk.waw.pl/extension

layer is on CREODIAS exposed via WMS

**Comment by lubojr** [comment]
Implemented in https://github.com/eurodatacube/eodash/pull/621
- added the new baselayer configuration for all indicators under `agriculture` cathegory which now have EO Data displayed - Could you please review?

**Comment by aapopescu** [comment]
@lubojr please add this layer to the center map as well

**Comment by lubojr** [comment]
@aapopescu As another option for a baselayer for all indicators?

**Comment by aapopescu** [comment]
> @aapopescu As another option for a baselayer for all indicators?

yes
