### ISSUE TITLE
Change E8 chart

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#615]
https://github.com/eurodatacube/eodash-data/tree/E8-new-chart

**Comment by aapopescu** [comment]
https://github.com/eurodatacube/eodash-data/pull/200

**Comment by santilland** [comment]
Took new data and replaced current E8, changing the visualization to E10a6 type:
![image](https://user-images.githubusercontent.com/4036819/98126046-6fe31900-1eb5-11eb-92e5-84f11d11dc86.png)
Probably still need to decide which color we will use for each year group.

**Comment by aapopescu** [comment]
@santilland , looks good!

**Comment by santilland** [comment]
Merged and deployed to staging
