### ISSUE TITLE
Prepare for 2021 in yearly compare indicators (E10a6, E8 etc.)

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#616]
Need to adjust data and client

**Comment by lubojr** [comment]
Other examples: E8 with lockdown dates rendered (this in current form can not be rendered even with configuration change/update)

**Comment by santilland** [comment]
The issue for data in 2021 is specific to some indicators, those which show the evolution line of 2019 and 2020 on the same "1 year" time axis overlapped. I will try to compile a list of the relevant indicators.
I think we can solve the issue in general by removing the restriction data visualization and adding a third entry (columns or line) to the plot.

- [ ] **E13e**: We could remove the lockdown dates, not sure i can think of any other option and add a third curve for 2021 
![image](https://user-images.githubusercontent.com/4036819/122032642-1ee2be00-cdd0-11eb-8ad0-265c99b22efa.png)
 
- [ ] **E8**: Same as with previous, i think there is already some conflict of overlapping restriction time spans in some cases 
![image](https://user-images.githubusercontent.com/4036819/122032959-65d0b380-cdd0-11eb-8667-6ba9be5d9551.png)

- [ ] **E10a1; E10a5** will there be updates to these indicators? It should be possible to add a third entry to the columns for 2021 but color should be decided and if percentage change label should be to 2019 or to 2020. Indicator label would also need to be changed.
![image](https://user-images.githubusercontent.com/4036819/122033289-acbea900-cdd0-11eb-9efb-26f416cfc1a9.png)

- [ ] **E10a2, E10a6** will there be updates? if yes same as E13e 
![image](https://user-images.githubusercontent.com/4036819/122033453-d2e44900-cdd0-11eb-8c86-d3c0c4a8052b.png)
