### ISSUE TITLE
Dark mode for dashboard

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#617]
I played around a bit and added a dark mode in https://github.com/eurodatacube/eodash/tree/dark-mode branch (can be tested in a feature branch) - a user can switch using the small sun/moon toggle in the bottom right of the footer, whereas dark/light mode is automatically set according to his/her current browser preference.

we can merge this if wanted.

![image](https://user-images.githubusercontent.com/26576876/97563046-d31b0a00-19e2-11eb-85c0-ed7a9dca7e67.png)

**Comment by aapopescu** [comment]
beautiful!
