### ISSUE TITLE
Use Cloudless or HR optical baselayer for ship indicators 

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#654]
@lubojr when there is no HR optical imagery available make optical cloudless layer default, for example here https://www.eodashboard.org/?poi=US01-E13c&indicator=E13c

**Comment by aapopescu** [comment]
cannot see expected behavior, Terrain Light still seems to be the default

**Comment by lubojr** [comment]
It works for me on testing: 
![image](https://user-images.githubusercontent.com/19269667/99388139-686c3880-28d5-11eb-9863-9d4f8872e273.png)
on url?indicator=E13c&poi=US03-E13c

**Comment by aapopescu** [comment]
works, all good!
