### ISSUE TITLE
Navigation over the indictor menu

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#67]
### Environment
**App version:** 0.4.0

**Operating system:** MacOS

**Affected browser:** Safari 12

### Steps to reproduce:
select indicators over the indicator menu 

### Expected Behaviour:
once indicator selected - map would highlight them and zoom so they are visible

### Actual Behaviour:
the map remains fixed to the current zoom so when zoomed already to a certain AOI the selected indicator is not visible

### Comments:
No comments

**Comment by silvester-pari** [comment]
is this now solved, since the map always zooms to the selected indicator via filter?
