### ISSUE TITLE
Separate times for charts and for maps

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#698]
- Prepare a concept and implement option to separate times used for charts and times for EO Data
- Currently the exact same array is used, or a new one can be substituted from config.
- Prepare a concept of how this can be implemented and then configured. 
- For example: https://github.com/eurodatacube/eodash-data/pull/232 has less time entries for chart than for features, but we still want to load all of them in map. - for now deleted the ones without reference in csv

**Comment by Schpidi** [comment]
Likely needed for https://github.com/eurodatacube/eodash-data/issues/222
