### ISSUE TITLE
Add custom dashboard feature

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#720]
Add a way to create a custom selection of charts/maps, and store the result

- [x] Create a customized dashboard by adding charts/maps to it
- [x] Store the customized dashboard and generate an edit and a share link
- [x] Add questionnaire to ask user about field of work/interests
- [x] Optionally add user to mailing list

**Comment by silvester-pari** [comment]
did some first testing in https://github.com/eurodatacube/eodash/commit/c349406fe64e0a89ace9b90033af51f4dc63851e, very much WIP

**Comment by silvester-pari** [comment]
after the latest review, following things still need fixing:

- [ ] something happened to the editing of elements titles
- [ ] sometimes when going back and forth, the title of the custom dashboard disappears completely
- [ ] margin of the top right buttons is missing in some cases
- [ ] in the viewing mode, no title edit buttons shall appear
- [ ] the "disconnect" button shall be renamed to something easier to understand, e.g. "exit edit mode" (also change icon)
- [ ] the "publish" button shall be renamed to "save dashboard", as it is actually not "published" unless the link is shared
- [ ] the "update map position" button shall disappear after saving, and only appear after the map position has been changed
- [ ] "update map position" shall renamed to "save map position"
- [ ] the maps that allow drawing/custom area selection shall have these buttons removed inside the custom dashboard view

**Comment by santilland** [comment]
Other feedback:

- [ ] Map not re-centering when increase card size
- [ ] (On mobile) When selecting the interests, clicking DONE did not close the dropdown so I had to scroll to get passed it
