### ISSUE TITLE
NEW CMEMS datasets to be added

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#756]
**- Atlantic coasts:** 

OCEANCOLOUR_ATL_CHL_L4_NRT_OBSERVATIONS_009_037
https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=OCEANCOLOUR_ATL_CHL_L4_NRT_OBSERVATIONS_009_037

@lubojr , 
There is one issue we should take care of: The Atlantic regional product seems to have data also in the western part of the Mediterranean Sea. This should be discarded, as we have the Mediterranean regional product. 

[Longitudes <  5.3536 W  OR  (Longitudes < 1.4436 E     and Latitudes > 42.8782 N) OR  Latitudes > 45 N ]   = Keep the data
Discard all the rest.

**- Black Sea:** 

OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045
https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045

**- Baltic Sea:** 

OCEANCOLOUR_BAL_CHL_L3_NRT_OBSERVATIONS_009_049
https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=OCEANCOLOUR_BAL_CHL_L3_NRT_OBSERVATIONS_009_049

**Comment by aapopescu** [comment]
Feedback from WQ team:
- AOI dark border to be removed
- Legend should span the whole range of values (e.g. to include also dark blue/black and dark red)
- Baltic layer may be removed (please hold for the moment on this point, needs confirmation)

**Comment by lubojr** [comment]
@aapopescu 
AOI dark border to be removed - By that you mean completely remove the subaoi delineation for limiting user movement or just make it completely opaque (both for subaoi inverse area and the outline or just the inverse area and leave the outline)?

**Comment by aapopescu** [comment]
> @aapopescu
> AOI dark border to be removed - By that you mean completely remove the subaoi delineation for limiting user movement or just make it completely opaque (both for subaoi inverse area and the outline or just the inverse area and leave the outline)?

Completely remove the sub-AOI delineation

**Comment by aapopescu** [comment]
closing this as it is addressed in #799

**Comment by lubojr** [comment]
Reopening as more general issue https://github.com/eurodatacube/eodash/pull/799#issuecomment-781255016 needs to be addressed. Will not be just configuration change.

**Comment by santilland** [comment]
Changes can not be done on data level so we should look at a solution on client level.
@lubojr had a possible solution in mind lets discuss it

**Comment by aapopescu** [comment]
a legend is needed

**Comment by santilland** [comment]
thanks for spotting that, was added, will take a little to update the test deployment
