### ISSUE TITLE
Include COVID-19 data:

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#757]
- cases
- vaccinations
https://github.com/CSSEGISandData/COVID-19
https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations/country_data 
- link to app code 
- https://cds.climate.copernicus.eu/cdsapp#!/software/app-c3s-monthly-climate-covid-19-explorer?tab=appcode

**Comment by santilland** [comment]
Looking at the data i think we need a clear specification what should be included and how it should be integrated into the dashboard.
We will somehow then need to extract the wanted data and convert it to a format we can work with.
One possibility would be to use the same approach as with the google mobility data. We could extract the time series for each country and load it as a timeline when clicking on a country on the global map.
For this i think we could extract the information for **cases** from the following dataset:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

I don't see any information on **vaccinations**, maybe i am missing something. These are the datasets for which there are at least time series:
```
time_series_covid19_confirmed_US.csv
time_series_covid19_confirmed_global.csv
time_series_covid19_deaths_US.csv
time_series_covid19_deaths_global.csv
time_series_covid19_recovered_global.csv
```
