### ISSUE TITLE
Add mobility data

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#758]
Add mobility indicator :

- maps of mobility (Facebook data for good) - under investigation

**Comment by santilland** [comment]
https://www.google.com/covid19/mobility/
Initial proposed approach is to integrate data as "global" dataset, which can be selected from the dropdown, opening a map where it is possible to select countries, when clicking on a country it will show the mobility data for that country.

**Comment by aapopescu** [comment]
GSA Mobility Data:

[all_data.csv.zip](https://github.com/eurodatacube/eodash/files/6001057/all_data.csv.zip)
[borders_GL2017_Roads_EU27_UK_coord_names.zip](https://github.com/eurodatacube/eodash/files/6001058/borders_GL2017_Roads_EU27_UK_coord_names.zip)

- Suggested implementation:

1. Map Visualisation style: https://live.sixfold.com/ (border points in borders_GL2017, color code in all_data_csv)
2. Time browser (info in all_data_csv)
3. Selecting one point loads time series with waiting time (data in all_data_csv)

**Comment by santilland** [comment]
Story was added to indicator in branch gsadata

**Comment by Schpidi** [comment]
Mobility data was added on country level as proposed in #863 see https://race.esa.int/?poi=GG-GG. Please reopen if anything is missing.
