### ISSUE TITLE
GEOGLAM time selection crashes older mobile browsers

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#766]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 2.5.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/?poi=W6-N6">https://www.eodashboard.org/?poi=W6-N6</a></p>
<p><strong>Operating system:</strong> iOS</p>
<p><strong>Affected browser:</strong> Safari 12</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Try to change time selection</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Replace the layer without carshing</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>No comments</p>

**Comment by silvester-pari** [comment]
@lubojr maybe you can have a look into this, by either optimizing the GeoJSON and/or the way the layer is switched (not needing to refetch the GeoJSON)
