### ISSUE TITLE
Add temperature and humidity maps

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#777]
https://cds.climate.copernicus.eu/apps/c3s/app-c3s-monthly-climate-covid-19-explorer?delay=selected%20month&year_month=January%202021

**Comment by santilland** [comment]
Technical implementation done, waiting for inputs on content:
Are titles ok?
Is the air category ok? Not sure which one to use
Which colorscale label should we use?
Will there be a related story?

**Comment by AlessandroScremin** [comment]
here are the colorscales png...

![gradient__humidity_colourbar](https://user-images.githubusercontent.com/65602207/111336023-267db400-8675-11eb-8719-eb29cd8edb70.png)
![gradient_T2m_colourbar](https://user-images.githubusercontent.com/65602207/111336025-27aee100-8675-11eb-93b0-9057777786a2.png)
@santilland can you see them correctly? with title and axes values?

**Comment by santilland** [comment]
Looks good, i have committed it to the branch, should be deployed soon.

**Comment by AlessandroScremin** [comment]
@santilland    maybe you needed also wind fileds 

![gradient__windU_colourbar](https://user-images.githubusercontent.com/65602207/111632312-a2523a80-87f4-11eb-9f89-71ce2c70db39.png)
![gradient__windV_colourbar](https://user-images.githubusercontent.com/65602207/111632317-a2ead100-87f4-11eb-8592-9df392f2947d.png)

**Comment by aapopescu** [comment]
![Wind u field](https://user-images.githubusercontent.com/35488732/114187881-c82cb400-9948-11eb-9c28-e023b2020f10.png)
![Wind v field](https://user-images.githubusercontent.com/35488732/114187885-c95de100-9948-11eb-9bd2-fa69209ba6a3.png)
