### ISSUE TITLE
nasa covid-api custom indicator area draw configs

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#798]
Goal is to add the custom area draw configuration for already offered global datasets from NASA API which we also reference, documentation of `/timelapse` endpoint with examples of request & response https://github.com/NASA-IMPACT/covid-api/pull/113
- [x] CO2
- [x] NO2
- [ ] Nightlights global

**Comment by santilland** [comment]
The referenced pull request which implements this functionality has not been merged, so if i understand correctly the `/timelapse` endpoint currently only works for `no2-mean` and `no2-diff` so i guess for now we can reduce the priority of this ticket until this has been solved.
