### ISSUE TITLE
Integration of GSA mobility data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#800]
I have created a new issue as this data is quite different to what we have done so far so we will need to consider the effort involved and we should track the effort and status separate to the mobility data handled until now.

@santilland here is the GSA Mobility Data:

[all_data.csv.zip](https://github.com/eurodatacube/eodash/files/6001057/all_data.csv.zip)
[borders_GL2017_Roads_EU27_UK_coord_names.zip](https://github.com/eurodatacube/eodash/files/6001058/borders_GL2017_Roads_EU27_UK_coord_names.zip)

- Suggested implementation:

1. Map Visualisation style: https://live.sixfold.com/ (border points in borders_GL2017, color code in all_data_csv)
2. Time browser (info in all_data_csv)
3. Selecting one point loads time series with waiting time (data in all_data_csv)

_Originally posted by @aapopescu in https://github.com/eurodatacube/eodash/issues/758#issuecomment-781132159_

**Comment by santilland** [comment]
Current status is possibilities are being explored on how to best access the data, i.e. api or other approach.

**Comment by aapopescu** [comment]
new data:
[daily_reports_fixed.zip](https://github.com/eurodatacube/eodash/files/6123535/daily_reports_fixed.zip)

**Comment by aapopescu** [comment]
@santilland , an update to the data, values were corrected for some days in March 2021

[daily_reports_2021-03-10.zip](https://github.com/eurodatacube/eodash/files/6148544/daily_reports_2021-03-10.zip)

**Comment by santilland** [comment]
Hello  @aapopescu the sent file is an excel file, do you have also the csv version? just in case there are any export/conversion things to consider

**Comment by aapopescu** [comment]
can you please try this one?
[daily_reports_2021_03_10.csv.zip](https://github.com/eurodatacube/eodash/files/6155987/daily_reports_2021_03_10.csv.zip)

**Comment by santilland** [comment]
Data was updated, looks to be working as expected, deployment on `gsadata` branch

**Comment by santilland** [comment]
Story was added to indicator in gsadata branch

**Comment by Schpidi** [comment]
GSA data was added in #863 see https://race.esa.int/?poi=GSA-GSA. Please reopen if anything is missing.

**Comment by santilland** [comment]
GSA data was disabled need input from esa to decide if this indicator should be included again. I think usage rights for the data were missing
