### ISSUE TITLE
Add population data

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#802]
Convert to COG and create SH layer for 2020

https://sedac.ciesin.columbia.edu/data/set/gpw-v4-population-density-rev11

**Comment by AlessandroScremin** [comment]
FYI @JPatruno @Antonio-Romeo

**Comment by AlessandroScremin** [comment]
Hi @aapopescu @Schpidi @santilland 
I see this in High priority for release 3.0 and assigned to me, but is already done since 19/20 February 2021 and layers provided: ID: POPULATION_DENSITY.
 ID: RAW_POPULATION_DENSITY.


So please let me know of any issues with this layer, if any

**Comment by santilland** [comment]
Hello @aapopescu , we have population data in the trilateral instance as layer (https://eodash-trilateral.eox.at/?poi=W6-NASAPopulation) . Should we look into adding this dataset into the esa instance?

**Comment by santilland** [comment]
Layer was integrated into client, but dataset is not working as expected, it returns transparent tiles for "overview" zoom levels ~5 and below.
This happens in Sentinelhub, and the same behaviour happens in the client.
![image](https://user-images.githubusercontent.com/4036819/111292116-25825d80-8648-11eb-904e-c5b7f7dfda5d.png)

![image](https://user-images.githubusercontent.com/4036819/111292035-0f749d00-8648-11eb-8f2e-f49a7bc17b3e.png)

![image](https://user-images.githubusercontent.com/4036819/111292170-359a3d00-8648-11eb-99de-4e5c11b6b96d.png)
![image](https://user-images.githubusercontent.com/4036819/111292218-4054d200-8648-11eb-874c-64a9fb2b0032.png)

**Comment by AlessandroScremin** [comment]
Open an issue to Grega on eodash-data

**Comment by aapopescu** [comment]
thanks! @santilland , when the visualisation is solved, let's change the source also for the trilateral population indicator

**Comment by Schpidi** [comment]
done in #864
