### ISSUE TITLE
Use icons in the table view

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#809]
in the table view, add a visual cue for global indicators (e.g. globe icon instead of "all") - how about using country flags aswell?

**Comment by komninoschat** [comment]
For this, we have three design options:

1)
![1](https://user-images.githubusercontent.com/29049104/108846530-5a6e3800-75e7-11eb-8254-6d19b695bfde.png)
2)
![2](https://user-images.githubusercontent.com/29049104/108846581-6823bd80-75e7-11eb-9207-973e1182ada7.png)
3)
![3](https://user-images.githubusercontent.com/29049104/108846649-7a9df700-75e7-11eb-898e-36d8171e24bc.png)

@aapopescu, what do you think?
