### ISSUE TITLE
Zoom in button obscured by full screen button

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#821]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 2.5.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/?country=US&amp;poi=US03-E13c">https://www.eodashboard.org/?country=US&amp;poi=US03-E13c</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Safari 13</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://www.eodashboard.org/?country=US&amp;poi=US03-E13c">https://www.eodashboard.org/?country=US&amp;poi=US03-E13c</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>zoom in button visible on the indicator map (left panel)</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca </p>

**Comment by aapopescu** [comment]
https://github.com/eurodatacube/eodash/projects/3#card-56162054
