### ISSUE TITLE
SISTEMA Apulia Vodafone indicator 

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#829]
Data is being prepared.
Intent is to provide an array for the measurement parameter. It is not clear if this can be included in geodb.

Example image from SISTEMA
![image](https://user-images.githubusercontent.com/4036819/109970366-40260f80-7cf5-11eb-9891-3a5b7d7f9ece.png)

Approach show each category as a line on the plot.
There is a challenge with non uniformly distributed measurement times, it is proposed to use a different distribution type for the x axis (time) of the plot.
In order to interrupt the line connecting point a NaN value will be added between months.

It might be considered to add some markers/lines between months, depending on the results.

**Comment by aapopescu** [comment]
Data:

[combined_satellite_vodafone_analysis.zip](https://github.com/eurodatacube/eodash/files/6109111/combined_satellite_vodafone_analysis.zip)

**Comment by santilland** [comment]
I discussed with Alessandro the possibilities, the easiest integration approach for us (with as little modification as possible for the client) would probably be to handle it as the E10a6 indicator. Meaning we have one point AOI on the map (normal indicator) for each location, when you click on a point it shows the sub-aoi (region highlighted on the map, e.g.: https://eodash.eox.at/?poi=ES42a-E10a6) and then we load a simple line plot with a line/label for each of the available 8 groups.
To get the data to be able to do the plot we could use either an array encoded as string for the "Measurement Value", or as we have used it already before in the past the same approach but adding the information on the "Reference value". So in principle looking like this "[1.0, 2.0, NaN, 1.1, 0.5, NaN, 3.0, 4.0]".

**Comment by AlessandroScremin** [comment]
@santilland @aapopescu @JPatruno 

I try to collect the diverse input from sistema into this E10a6 compliant file...Several fields are missing...but would see if it could work...

In the Description column you have a string with the array  [ a, b, c, d, ...] as the header of values, and in the measurement value another array of values int he same order of the header  [1,0,4,5,.... ]. 
I didn't work on the AOI coordinates and site name codes (that should correspond to the geojson with polygon) , but If the structure works we could ask sistema to fill the excel...if necessary....

let me know your opinion on the structure @santilland , could it work for you?

the array should not be a problem for the geoDB as also N1 timeseries are in geoDB with array. All columns except dates are string so it is just up to you to read within  [ ]
kr

Alessandro
[Combined_readapted_SISTEMA_data.zip](https://github.com/eurodatacube/eodash/files/6130986/Combined_readapted_SISTEMA_data.zip)

**Comment by santilland** [comment]
Thank you Alessandro, i will have a look and let you know when i reviewed it.

**Comment by santilland** [comment]
Hello Alessandro, i think the structure should work, but there are some things missing as you said.
We would still need AOI (lat/lon) and Sub-AOI (WKT area definition) as well as a unique AOI_ID (maybe "IT_<Site Name>" could be used) per location.
I think the current Description is not good, as we use this field as subtitle in the data panel, so i would change it to a short description of the indicator.
The information on categories could be added in the "Reference Description" field (or in the "Rule" field).
So description could be "Identified number of workers per class on tomatoes cultivation fields".
And the other field be:
```
 [Foreigner - External Worker, Foreigner - Internal Worker, Foreigner with Italian SIM - External Worker, Foreigner with Italian SIM - Internal Worker, Italian - External Worker, Italian - Internal Worker, Masked - Internal Worker, Masked - External Worker] 
```
The labels might be a bit long and occupy quite some space in the plot, not sure if this could be reduced somehow.

**Comment by AlessandroScremin** [comment]
Hi  @santilland     FYI  @aapopescu @JPatruno 

I arranged the csv, adding AOI and SubAOI, AOI_ID as proposed, and try to trim a bit the workers class. Moved class workers to Rule column

Since the points of the polygons in the Sub AOI are huge, I added only one Polygon record for each AOI_ID, let say the first occurrence of each AOI_ID has the  Polygon (as you did for oter indicators).

could you try this version of the CSV....

only one side note: the AOI coordinates are not the center of the shapes but I take the first point in the polygon. Just ot say don't ex[ect to find the center point in the AOI.  

hope this fix all issues


[Combined_readapted_SISTEMA_data_3.zip](https://github.com/eurodatacube/eodash/files/6163487/Combined_readapted_SISTEMA_data_3.zip)

**Comment by santilland** [comment]
Hello @AlessandroScremin , thank you for the update, it seems we reached some limit for the field size with the subaois....
I am getting `Exception: field larger than field limit (131072)` when i try to parse the csv.
Would it be possible to simplify the features a little bit? Would also be great for performance reasons on the client.
If you are using qgis to convert from geojson to wkt this should be one step in between. Else maybe another option could be to use an online tool maybe like https://mapshaper.org/

**Comment by AlessandroScremin** [comment]
@santilland 
I wasn't aware of this issue, maybe it was for this reason they provided the geojsons related files?

These files are provided by SISTEMA, in order to make it faster I generated the csv from their multiple files into the agreed csv format. I also covnerted the geojson polygons into WKT...before wasting other time in arranging files....there are other limitation or issues you see with the csv?

**Comment by santilland** [comment]
it seems we have not had so large geojson as subaios until now

**Comment by santilland** [comment]
i think i have the original geojsons i will try to simplify the features, it would not be good to have to large features anyhow for the client i think

**Comment by AlessandroScremin** [comment]
Hi danioel I understood your point...but the geojosn are multipolygons quite complex...not sure the smoothing wiil be simple...

eg

![image](https://user-images.githubusercontent.com/65602207/111637192-7dac9180-87f9-11eb-87c6-4301fdaaa859.png)

**Comment by AlessandroScremin** [comment]
could it be enough simplified? but we have to teast each o fthem....
[IT_22_simplified.zip](https://github.com/eurodatacube/eodash/files/6164652/IT_22_simplified.zip)

**Comment by santilland** [comment]
ok, it seems the length of that wkt string is ok, was that the biggest geojson? if yes you could simplify the others with the same value and it should in theory work.
I am now having issues because the timestamp is not in iso format, so, still the generator has issues with the file.

**Comment by santilland** [comment]
for now i replaced all timestamps to a single day, just to see if it loads and at least the length of the subaoi seems to work fine, it loads in the client.
![image](https://user-images.githubusercontent.com/4036819/111646650-1e06b400-8802-11eb-979b-6e20bed3cc1c.png)
(right now in grey which is wrong - but it can be seen)
I am not completely sure the location is correct? Difficult to say.
Also we might consider making the title a little shorter.

**Comment by AlessandroScremin** [comment]
@santilland 
thanks for the test

Area is ok checked
Time my fault, in any case only yyyy-mm-dd
Was not the most complex...will generate new polygons and provide you the updated csv....

and hope this time works

**Comment by AlessandroScremin** [comment]
@santilland 

Sub AOI simplified and date formats corrected

hope this time work

Alesssndro


[Combined_readapted_SISTEMA_data_4.zip](https://github.com/eurodatacube/eodash/files/6165426/Combined_readapted_SISTEMA_data_4.zip)

**Comment by santilland** [comment]
Seems to be working nicely, thank you!
There is a test deployment for the e10a9 branch.

**Comment by AlessandroScremin** [comment]
@santilland 
THNAK YOU for the collaboration and patience...

Sent an amail with results to SISTEMA and let see if they have any comments

Ale

**Comment by Schpidi** [comment]
This was added in #851 see https://race.esa.int/?indicator=E10a9. Please reopen is anything is missing.
