### ISSUE TITLE
Loading of S-2 imagery on E13d2 is very slow

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#880]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 2.6.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/?indicator=E13d&amp;poi=PT1-E13d2">https://race.esa.int/?indicator=E13d&amp;poi=PT1-E13d2</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 89</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://race.esa.int/?indicator=E13d&amp;poi=PT1-E13d2">https://race.esa.int/?indicator=E13d&amp;poi=PT1-E13d2</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>faster load time or a notification that the imagery is loading </p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by lubojr** [comment]
Closing for now.
