### ISSUE TITLE
Implement area selection for NASA OMI data

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#882]
Similar approach to 

https://github.com/eurodatacube/eodash/issues/784

**Comment by leothomas** [comment]
Hi, 

Just adding some detail on the request made to us by Nasa scientists working on the NO2 and CO2 datasets. 

They would like the area selection + timeseries chart to be available for both the `NASA OMI` and `NASA OMI DIFFERENCE` datasets, as well as the `MEAN CO2` and `DIFFERENCE CO2` datasets. 

Please let me know if there is anything I can do to support this. 

Thanks!

**Comment by santilland** [comment]
To keep track of status:
After review for now we will wait to see if the API can be extended to accept a request for a time interval instead of a specific month. Evaluation of extension feasibility should be available before end of Mai.
