### ISSUE TITLE
Custom visualisation for Oil Storage Indicator 

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#887]
Phase 1: May 2021
- [ ] Data provided by Aresys on first 4 clusters
- [ ] API and Metadata for the European Oil Storage Index ready by Aresys
- [ ] Aresys provides the Story on one location (Rotterdam) to explain the methodology to use Sentinel 1 and Sentinel 2 in combination with AIS 

Phase 2: October 2021
- [ ] Data provided by Aresys on last 3 clusters
- [ ] Data and metadata available at the API by Aresys

![image](https://user-images.githubusercontent.com/35488732/115349969-c79be500-a1b4-11eb-8d82-dd92d68cf5cc.png)

### API :

The API consists of two HTTP endpoints that respond to HTTP GET requests. The responses are going to adhere to the JSON data interchange format. The endpoints are going to be served by an HTTP server that will reside on a publicly accessible domain. 

For security and data integrity reasons the HTTP server will leverage the HTTPS extension. The subdomain is yet to be decided, but it will be under the oilx.co domain, e.g. euindex.oilx.co

**Authentication**
In order to access the endpoints, an API key, provided by OilX, will be required. The API key must be provided via a custom authorisation header of the following form
Authorisation: OilXApiKey aabbccddeeff
Once the API is implemented, detailed documentation along with usage examples will follow.

**Cluster List URL resource: /esarace/v1/clusters**
This URL endpoint will return a JSON array, with each element representing an individual cluster. Each cluster will include a sites attribute, containing an array of
site objects belonging to it.

![image](https://user-images.githubusercontent.com/35488732/115349430-20b74900-a1b4-11eb-80be-5a6d0be3d567.png)

**European Oil Storage Index URL resource: /esarace/v1/europe**

This URL endpoint will return a JSON object representing the European storage index. An example response would look like this:
![image](https://user-images.githubusercontent.com/35488732/115349472-30369200-a1b4-11eb-9c7b-90b96c54e229.png)

@santilland, can you please revise the API specs above and say if changes/clarifications are needed?

**Comment by santilland** [comment]
Hello @aapopescu, i think it would be good if we discuss what exactly is the expected visualization in eodash to make sure we can check if the interface provides everything we need and understand better what values will be shown, but i think i have some preliminary questions that are valid in any case.

Two endpoints are planned. If i understand the description correctly the first one `clusters` provides the properties of the locations/elements "sorted" into clusters. 
The examples json is probably only a placeholder but I would expect to have more information per location/element, so at least their lat/lon positions.
I think this endpoint is also providing the values to be visualized, i am assuming it is the "Rate" value? The value is only present per complete cluster?
Then each location/element has "Band" information which is a color, should the PoIs in eodash be visualized in that color?

The `clusters` endpoint as well as the `europe` endpoint seem to only return 1 value (without timestamp), so i would understand it to be the "latest" value available when doing the request.

If the endpoints do not provide a history of the values with timestamps i think the only way to integrate this dataset would be to show the positions/elements in different colors based on a request to the endpoint that is done when the eodash client loads.

As for the `europe` endpoint we get one value per whole europe, i am not sure how we could visualize this information in eodash.

**Comment by santilland** [comment]
From our last discussion together i understand the following points:
 * Oilx will also provide timeseries data.
 * They are evaluating if a "dump" of the data (e.g. json containing all the information that will be provided) would be a viable option. Data size needs to be evaluated.
 * Ideally this "dump" could be requested through the provided API as data is updated weekly.
 * Other option would be to allow "filtering" by a time range through the API
 * EOX should be able to "digest" data on a weekly basis and serve it directly to the end user (instead of each client requesting the data from the API endpoint)
 * Best approach is to find the easiest method that works for all

**Comment by gspanos** [comment]
Hello, below I provide the new JSON schema for the **/esarace/v1/clusters** endpoint, as we discussed on the call:

1. It tries to avoid redundancy by not repeating the coordinates of each site more than once
2. It will return all clusters, sites and time series in one bulk response for simplicity
3. It uses the GeoJSON schema for [Features](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2)

```javascript
[
    {
        "cluster_id": 1,
        "name": "UK & Ireland",
        "series": [
            {"date": "2019-01-01", "Rate": 43.5, "Band": "Green"},
            {"date": "2019-01-08", "Rate": 48.5, "Band": "Red"},
            {"date": "2019-01-15", "Rate": 41.5, "Band": "Green"},
            {"date": "2019-01-22", "Rate": 25.5, "Band": "Green"}
        ],
        "sites": [
            {
                "type": "Feature",
                "properties": {
                    "id": 100012,
                    "name": "Sullom Voe",
                    "series": [
                        {"date": "2019-01-01", "Band": "Green"},
                        {"date": "2019-01-08", "Band": "Red"},
                        {"date": "2019-01-15", "Band": "Green"},
                        {"date": "2019-01-22", "Band": "Green"}
                    ]
                },
                "geometry": {
                    "type": "Polygon", 
                    "coordinates": [[
                        [-104.05, 48.99],
                        [-97.22, 48.98],
                        [-96.58, 45.94],
                        [-104.03, 45.94],
                        [-104.05, 48.99]
                    ]]
                },
            },
            {
                "type": "Feature",
                "properties": {
                    "id": 100058,
                    "name": "Teesport",
                    "series": [
                        {"date": "2019-01-01", "Band": "Green"},
                        {"date": "2019-01-08", "Band": "Green"},
                        {"date": "2019-01-15", "Band": "Green"},
                        {"date": "2019-01-22", "Band": "Green"}
                    ]
                },
                "geometry": {
                    "type": "Polygon", 
                    "coordinates": [[
                        [100.0, 0.0],
                        [101.0, 0.0],
                        [101.0, 1.0],
                        [100.0, 1.0],
                        [100.0, 0.0]
                    ]]
                },
            }
        ]
    },
    {
        "cluster_id": 2,
        "name": "Continent",
        "series": [
            {"date": "2019-01-01", "Rate": 43.5, "Band": "Green"},
            {"date": "2019-01-08", "Rate": 48.5, "Band": "Red"},
            {"date": "2019-01-15", "Rate": 41.5, "Band": "Green"},
            {"date": "2019-01-22", "Rate": 25.5, "Band": "Green"}
        ],
        "sites": [
            {
                "type": "Feature",
                "properties": {
                    "id": 100013,
                    "name": "Rotterdam",
                    "series": [
                        {"date": "2019-01-01", "Band": "Green"},
                        {"date": "2019-01-08", "Band": "Red"},
                        {"date": "2019-01-15", "Band": "Green"},
                        {"date": "2019-01-22", "Band": "Green"}
                    ]
                },
                "geometry": {
                    "type": "Polygon", 
                    "coordinates": [[
                        [-109.05, 41.00],
                        [-102.06, 40.99],
                        [-102.03, 36.99],
                        [-109.04, 36.99],
                        [-109.05, 41.00]
                    ]]
                },
            },
            {
                "type": "Feature",
                "properties": {
                    "id": 100068,
                    "name": "Antwerp",
                    "series": [
                        {"date": "2019-01-01", "Band": "Green"},
                        {"date": "2019-01-08", "Band": "Green"},
                        {"date": "2019-01-15", "Band": "Green"},
                        {"date": "2019-01-22", "Band": "Green"}
                    ]
                },
                "geometry": {
                    "type": "Polygon", 
                    "coordinates": [[
                        [100.0, 0.0],
                        [101.0, 0.0],
                        [101.0, 1.0],
                        [100.0, 1.0],
                        [100.0, 0.0]
                    ]]
                },
            }
        ]
    }
]
```

I hope the sample response is representative enough to make sense of the schema. Otherwise tell me if you need any clarifications

Please note that the **/esarace/v1/europe** endpoint remains as it is.

**Comment by santilland** [comment]
Hello, i think this schema provides all the information we need and should be easy to digest.
I am a bit curious about the geometry of the sites, right now it seems to be a 1 degree box/rectangle or a 4 point polygon.
For us it will be probably easier to have a geometry of type point with 2 coordinates for the center point of the site.

**Comment by gspanos** [comment]
@santilland understood. That's even easier for us since we have that information.

So assume that all geometry objects are gonna be in this form:
```javascript
"geometry": {
    "type": "Point", 
    "coordinates": [100.0, 1.0]
}
```

**Comment by santilland** [comment]
Perfect, sounds great, thanks!

**Comment by santilland** [comment]
@gspanos any news on possible access to the API?

**Comment by gspanos** [comment]
@santilland I expect that we're gonna have a first version of the API up and running on Monday, 21st of June. Is that ok?

**Comment by santilland** [comment]
Sounds great, thank you!

**Comment by gspanos** [comment]
@santilland I forgot that there's a bank holiday on Monday. Let's make it on Tuesday if it's not too much of an inconvenience

**Comment by santilland** [comment]
Sure, no problem!

**Comment by gspanos** [comment]
Still working on the server setup and solving some obstacles. Will send an email with the appropriate access creds once it's ready.

**Comment by aapopescu** [comment]
1) Would there be the option to see also total Europe?
	Should be possible with the "global indicator" approach mentioned by Daniel, even if this would be a graph and all other global ones are maps.

2) We were wondering if there is any easy way include some info (e.g. storage capacity, connectivity port/pipeline etc.) on the clusters and storage sites in the narrative that will be shown next to the indicator? 
	Thanks for the extra information. The short write-ups are good. We would also need the short description of the methodology as presented in the Proposal (fig 6 and fig 7 + text)? For the S1/S2 view with slider, if you can provide an animated gif we can include this in the "story".

3) Add a time averaged graph on-top of the  monthly values graph. This might help to better appreciate the times series development, as it fluctuates quite a bit (see two examples below) 
	

4) Implement scaling of the Y-axis from -1 to 1. 
	For the normalisation, can we consider 50% as the baseline with 0-100% being the min/max, or should the min/max interval be taken from the dataset? 

i5) Activation buttons for the "very low", "high" etc. time series points is not adding a lot of value right now. We could consider to merge very low/low and high/very high to make it more binary whether we are in a regular environment or not.
	Ok for the merge of "very low"+low, very "high+high"

**Comment by gspanos** [comment]
@aapopescu is any of this directed toward us (OilX), or is it part of the general UI/UX discussion?

**Comment by aapopescu** [comment]
> @aapopescu is any of this directed toward us (OilX), or is it part of the general UI/UX discussion?

ignore for the moment :)

**Comment by gspanos** [comment]
Hello, we updated the europe endpoint so that it includes a `Date` value.

**Comment by aapopescu** [comment]
- add total Europe as "global indicator" 
- Add a time averaged graph on-top of the monthly values graph
- remove % and consider qualitative scale from Low to High  
- display Low/Regular/High values for each Site in qualitative manner. Allocate 3 fixed values outside the normal interval to help build the visualization: 0.2 =Low, , 0.5 = Regular and 0.9 = High. This would be transparent for the user who would only see them located high low or in the middle on the chart, as below. 

![image](https://user-images.githubusercontent.com/35488732/127885839-893ebb5d-846f-417d-9480-1d90ed448009.png)

- Anca to provide stories

**Comment by aapopescu** [comment]
@lubojr , FYI
