### ISSUE TITLE
Tab switching consistency

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#891]
When swithcing tabs in an indicator,
- truck detection etc.: it should show the same AOI that is selected in the other tab (sync AOIs and also zoom to them on tab switch)
- covid data: selected coutnry should also be synced (and zoom to) between tabs

additional comments:
COVID19 data and Trucks - Maps and Tabs behaviour:
Tab use is confusing because user has to select country /AOI twice to look at different charts.
Two possible solutions:

 (not optimal) once a country/AOI is selected on one tab it should automatically be selected on the other tab too, so switching between tabs automatically changes the chart
 (better) use tabs on charts instead of map; map selection is done once, both charts updated

**Comment by santilland** [comment]
Same AOI selection works across tabs.
On Covid data country selection is not synced, needs to be done
