### ISSUE TITLE
User Interface redesign

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#893]
Consider a redesign of the user interface including:

- [x] better selection of global indicators
- [x] either use the main map also for data visualization or
- [ ] make main map less prominent when one POI is selected, to make clear the difference between data selection/data visualization
- [ ] consider using main map for country selection (e.g. mobility or covid data)
- [x] allow different "themes" to be visualized such as "covid", "polar" or "biomass", and allow an option to switch between them

**Comment by santilland** [comment]
Data with country selection was converted to POI location dataset, map was not made less prominent but selected poi (circle symbol) is not shown when an indicator with eo data is selected
