### ISSUE TITLE
World, Mobility Data Dataset Nothing Happens when going fullscreen

### ISSUE THREAD

**Issue by Scartography** [eurodatacube/eodash#902]
**Describe the bug**
when going full screen when using the global "World, Mobility Data" the interaction with the map provides nothing (just highlighting the country polygons). Works fine (with information) when using in the regular UI on firefox.

**Suggested Solution**
Disable the fullscreen map mode for this info-tool.

**Comment by Scartography** [comment]
* There is an option to enlarge the right portion of the dashboard. Therefore why is there a fullscreen map button for the maps on the right or the enlarge button under same logic?

**Comment by aapopescu** [comment]
thanks for the feedback, @Scartography
With the latest update, the country selection in fullscreen loads the chart on top of the map

**Comment by Scartography** [comment]
Thanks for the update, the selection of the country and graph works nicely. 
Sadly the close graph top left `[ x ]` button does not seem to do anything on Firefox 88.0 and Chrome
