### ISSUE TITLE
Population density from facebook

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#919]
Should be available from NASA API / needs to be reviewed id data is actually ready

https://earthdata.nasa.gov/covid19/explore/global?map=-74.0197%2C40.8648%2C8.88&layers=fb-population-density&date=2020-12-15

**Comment by aapopescu** [comment]
- Legend: can we get actual numbers, i.e. min and max value of people/sqkm?
- Make default baselayer EOX cloudless
- When ready, archive previous Population indicator
- Anca to add story

**Comment by santilland** [comment]
- [ ] Legend: I dont know if there is a source with this information
- [x] EOX cloudless as default baselayer
- [x] Archive population indicator
- [ ] Indicator story

**Comment by santilland** [comment]
See https://github.com/NASA-IMPACT/covid-api/issues/126 for update to colormap legend
