### ISSUE TITLE
Correct country names to be compliant with EuroStat names

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#921]

**Comment by Schpidi** [comment]
Using names from https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes:
- [ ] Macedonia -> North Macedonia
- [ ] Republic of Serbia -> Serbia

Czechia is the official name according to the page linked above.

@aapopescu please confirm, thx.

**Comment by santilland** [comment]
Names updated in current staging, if these are the only changes necessary issue can be closed.

**Comment by aapopescu** [comment]
Thanks, Ok for Europe.
