### ISSUE TITLE
Dashboard Technical Background and Integration Guide

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#952]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 2.6.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://eodashboard.org/">https://eodashboard.org/</a></p>
<p><strong>Operating system:</strong> Windows OS</p>
<p><strong>Affected browser:</strong> Firefox 89</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>The document &quot;Dashboard Technical Background and Integration Guide&quot; is mentioned extensively, and is supposedly at the Resources page at <a target="_blank"  href="https://www.eodashboardhackathon.org/about">https://www.eodashboardhackathon.org/about</a> , but all the links to it in the documents there just point back to the &#39;Resources&#39; page.
&quot;... please also see the companion guide -- the Dashboard Technical Background and Integration Guide-- which is located on eodashboardhackathon.org/about.</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Entry on Resources page with a direct link to Dashboard Technical Background and Integration Guide&quot;</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>No comments</p>

**Comment by santilland** [comment]
Thank  you for your feedback.
The "Technical Background and Integration Guide" has now been added to the resource page.
Feel free to reopen the issue if there are further questions.
