### ISSUE TITLE
Create static page url for the race challenges information

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#956]

**Comment by santilland** [comment]
For example to announce winners

**Comment by santilland** [comment]
There is now a /challenges endpoint that shows different content based on the loaded instance. The markdown files that are shown are the following:
/general/eodashboardhackathon.md (trilateral)
/general/challenges.md (esa)
and the corresponding pages on staging can be found with /challenges.
I think technically this ticket can be closed.

**Comment by Schpidi** [comment]
@aapopescu I see you assigned this to @santilland, do you want us to copy and adapt the information that is published on https://eo4society.esa.int/race-dashboard-challenges-2021/, https://eo4society.esa.int/2021/08/01/rapid-action-on-coronavirus-and-eo-race-dashboard-challenge-3/, and https://eo4society.esa.int/2021/07/08/race-challenges-2021-first-winner/? Is there any other points that shall be included? Feel free to add any information to the two markdown files as needed.

Btw. is Patrick on GitHub to add him to this issue?

**Comment by aapopescu** [comment]
Hi @Schpidi , the content for the race challenges is already available in the eodash-data. I uldated it recently, so it can be used as is. 

Not sure if Patrick is on Github.

**Comment by aapopescu** [comment]
Challennges.md

**Comment by santilland** [comment]
Hello @aapopescu, the endpoints are already available, so when we do a data release the endpoints are updated to the latest Challenges.md file version in the data repository, you can go to `/challenges` either on race or trilateral urls already. Should we close this ticket?

**Comment by aapopescu** [comment]
Great yes can be closed

**Comment by santilland** [comment]
Thanks!
