### ISSUE TITLE
Missing polygon tool

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#957]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 2.6.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://eodashboard.org/?poi=CN01-N7">https://eodashboard.org/?poi=CN01-N7</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 89</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://medium.com/euro-data-cube/find-covid-19-lockdown-measures-impacts-on-your-citys-air-quality-b628872b3251">https://medium.com/euro-data-cube/find-covid-19-lockdown-measures-impacts-on-your-citys-air-quality-b628872b3251</a></p>
<p>Trying to follow this tutorial but stuck on step 3 -- there is no tool that allows for drawing a polygon to define an area of interest. The current EO platform only shows the layers icon to toggle the base map, country labels, etc.</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Draw polygons to define area of interest and produce charts with indicator values over time in that specific area</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p><a target="_blank"  href="mailto:&#x61;&#115;&#104;&#108;&#x65;&#x79;&#64;&#97;&#100;&#x6d;&#x63;&#102;&#x2e;&#111;&#x72;&#103;">&#x61;&#115;&#104;&#108;&#x65;&#x79;&#64;&#97;&#100;&#x6d;&#x63;&#102;&#x2e;&#111;&#x72;&#103;</a> </p>

**Comment by lubojr** [comment]
Closing for now. No drawing on this POI.
