### ISSUE TITLE
Reprocessed imges in Collection

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#959]
Dear @gmilcinski @gobaRules 

I have a collection with hundreds of COGs in sentinel Hub with tiles from the S3 bucket in Mundi.

No I received an email from the owner that reprocessed all the COGs so I need to update them.

It is enough to overwite the objects in the S3 bucket in mundi, or do I have to remove the collection, the files from the bucket and reingest all the new files?

kr

ALessandro

**Comment by gmilcinski** [comment]
Hi @AlessandroScremin,
in general, if the index of the data did not change (i.e. internal tiling, location, ...), I think it might be safe to simply replace the data. If you are certain that there was no change (apart of the pixel values, obviously).

That said, the appropriate way would be to update tiles using:   
https://docs.sentinel-hub.com/api/latest/reference/#operation/updateByocCollectionTileById

I guess it should not be difficult to do a python script? If needed, we can help you with this.

Best,
Grega

**Comment by AlessandroScremin** [comment]
Hi @gmilcinski  @gobaRules 

Clear. I noticed that the images are changing only on pixels values, but also some of the files extensions is changign a bit: most are .tiff and some .tif in the buckets....the new ones are all .tif  

I created  new collection IDs for speedup the process but talking with EOX we noticed that the collection IDs in the JN templates and code of the dahsboard are the one in operation (4f5f67f1-5715-4f2b-8c98-ae57948ee2f5
and
dc461d36-d855-4021-93e6-686f08d48f3d 
....so changing the COllection ID is going to get more complciated than expected...code and JNs tempaltes to be changed

What about  delete the tiles from the operational collection (the ones above) and from the file fromthe bucket and reingest all the new images from scratch into the same operational colelction ID? same band name, same no data value...(only extensions of the file is changing)

do you see some contrainsts?

the collection ID s are: 
4f5f67f1-5715-4f2b-8c98-ae57948ee2f5
and
dc461d36-d855-4021-93e6-686f08d48f3d

**Comment by gmilcinski** [comment]
If the bands stay the same (number of them, value type), your approach seems like a good option. I suggest you give it a try.

If you stumble into the problems, do create a new collection and fill it up with new data. Then we will, in the back-end, delete the old collection completley and changed the ID of the olf one, so that JNs will stay the same. This will cause quite some work and potential problems as well (we have not yet done this, but I do not see a reason that it would not work). Therefore your suggestion is still a better one. This one should only be as a backup.

**Comment by lubojr** [comment]
@AlessandroScremin Please reopen if still valid. Thanks.

**Comment by AlessandroScremin** [comment]
@lubojr  it worked so ok on closing it

Thanks
