### ISSUE TITLE
Allow credential free access to geoDB RACE collections

### ISSUE THREAD

**Issue by dzelge** [eurodatacube/eodash#963]
**Is your feature request related to a problem? Please describe.**

The RACE dashboard is a React single age application (SPA). Developing RestFul access to the geoDB API using client credentials could expose these secrets. Hence, a public rest access is required to anyway public collections. 

**Describe the solution you'd like**

Provide a public geoDB RestAPI endpoint to RACE collections. 

**Describe alternatives you've considered**

Provide long lived tokens. However, the used auth provider only provdies tokens with a maximum lifetime of 1 month.

**Comment by lubojr** [comment]
@dzelge Closing now as part of the issue cleanup. Please re-open if still valid and planned in the future.
