### ISSUE TITLE
Map issues

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#975]
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 2.6.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/?indicator=E13d&amp;poi=AT4-E13d2">https://race.esa.int/?indicator=E13d&amp;poi=AT4-E13d2</a></p>
<p><strong>Operating system:</strong> Linux OS</p>
<p><strong>Affected browser:</strong> Chrome 91</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Open <a target="_blank"  href="https://race.esa.int/?indicator=E13d&amp;poi=AT4-E13d2">https://race.esa.int/?indicator=E13d&amp;poi=AT4-E13d2</a> and switch between &quot;Airport traffic&quot; and &quot;Detected airplanes&quot; tabs. After switching back and forth to the &quot;Detected airplanes&quot; tab the map is &quot;confused&quot; and zooming and panning is behaving strangely.</p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>Interactively working map</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Stephan</p>

**Comment by Schpidi** [comment]
seems to be fixed, thx
